### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by martinmasse** [intercom/intercom-ios#100]
Hello,

Can you please use a string bundle for the text displayed in the messenger so we can localize it to another language?

Thanks

**Comment by jeanfw** [comment]
:+1:

**Comment by Linushellberg** [comment]
+1

**Comment by dan-intercom** [comment]
Hey @martinmasse, thanks for the request. We want to add localisation support for the SDKs soon. We understand how important this is and the value this brings to your users. Stay tuned! 

Thanks!
Dan / PM, Mobile SDKs

**Comment by martinmasse** [comment]
Merci!

**Comment by jeanfw** [comment]
@dan-intercom great to hear it's coming soon, can you share any rough ETA ? thanks !

**Comment by adriane0815** [comment]
:+1:

**Comment by mtet88** [comment]
:+1:

**Comment by shoby** [comment]
:+1:

**Comment by laurrentt** [comment]
:+1:

**Comment by antoinebis** [comment]
Any updates on this? Thanks!

**Comment by mberube09** [comment]
Would it be possible to make it so we can specify the locale to use? (not the default one from iOS)

**Comment by jtreanor** [comment]
@antoinebis No updates currently.

@mberube09 This is certainly something we will take into account when implementing the feature. For example: You might not want Intercom to appear in French if you have no French speakers in your company.

**Comment by rockerhieu** [comment]
:+1:

**Comment by hatunike** [comment]
Would love an update on this - time frame?

**Comment by jeanfw** [comment]
Bump

**Comment by kdawgwilk** [comment]
:+1:

**Comment by esvp** [comment]
A quick work-around we used. When you open the Intercom messenger view, a new window gets added. Quickly do a recursive search in this window for the text view containing the welcome message and swap the text in place if found. (It's ugly, but gets the job done in circa 20 lines of code)

**Comment by jtreanor** [comment]
We really do appreciate everyone's feedback on this.

We don't have a timeframe update but it certainly will be added at a future date.

@esvp The workaround you are using is likely to break in future and we can't guarantee stability with the technique.

**Comment by Telemakhos** [comment]
C'mon guys... this can be done in one sprint.. no excuses!

**Comment by antoinebis** [comment]
Updates on this ?!

**Comment by diakonos** [comment]
👍🏼

**Comment by jtreanor** [comment]
[Version 3.0.0](https://github.com/intercom/intercom-ios/releases/tag/3.0.0) has added localization support for 38 languages. See [here](https://docs.intercom.io/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/localize-intercom-to-work-with-multiple-languages) for more information and let me know if you have any questions at all.

**Comment by Telemakhos** [comment]
Great job! Thank you!
