### ISSUE TITLE
Universal links handling

### ISSUE THREAD

**Issue by kirpichenko** [intercom/intercom-ios#101]
Hey. We are going to include some universal links in the messages. But currently if user taps the link Safari is opened. Is it possible to somehow to handle the tapped link inside the app?
Thanks

**Comment by adamkmccarthy** [comment]
Hi @kirpichenko, thanks for bringing this up. We don't have any configurable way to do this now but we'll add support for universal links so that you'll be able handle them as you wish.

**Comment by kirpichenko** [comment]
Thanks for you response. Do you have any rough estimations for this?

**Comment by adamkmccarthy** [comment]
@kirpichenko I do not i'm afraid.

**Comment by lchenay** [comment]
Universal links works with intercom-ios for many urls. For exemple
https://twitter.com/intercom?lang=fr
https://itunes.apple.com/fr/app/intercom-for-ios/id739927601?mt=8
...

Clicking on those link on ios9 inside an intercom message works well and open app if user have it allready installed, or open safari as fallback.

But it doesn't works for testflight url: https://beta.itunes.apple.com/v1/app/appId

Does intercom-ios make something special with testflight link?

Opening an universal link should works nativly without doing any works according to the doc https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html

We have making same test sending message inside Intercom app, this time all urls works well.

**Comment by adamkmccarthy** [comment]
@lchenay I haven't tried a universal TestFlight link, is it possible that Apple haven't deployed the correct `apple-app-site-association` entitlement to support `https://beta.itunes.apple.com`? The SDK has no special handling in place for this yet so there's no special behaviour happening for these urls.

**Comment by lchenay** [comment]
itunes.apple.com and beta.itunes.apple.com haven't an apple-app-site-association available.
But even without it, those link works from mail, messages, Intercom native app, website... (without any Safari redirection trick as we could see in ios8)

Except for intercom-ios. Click on those link inside an message displayed by intercom-ios does nothing. Even Safari don't open.

**Comment by adamkmccarthy** [comment]
Interesting, ill take a look :+1:

**Comment by adamkmccarthy** [comment]
@lchenay do you have a specific message in Intercom I might be able to look at to see if I can reproduce this issue? I've just tested a message on iOS 8 & 9 with iTunes, TestFlight, Twitter and our own Intercom links and they're all working as expected :(

**Comment by lchenay** [comment]
Yes, i just send me a new test. Message n°13569093 on app iq71xvb7

**Comment by adamkmccarthy** [comment]
Perfect, thanks.

**Comment by adamkmccarthy** [comment]
@lchenay is it possible that this is related to the `LSApplicationQueriesSchemes` scheme changes introduced in iOS 9? I've been able to reproduce some of what you're seeing in iOS 9 via the observations in https://github.com/intercom/intercom-ios/issues/103. I've also looked at the TestFlight app's plist and those keys aren't included, which might support why those links aren't opening as they used to.

**Comment by jtreanor** [comment]
2.3.15 has just been released.

Other apps' universal URLs will open correctly now. If you have universal URLs in your own app unfortunately these will still open in Safari. [Apple's docs](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html) state: 

> It’s important to understand that if your app uses openURL: to open a universal link to your website, the link always opens in Safari instead of getting redirected to your app. iOS recognizes that the call originates from your app and therefore should not be handled as a universal link.

The issue was in part due to the changes in `-[UIApplication canOpenURL:]` in iOS 9. There is also a bug in iOS 9 that may continue to cause this issue until Apple resolve it: http://awkwardhare.com/post/121196006730/quick-take-on-ios-9-url-scheme-changes

**Comment by adambolcsfoldi** [comment]
Is this still true? Is there still no way to get Universal Links embedded in messages to open inside your own app?

**Comment by jtreanor** [comment]
@adambolcsfoldi Yes, this is still the case as Apple's documentation states above. Is this a problem for your app?

**Comment by adambolcsfoldi** [comment]
We would like to have some way to send messages with clickable links that take the user to specific content within the app. As far as I can tell there is no way to accomplish this (?).

**Comment by jtreanor** [comment]
@adambolcsfoldi This can be achieved using custom url schemes. For example, when configured correctly you can send a message that links to `you_app://somewhere`.

**Comment by grifotv** [comment]
@jtreanor this approach with custom URL schemes only work as a notification when the app is either closed or in the background as far as I know.

What would be the best way to send such a link from within a message?

**Comment by grifotv** [comment]
@jtreanor sorry, my bad - I didn't realise we can add links to selected texts in Intercom messages:

<img width="243" alt="screen shot 2017-08-22 at 10 11 24" src="https://user-images.githubusercontent.com/435351/29557903-6dbc0994-8722-11e7-9da1-6b1405a10254.png">

<img width="342" alt="screen shot 2017-08-22 at 10 11 35" src="https://user-images.githubusercontent.com/435351/29557910-7150ece6-8722-11e7-811a-aedc1cfde72e.png">

**Comment by mieszko4** [comment]
@adamkmccarthy does intercom sdk have some kind of event handler for link clicks that we could attach to and override as we wish?

My scenario:
In our ios app we are using [branch.io](https://github.com/BranchMetrics/react-native-branch-deep-linking) and they provide special method `openURL` for universal links that are associated to our app so that such internal links can open inside of the app instead of going to Safari.

It would be great if I could override default behaviour of link click from intercom's message - I would then check if link is an internal universal link anduse branch's `openURL` else I would let intercom sdk handle the click.
