### ISSUE TITLE
supportedInterfaceOrientations statusBar

### ISSUE THREAD

**Issue by kobelb** [intercom/intercom-ios#102]
If I modify the Sample app's ITCViewController.h to have the following method

```
- (UIInterfaceOrientationMask) supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskPortrait;
}
```

and then click "Open Intercom" and rotate the phone to the left so that it appears landscape like below:

![simulator screen shot oct 15 2015 7 07 21 am](https://cloud.githubusercontent.com/assets/627123/10512026/6c441f3e-730b-11e5-9719-635147111891.png)

and then I close the Intercom window, the status bar becomes stuck to the side that it was on as seen below:

![simulator screen shot oct 15 2015 7 08 20 am](https://cloud.githubusercontent.com/assets/627123/10512041/87dc18f0-730b-11e5-90b0-0de2ccc9235a.png)

**Comment by jtreanor** [comment]
This has been fixed in 2.3.13. Intercom now respects `supportedInterfaceOrientations` of your app's root view controller.
