### ISSUE TITLE
Deeplinks in latest sdk

### ISSUE THREAD

**Issue by Linushellberg** [intercom/intercom-ios#103]
Hi,
Deeplinks in messages is not working with the latest sdk.
It worked with version 2.3.0 for us.

Only http hyperlinks seem to work now in the messenger.
If we use our app url scheme nothing will happen when clicking the link.

**Comment by adamkmccarthy** [comment]
Thanks @Linushellberg, I think this is related to https://github.com/intercom/intercom-ios/issues/101. Is 2.3.0 working for you in iOS 9?

**Comment by Linushellberg** [comment]
Hi,
You are right. This is a iOS 9 only bug. Works great on < iOS 9
Might be related to #101 but universal links is something different.
This is links with our url scheme like ridestore://product/1

**Comment by Linushellberg** [comment]
Found the issue.
They changed canOpenURL in iOS9 so you have to allow what url schemes the app is allowed to query.
So just added the url scheme to LSApplicationQueriesSchemes in info.plist

So not a issue in the SDK, Sorry for wasting your time!

**Comment by adamkmccarthy** [comment]
Thanks @Linushellberg, that one completely passed me by! I've done some quick testing with our own app here and i've been able to see both sides of that problem with `LSApplicationQueriesSchemes`. Thanks for letting us know.
