### ISSUE TITLE
Swift 2.1 Xcode 7.1

### ISSUE THREAD

**Issue by macdevnet** [intercom/intercom-ios#104]
I am trying to use the SDK in a Swift 2.1 App (in Xcode 7.1) but I am experiencing linker issues. 
Are there known issues with Swift 2.1 / Xcode 7.1

**Comment by adamkmccarthy** [comment]
Hi Scotty, thanks for letting us know. I haven't seen any issues with the swift side of things but I haven't had the chance to press it properly with 7.1, I'll take a look and see what's up.

**Comment by adamkmccarthy** [comment]
@macdevnet out of interest, did you manually integrate by dragging the framework into your project? Xcode 7 has a bug in it that no longer sets framework search paths and things like that so it might also affect the module map's ability to find the right libraries. Could you check those framework search paths and see if you have anything set? Thanks!

**Comment by macdevnet** [comment]
Framework paths were fine ... I took a look at the podspec and saw the app also needed libicucore and libxml2 ... after adding them to the project it seems to work ... might be worth updating the readme on that one.

**Comment by adamkmccarthy** [comment]
Perfect, thanks @macdevnet.

**Comment by jtreanor** [comment]
This is probably an issue with 7.1, those libraries are should be linked automatically from the module map.
I'll look into this tomorrow.

**Comment by jtreanor** [comment]
I have added a note to the manual install steps in the readme to work around the Xcode bug.

Hopefully Apple will address the issue soon.
