### ISSUE TITLE
New messages don't show up in the thread view

### ISSUE THREAD

**Issue by tals** [intercom/intercom-ios#105]
This was tested using the Sample app from this repo.

Essentially while the user has the chat thread open, incoming messages do not show up.
As soon as you leave that screen (by pressing back to reach the conversation view or press "X" to go back to the app), the new message suddenly appears.

Here's a video illustrating the problem: https://www.dropbox.com/s/v0okq5dq7mr7x2o/intercom.mov?dl=0
I've sent a reply from the website around the 9s mark. As you can see, it doesn't appear in the UI until I navigate away from it (at 16s).

 
Any idea whats going on?

**Comment by jtreanor** [comment]
This is not an issue with Intercom for iOS.

This can happen if your Intercom plan does not include real time message delivery.
