### ISSUE TITLE
SDK doesn't use localised welcome message in new conversation window

### ISSUE THREAD

**Issue by jeanfw** [intercom/intercom-ios#106]
I've set a localised welcome message for our French-speaking users in the Intercom Messenger settings. The text displays in the correct language on web browser messenger windows, but the intercom-ios still shows the default welcome message (in English) on devices with a French locale.

Settings:
![screen shot 2015-10-29 at 12 11 10](https://cloud.githubusercontent.com/assets/2714769/10817161/678d811e-7e38-11e5-9e87-eef5e20bce16.png)

iOS on French locale phone:
![img_0915](https://cloud.githubusercontent.com/assets/2714769/10817162/69539934-7e38-11e5-84b6-c8cb7a315c24.PNG)

I'm opening a separate issue from Localisation (#100) which is a feature, and this is more of a bug which I'm wondering if you could fix earlier (without waiting for full localisation support)?

Thanks!

**Comment by jtreanor** [comment]
Hi @jeanfw,

Thanks for opening this issue. We will address this as part of #100 so we can track them together.
