### ISSUE TITLE
Send device language to Intercom user profile

### ISSUE THREAD

**Issue by jeanfw** [intercom/intercom-ios#107]
Similar to what the JS SDK does by detecting the browser language, we'd need the iOS SDK to set a language property on the user automatically, based on the phone's NSLocale preferredLanguages. 

Is it possible to add that please?

It's quite important for us to be able message users in their language whenever possible. Thanks

**Comment by jtreanor** [comment]
Hi again @jeanfw 

We will also tackle this as part of #100
