### ISSUE TITLE
Layout advice

### ISSUE THREAD

**Issue by ded** [intercom/intercom-ios#108]
Hi there,
I could use some guidance in tweaking the layout of the `UIWindow` of the messenger. By default, calling `Intercom.presentConversationList()` opens a full modal window... and I was wondering if it's possible to set the frame to to be within a navigation bar, and a bottom tab bar. Thus about 40 points from the top and bottom.

**Comment by jtreanor** [comment]
Hi @ded,

Unfortunately this is not customisable right now. We will keep your feedback in mind though.
