### ISSUE TITLE
show last active thread (more control over presentMessageComposer?)

### ISSUE THREAD

**Issue by tals** [intercom/intercom-ios#109]
As it stands right now, it's non trivial for the user to send more than one message in a thread.
There is no API for displaying the last thread/specific thread, and both presentMessageComposer and presentConversationList have drawbacks:

In our use case, we want to have a single "Leave us feedback" button, but the behaviors we can implement with the current APIs are far from ideal.

#### presentMessageComposer ####
Always open up a *new* thread. It's problematic since it may appear to the user that their feedback was lost.
The only way to reach the old message is by clicking on the top-left back button, but that's ambiguous due to the modal nature of Intercom's iOS UI ("will this take me back to the app?").

#### presentConversationList ####
The problem here is that we want to have a "leave feedback" button, and having it go to the conversation list is confusing and adds an extra step.

Both behaviors have pretty big drawbacks.
Any ideas?

**Comment by jtreanor** [comment]
Hi @tals,

Thanks for the suggestion. This is a good idea and we will definitely consider it for a future release :smile:

**Comment by tals** [comment]
Is there a way around this issue? It makes it very hard for us to leverage Intercom from iOS.
