### ISSUE TITLE
Crash in -[ICMMetric incrementMetric:]

### ISSUE THREAD

**Issue by newyorkpizza** [intercom/intercom-ios#110]
I just started seeing some crashes come in with this stack track for iOS 9.2.0. My app uses Intercom v2.3.3.  

Has anyone else seen this problem? (Note that the problem occurs in an iOS 9.2 beta release, so it might be an Apple issue.)

	Fatal Exception: NSInvalidArgumentException
	-[__NSDictionary0 setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x13f50d2a0

	Thread : Fatal Exception: NSInvalidArgumentException
	0  CoreFoundation                 6471112960 (Missing)
	1  libobjc.A.dylib                6461079424 (Missing)
	2  CoreFoundation                 6471140892 (Missing)
	3  CoreFoundation                 6471128504 (Missing)
	4  CoreFoundation                 6470096524 (Missing)
	5  FooApp12                       4298194948 -[ICMMetric incrementMetric:] (ICMMetric.m:36)
	6  FooApp12                       4297988196 +[ICMBridge registerUnidentifiedUser] (ICMBridge.m:123)
	7  FooApp12                       4296504272 -[FAAppDelegate application:didFinishLaunchingWithOptions:] (FAAppDelegate.m:97)
	8  UIKit                          6552641632 (Missing)
	9  UIKit                          6554929488 (Missing)
	10 UIKit                          6554946764 (Missing)
	11 UIKit                          6554934740 (Missing)
	12 FrontBoardServices             6493878212 (Missing)
	13 FrontBoardServices             6493879108 (Missing)
	14 CoreFoundation                 6470815484 (Missing)
	15 CoreFoundation                 6470814096 (Missing)
	16 CoreFoundation                 6470805136 (Missing)
	17 CoreFoundation                 6469949056 (Missing)
	18 UIKit                          6552612572 (Missing)
	19 UIKit                          6552590060 (Missing)
	20 FooApp12                       4295942736 main (main.m:16)
	21 libdyld.dylib                  6465366200 (Missing)

**Comment by jtreanor** [comment]
Hi @newyorkpizza.

This issue was fixed in 2.3.9 of Intercom for iOS. If you update to the latest version it should work fine.
