### ISSUE TITLE
Memory leaks after calling logout

### ISSUE THREAD

**Issue by idcuesta** [intercom/intercom-ios#111]
Hi there,

When I profile my app, I can see some memory leaks caused by Intercom SDK.

<h2>Steps to reproduce it</h2>
- I log into my app, so Intercom SDK is initialised with a new user
- I do some stuff within the app, so some Intercom events and user updates are triggered
- I logout in the app, so Intercom logout method is called
- After few secs the memory leaks appear

I am currently on version 2.3.11 of the Intercom SDK

<h2>Screenshot</h2>
![screen shot 2015-11-12 at 09 32 58](https://cloud.githubusercontent.com/assets/2726409/11114975/6054b6a4-8920-11e5-9166-3b1089bda10b.png)

**Comment by jtreanor** [comment]
Hi @idcuesta :smile: 

Thanks for reporting this and giving all this detail.

I will investigate this and keep you updated here.

**Comment by jtreanor** [comment]
This has been fixed in 2.3.12.

**Comment by idcuesta** [comment]
Thanks @jtreanor :+1:

**Comment by jtreanor** [comment]
No problem 😄 Thanks for reporting!
