### ISSUE TITLE
open source the sdk

### ISSUE THREAD

**Issue by tals** [intercom/intercom-ios#112]
Hey,

Are there any plans to open source the iOS SDK?
There are a lot of refinements we'd like to add (#109 for example), but we are sadly locked out of implementing them due to the SDK being closed-source.

We could achieve some of what we want with method swizzling, but would obviously prefer to work with the source :)

**Comment by jnic** [comment]
Intercom indicated [in this Tweet](https://twitter.com/intercom/status/661187025685643264) that they were keen, and I note that the Go, Ruby, Java, PHP and JS bindings are all already open-source.

Is there any timeline on open-sourcing the iOS SDK? It would be hugely appreciated, and would let developers extend functionality relevant to us without having to write a client from scratch (or worse, investigate competing options).

**Comment by roland9** [comment]
+1

**Comment by jtreanor** [comment]
Thanks @tals @jnic @roland9 for bringing this up.

As @jnic pointed out, this is certainly something we are keen to do in the future. There are a number of things blocking us from open sourcing straight away so it won't be in the very near term but we are definitely exploring it.

Specifically regarding #109, its something that I hope we can address in the shorter term.

Sorry I don't have any more specifics to share and thanks for your feedback :smile:
