### ISSUE TITLE
Crash in v2.3.12

### ISSUE THREAD

**Issue by newyorkpizza** [intercom/intercom-ios#113]
Hi, we encountered this crash in the Intercom SDK, v2.3.12.  Is this a repro of https://github.com/square/SocketRocket/issues/156?  

	EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000013e686d8
	Thread : Crashed: io.intercom.PodIntercom_SRWebSocket.NetworkThread
	0  libobjc.A.dylib                0x198508644 objc_initWeak + 156
	1  newyorkpizza                   0x1003ff6e8 -[PodIntercom_SRWebSocket stream:handleEvent:] + 4299142888
	2  CoreFoundation                 0x183981c64 _signalEventSync + 192
	3  CoreFoundation                 0x18398dfd4 _cfstream_solo_signalEventSync + 240
	4  CoreFoundation                 0x18398177c _CFStreamSignalEvent + 468
	5  CFNetwork                      0x183108938 SocketStream::dispatchSignalFromSocketCallbackUnlocked(SocketStreamSignalHolder*) + 64
	6  CFNetwork                      0x1831084bc SocketStream::socketCallback(__CFSocket*, unsigned long, __CFData const*, void const*) + 268
	7  CFNetwork                      0x18310836c SocketStream::_SocketCallBack_stream(__CFSocket*, unsigned long, __CFData const*, void const*, void*) + 88
	8  CoreFoundation                 0x1839e8a20 __CFSocketPerformV0 + 624
	9  CoreFoundation                 0x1839e4544 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
	10 CoreFoundation                 0x1839e3fd8 __CFRunLoopDoSources0 + 540
	11 CoreFoundation                 0x1839e1cd8 __CFRunLoopRun + 724
	12 CoreFoundation                 0x183910ca0 CFRunLoopRunSpecific + 384
	13 Foundation                     0x1848892bc -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 308
	14 newyorkpizza                   0x100400988 -[PodIntercom__SRRunLoopThread main] + 4299147656
	15 Foundation                     0x18496fc80 __NSThread__start__ + 1000
	16 libsystem_pthread.dylib        0x198f23b28 _pthread_body + 156
	17 libsystem_pthread.dylib        0x198f23a8c _pthread_body + 154
	18 libsystem_pthread.dylib        0x198f21028 thread_start + 4

**Comment by jtreanor** [comment]
Hi @newyorkpizza,

Yes this is a reproduction of the issue you have linked. This is fixed in 2.3.13 and later.

**Comment by newyorkpizza** [comment]
Cool, thanks!
