### ISSUE TITLE
presentMessageComposer shows conversations view?

### ISSUE THREAD

**Issue by kermankohli** [intercom/intercom-ios#114]
Hey,

When I call Intercom.presentMessageComposer() I get the "View conversations" view instead of the message composer. The SDK is connected properly as it reports the last seen on the website correctly. Any ideas?

Cheers,
Kerman

**Comment by jtreanor** [comment]
Hi @kermankohli,

Currently, only the Support product allows inbound messaging. This happens if your app doesn't include it. Let me know if I can help in any way.

**Comment by kermankohli** [comment]
Hey James, didn't quite get you? I've got Support+Learn+Feeback Pro...

**Comment by jtreanor** [comment]
In that case you should be able to open the composer.

Would you mind contacting us through Intercom so that we can get this resolved for you?

James
