### ISSUE TITLE
Export current Intercom's version

### ISSUE THREAD

**Issue by talkain** [intercom/intercom-ios#115]
Hey,

We are using Intercom using the Intercom's [React Native](https://facebook.github.io/react-native/) wrapper called [react-native-intercom](https://www.npmjs.com/package/react-native-intercom).

The problem is that this project was built based on Intercom prior to v2.1 (which changed the way Intercom enables push notifications). In order to support both versions it would be nice to have the current Intercom's version as a constant in the code.

Thanks in advance!

**Comment by jtreanor** [comment]
Hi @talkain 

Although react-native-intercom is not made officially by us at Intercom, it should still work correctly with recent versions.

I'm not entirely clear on what you are asking. The most recent version should work with the React Native wrapper.

**Comment by jtreanor** [comment]
Oh, I see the issue in https://github.com/asamiller/react-native-intercom/issues/5. Version 2.3.4 or earlier should work with the wrapper because 2.3.5 removed the deprecated method.

I would be happy to help you in updating the React Native wrapper. It is based on our official Cordova plugin which replaced this functionality by adding `AppDelegate+IntercomPush.h/m` here: https://github.com/intercom/intercom-cordova/tree/master/src/ios

A similar approach would work for React Native.

**Comment by talkain** [comment]
Hi @jtreanor 
Thank you for the quick reply :-)

I would like to enable the use of both the old version and the new version (registerForRemoteNotifications and setDevice). Exporting the current version (defines/constants) will help differentiate between them.

I created [a patch](https://github.com/talkain/react-native-intercom/commit/2df8b9a4c29e78e51198a8bfeceab7a5c1f699dc) that removes the call to registerForRemoteNotifications, but I still like to support older versions.

What do you think?

Thanks!

**Comment by jtreanor** [comment]
One way you could do this check is as follows:

```
if ([Intercom respondsToSelector:@selector(registerForRemoteNotifications)]) {
    [Intercom performSelector:@selector(registerForRemoteNotifications)];
}
```

Although I would suggest not supporting older versions since `registerForRemoteNotifications` had some issues as described in #88.

**Comment by talkain** [comment]
@jtreanor I would take your advice.. let's see if the owner wants to keep this backward compatibility or not, and if so, I will use the selector-way.

Thank you :)

**Comment by jtreanor** [comment]
No problem @talkain :smile:
