### ISSUE TITLE
Links in in-apps don't work on press, only when long pressing them

### ISSUE THREAD

**Issue by mderazon** [intercom/intercom-ios#117]
Tested on iPhone 5s, iOS 9.2 and Intercom 2.3.18

When sending an in-app message with links, the links are not clickable. Only when long pressing the links it works.

Can you please confirm this ?
I can send you a link to the message I used to test it, just not comfortable sending it here in the open.

Please let me know of a direct way to contact you regarding this.

Thanks,
M

![output](https://cloud.githubusercontent.com/assets/717076/12536327/68602f5e-c2aa-11e5-82b7-8add8b7548be.gif)

**Comment by jtreanor** [comment]
Hi @mderazon,

Thanks for reporting this. I am investigating this now.

You can always contact us directly through the messenger on [intercom.io](https://intercom.io) or by emailing team@intercom.io

**Comment by jtreanor** [comment]
I haven't been able to reproduce this locally so far. It good be great if you could write in directly with details on your setup.

**Comment by mderazon** [comment]
@jtreanor sent your support team the link to the in app message

**Comment by jtreanor** [comment]
Thanks @mderazon,

I'll follow up there.

**Comment by mderazon** [comment]
@jtreanor Some of our customers have complained that the links are not clickable, and I also saw it immediately. But after couple of tries, I see that the link opens 20% of the times, depending on the way I click on the screen.

It seems that the tap region is very small

On simulator is never recognizes the tap. on a real device, it's something like 80% miss rate. I guess you have to know how to tap it correctly to improve the chance.

This is not related to our app specifically, and was reproduced in the sample app as well.

What UI component are you using for the link?

**Comment by jtreanor** [comment]
@mderazon Thanks for the detail. This is very interesting. The link is just an `NSAttributedString` with `NSLinkAttributeName` in a `UITextView` so there is nothing custom about it.

I will dig some more to see what I can find.

**Comment by jtreanor** [comment]
Quick update: I have reproduce the issue and I'm working on tracking down the cause.

**Comment by jtreanor** [comment]
@mderazon So the issue here is actually with iOS itself.
`UITextView` requires a minimum tap duration in order for links to open.

**Comment by mderazon** [comment]
@jtreanor has this always been the case ? Can you point somewhere that documents this? an open issue somewhere?

**Comment by jtreanor** [comment]
@mderazon Yes, it has been the case since at least iOS 7. I haven't found a radar for it but these links all refer to the delay:
- https://stackoverflow.com/questions/22379595/uitextview-link-tap-recognition-is-delayed
- https://www.hackingwithswift.com/example-code/system/how-to-make-tappable-links-in-nsattributedstring
- https://gist.github.com/benjaminbojko/c92ac19fe4db3302bd28

**Comment by jtreanor** [comment]
@mderazon I have added a workaround for this issue in [2.3.19](https://github.com/intercom/intercom-ios/releases/tag/2.3.19) which is now released on CocoaPods. Thanks for reporting it :smile:

**Comment by mderazon** [comment]
Just tested it and it looks like it solved.
Thanks :+1:

**Comment by leviathan** [comment]
Have you tried to disable content touch delays?
```
textView.delaysContentTouches = false
```

Apple docs: https://developer.apple.com/documentation/uikit/uiscrollview/1619398-delayscontenttouches

`UITextView` is a scroll view and it tries to delay tap events in order to determine the scrolling direction. However, if you want to detect a tap on a weblink, then disabling this helps.
