### ISSUE TITLE
Crash when using 3d touch on image picker.

### ISSUE THREAD

**Issue by nazeehshoura** [intercom/intercom-ios#118]
Log:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSObject previewingContext:viewControllerForLocation:]: unrecognized selector sent to class 0x19f518020'
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jtreanor** [comment]
Hi @nazeehshoura,

Thanks for reporting this.
Unfortunately, this is an iOS issue. There is a radar for it here: http://www.openradar.me/22981190
