### ISSUE TITLE
Validation Failing

### ISSUE THREAD

**Issue by aacorn** [intercom/intercom-ios#121]
Hi Guys,

Loving Intercom but hit a wall with our iOS integration, hoping someone can please help?
Able to successfully set-up with Push Notification and works a treat with our adhoc testing using a production certificate to test Apple Push Notifications, however now that we want to submit to the store using Xcodes Validation we get a very odd mix of issues.

1. If we have 'include app symbols' option checked then validation fails immediately, complaining the .ipa doesn't exist. 

Not experienced this before introducing Intercom framework and everything I'm reading suggests bitcode may be the culprit? Problem is we have set Bitcode to NO so maybe this is a red herring - unless the Target bitcode setting doesn't disable for frameworks?

2. As a work around if we uncheck 'include symbols' when trying to Validate the app then Validation takes FOREVER until finally timing out and giving a message to say Verification failed. "iTunes Store Operation Failed". No other info 

Latest Intercom Bundle and framework manually installed (no pods)
Xcode 7.2.1
Bitcode disabled in settings

One question.. On the initial summary screen prior to validating the app xcode shows app components with entitlements. The .ipa has entitlements and a dist prov profile. However also shown is a binary for 'Intercom' with no entitlements and no provisioning profile. Is that correct?

Going slightly crazy on this one. Thanks for any insights!!

**Comment by jtreanor** [comment]
Hi @aacorn,

Thanks for the detailed report. Each scenario you describe should work fine with Intercom. Intercom has had Bitcode support since 2.3.8.

We have found submitting/validating apps through Xcode to be very unreliable recently (both with and without Intercom). I would suggest using the Application Loader to upload your ipa instead (some details are [here](https://itunesconnect.apple.com/docs/UsingApplicationLoader.pdf)).

James

**Comment by aacorn** [comment]
Heya James,

Appreciate the feedback! I followed your advice and went the Application Loader route. It failed but gave some hopefully more useful clues as to why...

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'aacorn.app/Intercom.bundle/Intercom.framework/Versions/A/Intercom' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

Thanks again!

**Comment by aacorn** [comment]
Aha! The sites intructions directed to copy the intercom framework into the project dir and to do the same with intercom.bundle. However the bundle also contained the framework and xcode doesn't like having the framework in the app bundle. Anyway deleted the dupe framework and all seems to be right with the world. Thanks again for your help!
