### ISSUE TITLE
disallow registration of Apple's Test Flight users

### ISSUE THREAD

**Issue by ded** [intercom/intercom-ios#122]
Hi there,
Is there a way to prevent Apple from registering users into my app? Every time I submit a new build to TestFlight (for beta app preview), a fake user is created on their behalf, and thus — over time, clogs up our user list...

You can see here in the Intercom app demonstrating this in action (I purposefully blurred out the names of real people)

![image](https://cloud.githubusercontent.com/assets/372683/13065333/2db65776-d410-11e5-9a5c-3d55d003bd9e.png)

**Comment by jtreanor** [comment]
Hi @ded,

Unfortunately there is no way to identify which users are Apple reviewing your app. Of course you could delete these users after the review has completed.
