### ISSUE TITLE
Crash when send message

### ISSUE THREAD

**Issue by douglasd3** [intercom/intercom-ios#123]
I'm getting the following crash when i press 'Send' after `Intercom.presentMessageComposer()` :

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM removeObjectAtIndex:]: index 1 beyond bounds for empty array'

I'm using Swift 2.1 and Xcode 7.2.1

**Comment by ronocod** [comment]
Hi @douglasd3,

Do you have a stack trace for this error? If you could also post the SDK version you're using that would be a big help :)

**Comment by douglasd3** [comment]
Hi! i just figured it out. It was conflicting with another pod (UICollectionView+ARDynamicHeightLayoutCell), removing it from my project fixed the problem. I don't really know why, didn't have the time to investigate.

**Comment by ronocod** [comment]
Hmm, it seems that pod is swizzling a lot of methods on `UICollectionView` which could cause problems: https://github.com/AugustRush/UICollectionView-ARDynamicHeightLayoutCell/blob/d2755047d5e33c5ebbc8c54a2a82074be64fa250/UICollectionView%2BARDynamicHeightLayoutCell/UICollectionView%2BARDynamicCacheHeightLayoutCell.m#L44-L55

The crash doesn't seem to be in our library so I'll close this now :+1:
