### ISSUE TITLE
Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by douglasd3** [intercom/intercom-ios#126]
Hi, i'm having the following issue when upload the app to TestFlight:

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "bonuz.com". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

I've double checked the AppID and the certificates. Any ideia of what could be causing the problem?
PS.: The Push works fine despise the message.

I'm using Intercom for iOS version 2.3.19

**Comment by jtreanor** [comment]
Thanks @douglasd3,

Have you included the `aps-environment` entitlement in your app? I don't believe this issue is Intercom related.

**Comment by DaleCantwell** [comment]
Hi @douglasd3,
I'm going to close out this issue for now as it seems it is not an issue with our iOS integration. Let us know if you are still encountering this issue and we can investigate it again.
