### ISSUE TITLE
Closing Intercom conversation screen programatically?

### ISSUE THREAD

**Issue by ShaunakP** [intercom/intercom-ios#128]
Is there a way to check if Intercom screen is active and exit from it? I have a requirement in which it should be closed automatically upon a certain event in the app if that screen is open

**Comment by ronocod** [comment]
There is no way to do this currently but we have added it in an upcoming version. I'll update this issue when that version is released :)

**Comment by ShaunakP** [comment]
That is awesome! Thanks a lot..

**Comment by ShaunakP** [comment]
Can you please confirm that the upcoming release would have a way to 1)check whether intercom is open or not AND 2) Notify when Intercom screen is opened or closed.

**Comment by ronocod** [comment]
There is currently a way to [receive notifications when the Intercom UI is opened or closed](https://github.com/intercom/ios-sdk/blob/master/IntercomSDK/Classes/Intercom.h#L333-L352), but this does apply to the chat head notification as well as the messenger window.

We do not have a way to check if the messenger is open or not, but we'll note it as a feature request for the future.

**Comment by nico75005** [comment]
Any ETA regarding the new version? Because I might say it's really annoying when the app is in background and the user gets a notification bringing him in a specific area of the app but Intercom is still on top as the user was using it before the app went in background...
