### ISSUE TITLE
is there any swift document available?

### ISSUE THREAD

**Issue by iceman201** [intercom/intercom-ios#129]
## Version info
  - Intercom for iOS version: 9.3
  - iOS version: Swift 2.0

## Expected behavior
I wish could get a swift documents?

## Actual behavior
only obj-c documents

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs

**Comment by DaleCantwell** [comment]
Hi @iceman201 Thanks for contacting us. We don't currently have any swift documentation available. It is on our task list and we hope to add it in one of our upcoming releases.
Even though we currently don't have a set of documentation for Swift our iOS integration is fully compatible with Swift. Please contact us if you run into any specific issues while trying to integrate with your app.

**Comment by basememara** [comment]
Can you please leave this issue open until Swift documentation or at least a sample Swift project is included?

**Comment by skylerwshaw** [comment]
Hey @basememara, feel free to message us through the Intercom in-app messenger at [Intercom.io](intercom.io) or email team@intercom.io if you have any questions about implementing the Intercom iOS SDK for Swift. All of the same method calls are available between Objective-C and Swift. Here are some examples demonstrating the intuitive relationship between the two:

| Objective-C                                                               | Swift                                                          |
|---------------------------------------------------------------------------|----------------------------------------------------------------|
| [Intercom setApiKey:@"<#your_ios_api_key#>" forAppId:@"<#your_app_id#>"]; | Intercom.setApiKey("your_ios_api_key", forAppId: "your_app_id) |
| [Intercom registerUserWithUserId:@"<#123456#>"];                          | Intercom.registerUserWithUserId("123456")                      |
| [Intercom reset];                                                         | Intercom.reset                                                 |
| [Intercom presentMessageComposer];                                        | Intercom.presentMessageComposer                                |

Stay tuned, we will be adding documentation.

**Comment by felixdkatt** [comment]
Which method do we use to see what URL was used for the push notification?

**Comment by jtreanor** [comment]
As of [3.0.0](https://github.com/intercom/intercom-ios/releases/tag/3.0.0), the repo includes a Swift sample app and the following pages of our documentation provide Swift code: https://docs.intercom.io/install-on-your-product-or-site/quick-install/install-intercom-on-your-ios-app & https://docs.intercom.io/configure-intercom-for-your-product-or-site/configure-intercom-for-mobile/configuring-intercom-for-ios

**Comment by TheBachelor** [comment]
@DaleCantwell @jtreanor thanks for the documentation, but some of it isn't accurate. For example, ICMUserAttributes don't exist and now that updateUserWithAttributes is deprecated, how can we update user attributes in Swift 2.3?

**Comment by jtreanor** [comment]
Hi @TheBachelor,

The examples given in our docs is for Swift 3. It should be possible to also use it with Swift 2.3.
In the short term you can continue to use the deprecated `updateUserWithAttributes`, but it will be removed in a future release.

**Comment by TheBachelor** [comment]
Thanks for the response @jtreanor. It's not working. I'm sending info, but it's not reflecting on the dashboard. I think it may be already deprecated. How can I get the ICMUserAttribute object?

**Comment by TheBachelor** [comment]
The docs say do this:

let userAttributes = ICMUserAttributes()
userAttributes.name = "Bob"
userAttributes.email = "bob@example.com"
Intercom.updateUser(userAttributes)

but ICMUserAttributes() is undefined. So instead, i'm doing this

let userAttributes = [
"name" : User.SharedInstance.fullName,
"email" : User.SharedInstance.email,
"permission" : User.SharedInstance.permissions,
"token" : User.SharedInstance.firebaseToken,
"companies" : [
"name" : User.SharedInstance.companyName,
"companyId" : User.SharedInstance.companyId,
"plan" : subType,
"server" : server]
]

Intercom.updateUserWithAttributes(userAttributes as [NSObject : AnyObject])

This is what isn't working.

**Comment by jtreanor** [comment]
@TheBachelor I just ran this code successfully in a Swift 2.3 app:
```
let userAttributes = ICMUserAttributes()
userAttributes.name = "Bob"
userAttributes.email = "bob@example.com"
Intercom.updateUser(userAttributes)
``` 

`ICMUserAttributes` should be available as long as you have imported Intercom with `import Intercom`.

What version of Intercom are you using and how did you install it?

**Comment by TheBachelor** [comment]
That's strange. I just run pod 'Intercom'

**Comment by TheBachelor** [comment]
Intercom for iOS - Version 3.0.22 @jtreanor

**Comment by jtreanor** [comment]
@TheBachelor The latest version is 3.1.1. If you update to that with `pod update` `ICMUserAttributes` will be available 🎉

**Comment by TheBachelor** [comment]
That force updated all my libraries to Swift 3. I'm still converting the rest of the project. On the plus side, I have ICMUserAttributes and ICMComany as promised

**Comment by jtreanor** [comment]
Intercom does not require Swift 3.0, but perhaps another pod does. `pod update Intercom` would update Intercom only.

**Comment by TheBachelor** [comment]
I just run pod update. Managed to convert the whole project & set-up Intercom perfectly, thanks a lot @jtreanor
