### ISSUE TITLE
Restricted access to photos does not allow to quit

### ISSUE THREAD

**Issue by philipengberg** [intercom/intercom-ios#130]
## Version info
  - Intercom for iOS version: `2.3.19`
  - iOS version: `9.3.1`

## Expected behavior
Tapping the cancel button ("Annuller") would close the window

![img_0484](https://cloud.githubusercontent.com/assets/1840093/14532464/7c7ae96a-0261-11e6-8b15-947279b4835c.jpg)

## Actual behavior
The window cannot be closed

## Steps to reproduce
 1. Restrict access to photos
 2. Present message composer
 3. Tap image picker button next to text field
 4. The above view is presented, which **cannot** be exited

## Logs

**Comment by jtreanor** [comment]
Hi @philipengberg,

Thanks for sending this in. I have tried this out and I cannot immediately reproduce it locally. Does this happen only on certain iOS versions? Can you close the view controller if you allow access?

**Comment by philipengberg** [comment]
Yes, it works just fine, when granted access. 
Well, we have identified it on various versions of iOS 9 and consistently across different devices.

**Comment by jtreanor** [comment]
Thanks @phillipsngberg,

Are you using the latest version of Intercom (2.3.19)?

**Comment by philipengberg** [comment]
Yes :+1:

**Comment by philipengberg** [comment]
What is the status on this @jtreanor?

**Comment by jtreanor** [comment]
This is fixed in version [3.0.0](https://github.com/intercom/intercom-ios/releases/tag/3.0.0).
