### ISSUE TITLE
registerUnidentifiedUser() does not dismiss dialog messages

### ISSUE THREAD

**Issue by foobar8675** [intercom/intercom-ios#131]
For feature requests please contact us at team@intercom.io

registerUnidentifiedUser() does not dismiss dialog messages

## Version info
  - pod 'Intercom', '~> 2.3.19'
  - ios 9.3

## Expected behavior

the bubble should dismiss

## Steps to reproduce
 1. send your signed in user a message over intercom saying hello
 2. via the api, call Intercom.registerUnidentifiedUser()
 3. see the chat bubble persists. if you send an additional message , the additional message also shows.

## Logs

**Comment by jtreanor** [comment]
Hi @foobar8675,

I don't quite understand the issue you are seeing here. Why would you expect `registerUnidentifiedUser` to hide UI?

**Comment by foobar8675** [comment]
Hi @jtreanor maybe I'm the one misunderstanding . to set some context, we're using intercom to message our users. here are some steps to outline what we are doing

1. matt logs into the app 
2. app registers user via intercom
3. user shows on intercom.com 
![screen1](https://cloud.githubusercontent.com/assets/1685700/14720676/7f96a8cc-07b7-11e6-8dd6-32e782e66410.png)

4. employee clicks on matt and sends message
5. matt logs out of the app which calls `registerUnidentifiedUser`
6. matt still sees the conversation that the employee sent to matt.

perhaps I am making the wrong call, but my intent is such that when matt logs out, the conversation that the human had with matt would no longer be visible since that conversation belonged to matt.

**Comment by skylerwshaw** [comment]
Hey @foobar8675, per our [documentation here on the repo](https://github.com/intercom/intercom-ios#my-app-has-logged-in-and-logged-out-users) and here in our [Intercom documentation](https://docs.intercom.io/install-on-your-product-or-site/install-intercom-on-your-ios-app#my-app-has-both-logged-in-and-logged-out-users), the correct method to log a user out of Intercom is `[Intercom reset];`:
![image](https://cloud.githubusercontent.com/assets/5881537/14736190/baff4234-0875-11e6-95d5-3e18db89d7ba.png)

After this point, the SDK will be ready to register another identified or unidentified user.

Feel free to message us using the in-app messenger within your Intercom dashboard if you have any more questions about the installation or configuration of Intercom, including the mobile SDKs. 👍

**Comment by foobar8675** [comment]
got it. thank you @skylerwshaw
