### ISSUE TITLE
Image picker opens camera roll, doesn't allow picking from album

### ISSUE THREAD

**Issue by thomassnielsen** [intercom/intercom-ios#133]
## Version info
  - Intercom for iOS version: 2.3.19
  - iOS version: 9.3.1

## Expected behavior

I should be able to pick any image from my device

## Actual behavior

I can only pick images from my camera roll

## Steps to reproduce
 1. Open a new Intercom conversation
 2. Tap the photo icon
 3. Image picker opens, locked to camera roll

## Steps to fix
Use `UIImagePickerControllerSourceTypePhotoLibrary` instead of `UIImagePickerControllerSourceTypeSavedPhotosAlbum` when presenting the UIImagePickerController

## Note
I understand that there may be a reason for this being as it is, but I've got complaints about this from our users, so I wanted to notify you.

**Comment by bboyle18** [comment]
Hi @thomassnielsen 
Sorry for the delay in responding.
Thanks for highlighting this. We'll be fixing this in the next release later today.

Cheers

Brian

**Comment by jtreanor** [comment]
This is now fixed in [3.0.3](https://github.com/intercom/intercom-ios/releases/tag/3.0.3).
