### ISSUE TITLE
Automatic language detection

### ISSUE THREAD

**Issue by esvp** [intercom/intercom-ios#137]
## Version info
  - 2.3.21
  - Any

## Expected behavior

The SDK should fetch the current language of the user to be available for targeting in Intercom Dashboard.

## Actual behavior

This only happens in the browser version. Now we have to add it as a custom parameter and wait for our users to update our app.

**Comment by jtreanor** [comment]
Thanks for the feedback @esvp.

This would very much be a consideration of https://github.com/intercom/intercom-ios/issues/100.

I am closing this issue as a feature request. Let me know if you have any questions.
