### ISSUE TITLE
[Intercom] ERROR - Could not find the application's delegate. Push notifications may not work correctly.

### ISSUE THREAD

**Issue by Liron-K** [intercom/intercom-ios#139]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 2.3.21
  - iOS version: 9.3.1

## Expected behavior
Receive Push Notifications

## Actual behavior
Get the error mentioned in the title (before I even setup Intercom) and don't receive any push notifications. 
I confirmed that I do call 
```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [Intercom setDeviceToken:deviceToken];
}
```

## Logs
[Intercom] ERROR - Could not find the application's delegate. Push notifications may not work correctly.

**Comment by jtreanor** [comment]
Hi @Liron-K,

This error occurs when `[UIApplication sharedApplication].delegate` is `nil`. Can you think of any reason why this may be the case?

**Comment by Liron-K** [comment]
Nope. I even checked that and it's not null.
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  // Override point for customization after application launch.
  
  if(application.delegate)
  {
    NSLog(@"appDelegate: %@", [application.delegate class]);
  }
```
I get that exception before that if statement even gets called.

My guess is whatever code is checking for that is getting called before the app actually gets created and setup properly.

This is my main.m file.
```
#import <UIKit/UIKit.h>
#import "AppDelegate.h"

int main(int argc, char * argv[]) {
  @autoreleasepool {
      return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
  }
}
```

Here is the log:
> 2016-06-07 20:26:18.467 NCSYAttendance[3369:1569655] [Intercom] ERROR - Could not find the application's delegate. Push notifications may not work correctly.
> 2016-06-07 20:26:23.022 NCSYAttendance[3369:1569655] appDelegate: AppDelegate

**Comment by jtreanor** [comment]
Thanks for sending on this detail @Liron-K.

Can you confirm the header of your `AppDelegate` looks as follows?

```
@interface AppDelegate : UIResponder <UIApplicationDelegate>
...
@end
```

In particular I am wondering about the `<UIApplicationDelegate>` component. 

Your theory about it checking for the app delegate too early is a good one, but Intercom is designed to be smart enough to avoid this situation by saving the app delegate from when the device token was set.

Roughly speaking, this is the code that determines the application delegate:

```
+ (Class)applicationDelegateClass {
    Class applicationDelegateClass = [[UIApplication sharedApplication].delegate class];
    if (applicationDelegateClass) {
        NSString *className = NSStringFromClass(applicationDelegateClass);
        /* Save className for use on next launch if needed */
    } else {
        applicationDelegateClass = NSClassFromString(/* Use class name from last launch */);
        if (!class_conformsToProtocol(applicationDelegateClass, @protocol(UIApplicationDelegate))) {
            return nil;
        }
    }
    return applicationDelegateClass;
}
```

**Comment by Liron-K** [comment]
```
#import <UIKit/UIKit.h>
#import <CoreData/CoreData.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate>

@property (strong, nonatomic) UIWindow *window;

@property (readonly, strong, nonatomic) NSManagedObjectContext *managedObjectContext;
@property (readonly, strong, nonatomic) NSManagedObjectModel *managedObjectModel;
@property (readonly, strong, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator;

- (void)saveContext;
- (NSURL *)applicationDocumentsDirectory;

@end
```

I uninstalled the app from the phone and re-installed and now I'm not seeing that error in the console. I sent a test push and I didn't receive it though, so I'm not sure if that's related or not.

**Comment by Liron-K** [comment]
Actually take that back - I got it again.

**Comment by Liron-K** [comment]
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  // Override point for customization after application launch.
  
  if(application.delegate)
  {
    NSLog(@"[application.delegate class] %@", [application.delegate class]);
    
    Class applicationDelegateClass = [[UIApplication sharedApplication].delegate class];
    NSString *className = NSStringFromClass(applicationDelegateClass);
    NSLog(@"applicationDelegateClass: %@", className);
    
    Class applicationDelegateClassResolved = NSClassFromString(className);
    NSLog(@"applicationDelegateClassResolved: %@", applicationDelegateClassResolved);
    
    if (!class_conformsToProtocol([application.delegate class], @protocol(UIApplicationDelegate))) {
      NSLog(@"[application.delegate class] Doesn't Conform");
    }
    if (!class_conformsToProtocol(applicationDelegateClass, @protocol(UIApplicationDelegate))) {
      NSLog(@"applicationDelegateClass Doesn't Conform");
    }
    if (!class_conformsToProtocol(applicationDelegateClassResolved, @protocol(UIApplicationDelegate))) {
      NSLog(@"applicationDelegateClassResolved Doesn't Conform");
    }
  }
```

> 2016-06-07 22:23:49.117 AppName[3468:1599243] [Intercom] ERROR - Could not find the application's delegate. Push notifications may not work correctly.
> 2016-06-07 22:23:49.247 AppName[3468:1599243] [application.delegate class] AppDelegate
> 2016-06-07 22:23:49.247 AppName[3468:1599243] applicationDelegateClass: AppDelegate
> 2016-06-07 22:23:49.247 AppName[3468:1599243] applicationDelegateClassResolved: AppDelegate

Note that none of the "Does Not Confirm" get printed here. Maybe you are somehow calling NSClassFromString before the class gets loaded? I would expect these methods to only get called after I call setup on the Intercom SDK.

**Comment by Liron-K** [comment]
@jtreanor Any news on this?

**Comment by jtreanor** [comment]
@Liron-K Thanks for sending on the detail on this.

There may be something else going on here. Can you put a breakpoint on the line in `application:didRegisterForRemoteNotificationsWithDeviceToken:` to make sure that it is getting called?

The error you are seeing here should not cause you to not receive push. Are you testing push on an Adhoc (production) build?

**Comment by Liron-K** [comment]
I am getting a callback on `didRegisterForRemoteNotificationsWithDeviceToken` but not `didReceiveRemoteNotification`.

This app is an enterprise app and I'm testing in the debugger using the team provisioning profile. I guess I might not be receiving the pushes because I'm not using a development push certificate in intercom. Is there a way to test this in the debugger or do I have to be using the production build for push to work?

**Comment by jtreanor** [comment]
Unfortunately you will need to be using a production build in order to receive push.

Let me know how you get on with that.

**Comment by Liron-K** [comment]
Ok - so I get the following:

> Jun  9 13:20:16 Lirons-iPhone-6 AppName[4598] <Warning>: Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.

This is my receive block. Indeed I don't call the completion handler - but I also don't see 'didReceiveRemoteNotification' in the logs. I'll try and see if adding that fixes the problem.
```
-(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  NSLog(@"didReceiveRemoteNotification");
}
```

**Comment by jtreanor** [comment]
It is expected that `didReceiveRemoteNotification` won't get called, since Intercom handles this internally. What version are you using? The latest is 2.3.21.

**Comment by jtreanor** [comment]
Ah, I see from your original message that you are using 2.3.21. When you open the push notification, does it open the Intercom messenger?

**Comment by Liron-K** [comment]
What do you mean open the push? I don't seem to be receiving the push on the device. I see regular app messages, but not pushes.

**Comment by Liron-K** [comment]
OK - got it to work :). I still see the error message I originally reported but it doesn't seem to be preventing push notifications from appearing.

**Comment by jtreanor** [comment]
@Liron-K I mean when you open the app via the push notification, does the Intercom window show?

I'm glad that much is working for you :) I'm sure we'll be able to figure out the last bit.

**Comment by Liron-K** [comment]
Yes when I open the app via the push, the intercom window does show. Thanks.

**Comment by jtreanor** [comment]
Great, that sounds like everything is working correctly 😄 

Are you happy for me to close this issue?

**Comment by Liron-K** [comment]
Up to you if you want to still investigate the error message I initially reported :).

**Comment by jtreanor** [comment]
I will keep an eye on it and update if I learn anything more.

Thanks @Liron-K 😄
