### ISSUE TITLE
v3 does not allow taking a photo, only uploading

### ISSUE THREAD

**Issue by billinghamj** [intercom/intercom-ios#140]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.0-beta2
  - iOS version: 9.3.2

## Expected behavior

When tapping the image button in a conversation, the user should be able to choose to either take a new photo, or to upload an existing photo.

## Actual behavior

Only uploading an existing photo is possible.

## Steps to reproduce
 1. open an Intercom conversation
 2. tap the image button

**Comment by jtreanor** [comment]
Hi @billinghamj,

Thanks for sending this in. Given that this is a feature request rather than an issue, it would be great if you could send details of the functionality you would like to team@intercom.io, along with examples of why this would be useful for your users.

James
