### ISSUE TITLE
[ICMMetric saveMetrics:] crash

### ISSUE THREAD

**Issue by deli33** [intercom/intercom-ios#141]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 2.3.21
  - iOS version: 9.3.2

## Expected behavior
It does not have a user history

## Actual behavior
It does not have a user history

## Steps to reproduce
It is inaccurate.
When you stay in a long time background

## Logs

Crashed: com.apple.root.background-qos
EXC_BREAKPOINT 0x0000000180c396a8

Crashed: com.apple.root.background-qos
0  CoreFoundation                 0x180c396a8 __CFBasicHashRehash + 2512
1  Foundation                     0x18155237c -[NSKeyedArchiver _initWithOutput:] + 368
2  Foundation                     0x1815af76c +[NSKeyedArchiver archiveRootObject:toFile:] + 200
3  Sunshine                       0x10090e9e4 +[ICMMetric saveMetrics:] + 4304988644
4  libdispatch.dylib              0x1806514bc _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x18065147c _dispatch_client_callout + 16
6  libdispatch.dylib              0x18065f914 _dispatch_root_queue_drain + 2140
7  libdispatch.dylib              0x18065f0b0 _dispatch_worker_thread3 + 112
8  libsystem_pthread.dylib        0x180869470 _pthread_wqthread + 1092
9  libsystem_pthread.dylib        0x180869020 start_wqthread + 4

**Comment by jtreanor** [comment]
Hi @deli33,

Could you give more info about the issue you are seeing? Under what circumstances does this crash occur?

**Comment by jtreanor** [comment]
I am closing this issue due to a lack of further information and the substantial changes make in [3.0.0](https://github.com/intercom/intercom-ios/releases/tag/3.0.0).

Feel free to reopen if you see this crash again.
