### ISSUE TITLE
Update documentation URL

### ISSUE THREAD

**Issue by jrmsklar** [intercom/intercom-ios#142]
## Version info
  - Intercom for iOS version: 2.3.21
  - iOS version: N/A

Various documentation URLs refer to an outdated URL scheme. Some examples are as follows:

- https://doc.intercom.io/api/#user-model
- https://doc.intercom.io/api/#companies-and--users
- http://doc.intercom.io/api/#events

It looks like the newer URL scheme is `https://developers.intercom.com/reference/#<resource>`.

Thanks!

**Comment by bboyle18** [comment]
Hi @jrmsklar 
Thanks for highlighting this. 👍 
We are currently updating our docs so we'll fix those links soon.

The ones you referenced are all available here:
https://developers.intercom.io/reference/#user-model
https://developers.intercom.io/reference/#companies-and--users
https://developers.intercom.io/reference/#events

Cheers

Brian

**Comment by jrmsklar** [comment]
@bboyle18 thanks for those 👍. I was able to find the correct pages, just wanted to let you know of the older links hanging around 😃.

**Comment by bboyle18** [comment]
@jrmsklar Have you got a link to the specific pages where the dead links were?

**Comment by jrmsklar** [comment]
It's in the main `Intercom.h` header file in the framework.

**Comment by bboyle18** [comment]
Thanks @jrmsklar 
This will be updated in our next release.
