### ISSUE TITLE
logEventWithName metadata as an ordered object

### ISSUE THREAD

**Issue by jasongaare** [intercom/intercom-ios#143]
## Version info
  - Intercom for iOS version: 2.3.10
  - iOS version: 9.3

## Desired behavior

Right now, the Intercom library passes metadata with a logged event as an NSDictionary, which does not have order. It would be beneficial if we could pass an ordered set or array to the metadata so that it comes out in a controlled order.

## Actual behavior

In our use case, we typically send 5 to 10 data pieces in our metadata and they do not appear in any sort of order when presented on the Activity Feed on the web application. The information is correctly displaying, but some items passed are for reference only, and others are the pertinent information to our team, so finding away to order them would be preferable.

Does anyone have a clever solution to this? Or would this be better classified as a feature request?

**Comment by jtreanor** [comment]
Hi @jasongaare,

Thanks for the request. Unfortunately this request involves a fundamental change to how metadata on Intercom events work. I certainly understand your use case but it will not be a change we will be making in the near future.

Feel free to contact Intercom directly through [intercom.io](https://intercom.io) or at team@intercom.io to discuss your needs more.
