### ISSUE TITLE
Not able to upload to Appstore: BundleIdentifier contains disallowed chars

### ISSUE THREAD

**Issue by phips28** [intercom/intercom-ios#146]
I cant upload our app to the Appstore. Error:
<img width="582" alt="screenshot 2016-07-22 13 23 24" src="https://cloud.githubusercontent.com/assets/3694800/17070406/98a0c63a-5010-11e6-98dd-752ecc6b753f.png">

## Version info
  - Intercom for iOS version: 3.0.1
  - iOS version: -

## Expected behavior
upload without error

## Actual behavior
upload has error

## Steps to reproduce
 1. Install Intercom via pods
 2. Archive the project with xcode
 3. Submit it to Appstore via Organizer

## Logs
There is a point at the end of the BundleIdentifier:
<img width="597" alt="screenshot 2016-07-22 13 45 48" src="https://cloud.githubusercontent.com/assets/3694800/17070766/acbec494-5012-11e6-8967-4f1a0c2b945b.png">
I removed it and was able to upload the app.

**Comment by jtreanor** [comment]
Hi @phips28,

Thanks for reporting. I'm fixing this now. In the meantime version 3.0.0 does not have this issue.

**Comment by jtreanor** [comment]
3.0.2 which fixes this issue is now released.

Thanks again for reporting this @phips28.
