### ISSUE TITLE
Receiving message: Could not find the application's delegate. Push notifications may not work correctly.

### ISSUE THREAD

**Issue by zackola** [intercom/intercom-ios#147]
## Version info
  - Intercom for iOS version: 2.3.21
  - iOS version: 9.3.2

## Expected behavior
Intercom does not load until after app delegate exists, push notifications work

## Actual behavior
Intercom NSLogs "Could not find the application's delegate. Push notifications may not work correctly." It is the first thing that my app logs, before the AppDelegate is loaded. Push notifications are not working.

## Steps to reproduce
 0. Add `pod "Intercom"` to Podfile
 1. `pod install`
 2. Setup intercom integration as per instructions
 3. `@import Intercom;` in AppDelegate
 4. Add symbolic breakpoint for NSLog
 5. Launch app.

![image](https://cloud.githubusercontent.com/assets/19680/17071416/7703bfc2-502f-11e6-8880-aafcc6fa0c91.png)

Not sure if push notifications not working is being caused by this, but it would be nice to have this error message go away and see if it helps :)

**Comment by jtreanor** [comment]
Hi @zackola,

Thanks for reporting this.

Your theory about it checking for the app delegate too early is a good one, but Intercom is designed to be smart enough to avoid this situation by saving the app delegate from when the device token was set.

In fact, it is necessary for Intercom to exist this early in order for push to be handled correctly.

Roughly speaking, this is the code that determines the application delegate:

```
+ (Class)applicationDelegateClass {
    Class applicationDelegateClass = [[UIApplication sharedApplication].delegate class];
    if (applicationDelegateClass) {
        NSString *className = NSStringFromClass(applicationDelegateClass);
        /* Save className for use on next launch if needed */
    } else {
        applicationDelegateClass = NSClassFromString(/* Use class name from last launch */);
        if (!class_conformsToProtocol(applicationDelegateClass, @protocol(UIApplicationDelegate))) {
            return nil;
        }
    }
    return applicationDelegateClass;
}
```

When you say push notifications are not working do you mean that you are not receiving them at all, or when you open a push they don't open the Intercom UI correctly?

Are you using any other third party push providers in your app?

**Comment by zackola** [comment]
We are not receiving push notifications from Intercom at all. We are using/receiving Parse push notifications successfully. Thanks for having a look!

The really weird thing is that we have some NSLog stuff in our AppDelegate, way earlier than Intercom is set up, but this Intercom error message is the 1st line in our log output.

**Comment by paulcarpenter** [comment]
@zackola's coworker here. The method you posted looks like you are indeed saving an identifier for the app delegate’s class, but that method is only looking for the class itself. If no delegate object has been instantiated yet, (which you can see is the case from the screenshot we attached at the beginning), then knowing what the delegate’s class ​*will*​ be doesn’t solve the problem.

**Comment by jtreanor** [comment]
Thanks @zackola and @paulcarpenter,

Perhaps the log line we have is a bit misleading. Your assessment is correct, but Intercom actually only needs the class itself, so the delegate does not need to be initialised.

I'll have a look at Parse's push logic to see if they could be conflicting with us.

Have you tested push using an Adhoc (production) build?

**Comment by jtreanor** [comment]
@zackola @paulcarpenter

[3.0.3](https://github.com/intercom/intercom-ios/releases/tag/3.0.3) includes some changes that may either fix this issue for you. If not, I have updated the log to give slightly more info.

Let me know when you get a chance to try out the new version.

**Comment by zackola** [comment]
Thanks! Just checked out 3.0.3 Similar behavior with slightly different log:

```2016-07-25 15:00:46.667 Recfive[23485:6336286] [Intercom] ERROR - Could not find the application delegate's class (FIRA_R5AppDelegate-1469473077259). Push notifications may not work correctly.```

**Comment by jtreanor** [comment]
Thanks @zackola,

That is very interesting. What is the name of you App Delegate's class?
Does the class name in brackets look familiar?

**Comment by jtreanor** [comment]
One more question; is your app delegate written in Objective-C, or Swift?

**Comment by zackola** [comment]
@jtreanor We are `R5AppDelegate` - `FIRA` prefix seems to have something to do with Firebase Analyics via the  `Google/Analytics` pod. I Have no idea what -1469473077259  is.

R5AppDelegate is objective-c! Thanks again!

**Comment by jtreanor** [comment]
@zackola it seems that is our problem then. Since the app delegate class name changes between runs, Intercom can't fully set up push. I'll look a bit deeper into how Firebase does this to see if we can work around it.

Having said that, this shouldn't prevent your app from receiving push notifications. Have you tried sending push to a production (Adhoc) build?

**Comment by zackola** [comment]
Yes, We've attempted to send to production builds using the manual messages section of Intercom dashboard, but are not receiving them.

**Comment by zackola** [comment]
Hm. Ok, actually some of us are receiving them, just not me. Will investigate more on my end/throw my device in the river.

**Comment by jtreanor** [comment]
Thanks @zackola, let me know if I can help with your investigation.

**Comment by jtreanor** [comment]
@zackola [3.0.4](https://github.com/intercom/intercom-ios/releases/tag/3.0.4) is now released. This version includes must more robust app delegate checking which will be resilient to the type of things that Firebase are doing.

I'll wait until you have tried this version out before closing this issue.

**Comment by zackola** [comment]
Cool thanks! Definitely relieves the error!

**Comment by jtreanor** [comment]
That's great. Thanks @zackola. Let me know if I can help in any other way.
