### ISSUE TITLE
Message title missing

### ISSUE THREAD

**Issue by philipengberg** [intercom/intercom-ios#148]
## Version info
  - Intercom for iOS version: `3.0.2`
  - iOS version: `9.3.2`

## Expected behavior
Name should be shown above last active label.

## Actual behavior
Name is not shown.

## Steps to reproduce
![simulator screen shot 23 jul 2016 13 13 26](https://cloud.githubusercontent.com/assets/1840093/17077648/71af6ee2-50d7-11e6-9ca8-cfba9d614df3.png)

**Comment by jtreanor** [comment]
The issue here is actually that the barStyle you have set using UIAppearance is setting the style for Intercom's navigation bar.

I have reopened #145 to track this and I'm closing this as a duplicate.
