### ISSUE TITLE
HTML in welcome message not displayed in 3.x

### ISSUE THREAD

**Issue by allaire** [intercom/intercom-ios#149]
## Version info
  - Intercom for iOS version:  3.0.2
  - iOS version: Latest

## Expected behavior

We have `<br>` tags and `<a>` tags in our welcome messages, we expect that the tags get rendered correctly.

## Actual behavior

The tags (at least the `<br`) are displayed as plain text.

## Steps to reproduce
 1.  Add html to welcome messages
 2. View in latest iOS SDK
 3. Profit

## Logs

N/A

**Comment by jtreanor** [comment]
Hi @allaire,

With the [new version of our Messenger](https://www.intercom.io/in-app-messaging) you can no longer use HTML in your profile. I know this change is a bit of an adjustment. If you have any more thoughts on this, feel free to let us know at team@intercom.io.
