### ISSUE TITLE
Shell script does not compile during manual installation 

### ISSUE THREAD

**Issue by ay5000** [intercom/intercom-ios#152]
## Version info
  - Intercom for iOS version: 3.0.3 
  - iOS version: 9.3

I've followed the Intercom manual installation guide and added "bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Intercom.framework/strip-frameworks.sh" to a new Run Scripts phase.

## Expected behavior
1. Project should compile

## Actual behavior
1. Project does not compile and I get the following error:
bash: /Users/Allan/Library/Developer/Xcode/DerivedData/XXXX/Build/Products/Debug-iphoneos/XXX.app/Frameworks/Intercom.framework/strip-frameworks.sh: No such file or directory

Thanks,
Allan

**Comment by jtreanor** [comment]
Hi @ay5000 

When you added Intercom.framework to your project, did you add it the "embedded binaries" section of your target?

Are you using the latest version (3.0.3)?

**Comment by ay5000** [comment]
Hi @jtreanor,

I copied it to a subfolder in my project and then dragged it over to embedded binaries.

Yes, using latest 3.0.3.

**Comment by bboyle18** [comment]
Hi @ay5000 

This is indeed a mistake in our documentation.
To get this to compile, you need to remove the Run Script from your Build Phases and then compile your code. This will create the directory **/Users/Allan/Library/Developer/Xcode/DerivedData/XXXX/Build/Products/Debug-iphoneos/XXX.app/Frameworks/Intercom.framework**. Once this is done you can re-add the Run Script. The script should then run successfully.

Please let me know if this works for you.
Thanks for highlighting this, I'll update our documentation. 

Cheers
Brian

**Comment by jtreanor** [comment]
@ay5000 One quick question for you: what version of Xcode are you using?

**Comment by ay5000** [comment]
@jtreanor  I am using Xcode 7.3.1.

I decided to downgrade to previous version because we prefer the window overlay vs the new modal in 3.0. BTW is that configurable?

**Comment by jtreanor** [comment]
@ay5000 No, that is not something that is currently configurable. We'll take note that you would like it to be.

I am also using Xcode 7.3.1 and the install works with the instructions in the docs.

If you decide to use 3.0 again, let me know and I would be happy to help get you set up.

**Comment by afilp** [comment]
@bboyle18 Unfortunately, I have exactly the same problem in XCODE 8.3.3. 

No  'XXX.app' folder exists inside the DerivedData path.

The problem is that your solution does not apply also. Even without the script, no such folder is created there...

I cannot submit to Apple Store, what can we do now?
