### ISSUE TITLE
Cannot escape from Image picker on iPhone

### ISSUE THREAD

**Issue by AnitaPita** [intercom/intercom-ios#154]
Hi, on an iPad device the Image picker in Intercom's chat bar has a `cancel` option, but on iPhone it does not. Also, there's a bug where home-button ->  going back into the app causes the full chat bar to appear, and there's no way to get back to the main Intercom window without killing the app. I'm testing on an iPhone 6.

## Version info
  - Intercom for iOS version: 3.0.3
  - iOS version: 9.3.1

## Expected behavior
In the Image picker view, there should be a button in the top-left to cancel image selection.

## Actual behavior
Once you are in the Image picker view, the only way to continue using the app is to send an image to Intercom. Also, tapping the home screen while in Image picker and returning to the app causes the chat bar to appear and then tapping on an image does this:
<img width="399" alt="f528fe354c878482b0e9b5eda4ce58ea" src="https://cloud.githubusercontent.com/assets/9097129/17179232/6e5eec6a-53e6-11e6-8070-2f99e2091d7a.png">

This can even show up with just scrolling in the image picker view, but I've not been able to get the chat bar to appear consistently in that case. 

## Steps to reproduce bug
 1. Open the image picker
 2. Tap the home button
 3. Tap the app to open it; the chat bar+image picker should be visible and interactive.

## Logs
This is a UI bug.

**Comment by jtreanor** [comment]
@AnitaPita Thanks for taking the time to report these issues.

Regarding the cancel button being missing: are you sure that you are using the latest version (3.0.3) on both devices. If so, what iOS version are they running?

I haven't been able to reproduce the second issue but I will certainly continue to investigate.

**Comment by AnitaPita** [comment]
Thanks @jtreanor for your quick response and keeping me posted.

I can confirm that the cancel button doesn't appear on the image picker for the user, who's on 3.0.3 and running iOS 9.3.1 on an iPhone.

**Comment by jtreanor** [comment]
Thanks @AnitaPita, I'll keep you posted.

**Comment by jtreanor** [comment]
@AnitaPita Could you check if the cancel button is now appearing in version 3.0.4.

I still haven't been able to reproduce either issue reported here but I will keep digging.

**Comment by AnitaPita** [comment]
Hi @jtreanor, I've tested this bug on 3.0.6 and both the image picker and cancel button issues are present. I can consistently reproduce the issue by backgrounding the app or pulling up the command center, as in the following gif where the chat bar pops up unexpectedly during the image picker. There's no cancel button, and due to the bug, once the chat bar appears I can't even send an image because the chat bar is covering the `send/cancel` options.

![intercom_iphonefailv2](https://cloud.githubusercontent.com/assets/9097129/17368292/4d7925f8-5961-11e6-9368-592fa1574589.gif)

**Comment by bboyle18** [comment]
Thanks @AnitaPita, this is great info.
Just wondering if you are customising your app with UIAppearance? 

Cheers

Brian

**Comment by AnitaPita** [comment]
@bboyle18 yes, we are using that for customization. How could that be affecting our integration?

**Comment by bboyle18** [comment]
Hey @AnitaPita
Would you mind sharing the line of code you're using to customise the appearance of your UIBarButtonItem objects? It may be impacting the visibility of the Cancel button. We protect against this but we may have missed a specific type of customisation. 
We're working on a fix for the chat bar issue. 

Thanks for your help with this!
Brian

**Comment by AnitaPita** [comment]
Hi @bboyle18, we realized that we were setting the tint colour of our UIBarButtonItem object to white, so when Intercom popped up, the white Cancel button wasn't visible over the white nav bar. We're working on our fix for this; thanks for your help!

**Comment by jtreanor** [comment]
Thanks for the detail @AnitaPita,

We will also ensure that setting tintColor on UIBarButtonItem will not effect Intercom in the next release.

**Comment by bboyle18** [comment]
Hi @AnitaPita 
We've just released [v3.0.8](https://github.com/intercom/intercom-ios/releases/tag/3.0.8). This fixes these issues. 😉
Thanks for your help in tracking down these bugs.

Cheers

Brian
