### ISSUE TITLE
Broken chat layout on iOS 8

### ISSUE THREAD

**Issue by rockerhieu** [intercom/intercom-ios#156]
## Version info
  - Intercom for iOS version: 3.0.3
  - iOS version: 8.4.1

## Expected behavior
1. No extra empty space should be shown below the softkeyboard
2. No overlapping of Intercom text, chat, and chat status

## Actual behavior
1. Extra empty space shown below the softkeyboard
2. If an conversation exists, Intercom text, chat, and status of chat (seen, time) overlap

## Steps to reproduce
1. Open a chat.
2. When open a chat, the soft keyboard will be pulled up.

See attached screenshot and video
http://recordit.co/wyvM0KW55V

<img width="347" alt="screen shot 2016-07-29 at 2 02 30 pm" src="https://cloud.githubusercontent.com/assets/1281889/17244055/11ae4ad6-55aa-11e6-9e6c-bee11ae01197.png">

**Comment by nucauthu** [comment]
Hi @jtreanor ,
I'm in charge in iOS development, same company with @rockerhieu . We are using IQKeyboardManager. And this is the log when it crashed:
```
The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x18265770 V:[PodIntercom_IntercomConversationInputAccessoryView:0x182dd3a0]-(0)-[_UIKBCompatInputView:0x183ce4f0]>
    When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView _viewHierarchyUnpreparedForConstraint:] to debug.
2016-07-29 16:01:39.557 TKN DevRelease[6138:1939928] *** Assertion failure in -[UIInputSetHostView _layoutEngine_didAddLayoutConstraint:roundingAdjustment:mutuallyExclusiveConstraints:], /SourceCache/UIKit/UIKit-3347.44.2.2/NSLayoutConstraint_UIKitAdditions.m:560
```

**Comment by jtreanor** [comment]
Thanks @nucauthu,

The problem here is that IQKeyboardManager is interfering with Intercom's keyboard handling. However, it will be possible to work around this issue by observing some NSNotifications.

This gist gives an example of how you can disable IQKeyboardManager for Intercom, but enable it for the rest pf you app: https://gist.github.com/jtreanor/edd5121a85168ad9a98af165e1742f93

Let me know if this works out for you.
