### ISSUE TITLE
didFinishLaunchingWithOptions not called

### ISSUE THREAD

**Issue by woofyman99** [intercom/intercom-ios#158]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.4
  - iOS version: 9.3.2

## Steps to reproduce
 1. Launch App
 2. 
 3. 

## Logs

**Comment by jtreanor** [comment]
Hi @woofyman99,

Thanks for sending this in. Can you please give some more details about your app? 
Some things that would be helpful are; is it written in Objective C or Swift? Do you use any other third party push providers? Is there anything unusual about you app's app delegate?

In the meantime it is safe to continue using 3.0.3 though we will work on fixing this immediately.

**Comment by woofyman99** [comment]
Written in Swift.  The app is Agent Snap, it’s a camera app that uses exposure fusing.
Another push provider we use is Localytics.  There’s nothing unusual about the application delegate other than Localytics becoming the application delegate.  But that doesn’t happen until after didFinishLaunchingWithOptions.  I hope that is helpful.

**Comment by jtreanor** [comment]
Thanks @woofyman99,

That is very helpful. I'll keep you updated.

I tested compatibility with Localytics successfully prior to releasing 3.0.4 so there much be something unusual going on here.

**Comment by jtreanor** [comment]
@woofyman99 I've done some more testing and I cannot reproduce unexpected behaviour in a Swift test app with both Localytics and Intercom.

Can you clarify how the issue is manifesting? e.g. Does didFinishLaunchingWithOptions: not get called at all (so the app doesn't launch fully) or does this only happen when opening a push notification?

**Comment by woofyman99** [comment]
It doesn’t get called at all.

If you want, I’ll create a test app that illustrates the bug.

**Comment by jtreanor** [comment]
A test app would be very useful.
Thank you @woofyman99.

**Comment by woofyman99** [comment]
James, I am unable to create a minimal test app that exhibits the bug.
Removing Localytics or using Intercom-swift 3.0.3 fixes the issue.

**Comment by jtreanor** [comment]
@woofyman99 Thanks for trying that.
I will continue to investigate the issue and keep you updated.

**Comment by jtreanor** [comment]
3.0.6 has now been released. This update includes refinements to how Intercom configures push notifications.

@woofyman99  I am confident this will fix your issue. Let me know how it goes for you.

**Comment by garnett** [comment]
@jtreanor now the library has another issue:
I have two delegates in app bundle: `AppDelegate`, and `TestAppDelegate` (I'm changing them for tests). With 3.0.6 `didFinishLaunchingWithOptions` is called on `TestAppDelegate`!

With all respect, your "clever" swizzling is too clever.

**Comment by woofyman99** [comment]
That fixed it!

**Comment by jtreanor** [comment]
@woofyman99 Great, I'm glad that fixed your issue. Thanks for your help getting this resolved.

@garnett I understand your feedback on this. Thanks for reporting this, I'll immediately investigate it.

**Comment by jtreanor** [comment]
3.0.7 has been released to address the last remaining issues here that @garnett pointed out.

I understand that using our swizzling doesn't suit everybody. In the future we will look at introducing a manual method that avoids the swizzle entirely.
