### ISSUE TITLE
trouble using test app w/SDK

### ISSUE THREAD

**Issue by jpohhh** [intercom/intercom-ios#159]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.2
  - iOS version: 9.3

## Expected behavior
Using our test app's API key and App ID should allow Intercom functionality against our test app.

## Actual behavior
Using our test app's identifiers leads to errors in the console w/all API requests leading to 400's. See Logs section for exact statements.

After a ton of testing, I've discovered that if I use the main app API key/App ID, log the user in, shut down the app, and then use the test app API key/App ID, everything works as expected. It's not a sufficient solution for us because it still leads to testing data on the main app, from the login process. It's possible that if the prod app API key/App ID was *ever* used with currently installed app, it will work, so I recommend deleting your test app from the simulator and doing a fresh install that only ever uses the test app API key/App ID before trying to reproduce.

## Steps to reproduce
 1.  Set test app identifiers in appropriate method
 2. Attempt interactions with Intercom that require API calls, such as logging in or opening the message list

## Logs
2016-08-03 14:04:35.990 SimplyWine[30606:8762237] [Intercom] ERROR - Tried to update user attributes but there was a network error - Request failed: bad request (400)
2016-08-03 14:04:39.649 SimplyWine[30606:8762441] [Intercom] ERROR - Tried to get conversations for display in the conversations list but there was a network error - Request failed: bad request (400)

**Comment by skylerwshaw** [comment]
Resolved in discussion within Intercom conversation.

**Comment by ArtemShvydky** [comment]
I have same problem. How I can fix it?

**Comment by ZakharovPaul** [comment]
The same problem for me.Has anyone found the solution?

**Comment by jtreanor** [comment]
@ZakharovPaul This issue was a problem with how Intercom was integrated.

This is likely the case for your issue also. I suggest emailing team@intercom.io to get this resolved.

If you believe there is an issue with Intercom, feel free to open a new issue.
