### ISSUE TITLE
v3 Validation errors

### ISSUE THREAD

**Issue by mhemmings** [intercom/intercom-ios#163]
Since upgrading to v3, the app builds fine, but when we go to upgrade to the app store, the framework suddenly appears in the "binary and entitlements" list, and a validation error occurs.

![screen shot 2016-08-15 at 02 20 19](https://cloud.githubusercontent.com/assets/5692567/17653546/eeabdda4-628e-11e6-8f58-3327af3c4a2a.png)

![screen shot 2016-08-15 at 02 22 50](https://cloud.githubusercontent.com/assets/5692567/17653566/36c82228-628f-11e6-9198-0ff011a0620b.png)

## Version info
  - Intercom for iOS version: 3.0.8
  - iOS version: N/A

## Steps to reproduce
 1. Archive App
 2. Attempt to upload to app store

## Logs

**Comment by jtreanor** [comment]
Thanks @mhemmings,

Did you follow step 3 in the manual install instructions [here](https://github.com/intercom/intercom-ios#manual-installation)?

**Comment by mhemmings** [comment]
@jtreanor Thank's I'll have a try. Does this still allow package management from pod though?

**Comment by jtreanor** [comment]
@mhemmings Yes of course. If you installed with Cocoapods, that step shouldn't be needed.
Does your Podfile include `use_frameworks!`?

**Comment by mhemmings** [comment]
Adding `use_frameworks!` didn't work. So then tried a clean and rebuild, and it has broken a few other libraries

**Comment by jtreanor** [comment]
It seems that is your issue then. `use_frameworks!` is required when using CocoaPods to install 3.0.x. If you can't add  `use_frameworks!`, you should [install Intercom manually](https://github.com/intercom/intercom-ios#manual-installation).

**Comment by mhemmings** [comment]
Doesn't sound like a good solution. Lot's of discussion online about avoiding the use of `use_frameworks!`. Not sure what the solution is, but would like to avoid installing manually so will be rolling back to v2.x until a long term fix can be found.

**Comment by jtreanor** [comment]
Thanks for your feedback on this @mhemmings. We are looking into the best way to resolve this for all use cases.

**Comment by mhemmings** [comment]
@jtreanor Great, thanks for your support.

**Comment by jtreanor** [comment]
After considering this carefully we have released [3.0.10](https://github.com/intercom/intercom-ios/releases/tag/3.0.10). This version removes the requirement for `use_frameworks!` when installing via CocoaPods.
