### ISSUE TITLE
Conversation Header headline text cut off

### ISSUE THREAD

**Issue by jasonblood** [intercom/intercom-ios#166]
I have attached a screenshot of the text being cut off. I suspect its possible for this to happen in non live version if username / company name is long enough. Just does not look to pretty in my opinion the way its cut off.
## Version info
  - Intercom for iOS version: 3.0.10
  - iOS version: 8.4
  - Device: iPhone 5

## Expected behavior
Would expect maybe some padding on the right, the text to be trunicated or a new line maybe ?
## Actual behavior
Text is cut of abruptly.
## Steps to reproduce
 1. Send yourself a message and have your username / company long enough to cause it to be cut off.

## Logs
![screen shot 2016-08-25 at 12 20 08](https://cloud.githubusercontent.com/assets/2226303/17967360/a8ced4d4-6abe-11e6-9a83-6ed5cae8f7c7.png)

**Comment by bboyle18** [comment]
Hi @jasonblood 
Thanks for reporting this 👍  
We'll have this fixed in a future release.

Brian

**Comment by jtreanor** [comment]
[3.0.11](https://github.com/intercom/intercom-ios/releases/tag/3.0.11) has now been released. The fix for this issue is included 😄
