### ISSUE TITLE
Crash in ICMNavigationController if application allows more than one orientation

### ISSUE THREAD

**Issue by nachonet** [intercom/intercom-ios#167]
## Version info
  - Intercom for iOS version: 3.0.10
  - iOS version: 9.3.4

## Expected behavior
Be able to visualize a conversation

## Actual behavior
Crashing when opening a conversation

## Steps to reproduce
 1. Go to a View Controller with no rotation (just Portrait mask on an iPhone device)
 2. Send a message to yourself
 3. Tap on the notification
 4. Crash
(The application allows multiple orientations but in this View Controller it can be used just in Portrait mode)

## Logs
*** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [ICMNavigationController shouldAutorotate] is returning YES'
*** First throw call stack:
(0x23935b0b 0x230f2dff 0x23935a51 0x27f8bb49 0x27f952bf 0x27f9525b 0x27f93bc3 0x27fce511 0x27f0ef1f 0x27f0ece9 0x27f0e435 0x27f0e2e3 0x27f1b37b 0x27f1acf7 0x579595 0x282660f7 0x281be49d 0x281ca7af 0x27f06799 0x238f72b1 0x238f55a7 0x238f59e5 0x238441c9 0x23843fbd 0x24e60af9 0x27f7c435 0x1fb1cd 0x234f0873)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by bboyle18** [comment]
Hi @nachonet 

Thanks for reporting this issue 👍

Intercom bases its orientation off your rootViewController, so it seems in this case that we are getting the wrong orientation information. Can you give me a little more info about your view hierarchy? Is the ViewController that has no rotation embedded within a UINavigationController?

Thanks

Brian

**Comment by nachonet** [comment]
Thank you so much for your help

When I started to explain the view hierarchy here, I found out what the problem was. It was related to the rootViewController (and its orientation methods) which was indeed a UINavigationController.

Thanks again :)

**Comment by bboyle18** [comment]
Hey @nachonet 
I'm glad you sorted your problem.
I'm curious as to how you were changing your orientation methods in the rootViewController as Intercom should have been able to pick up the correct orientation. Would you be able to share a little more info with us so that we can prevent this happening in the future?

Thanks

Brian

**Comment by nachonet** [comment]
Hi Brian,

The application supports multiple orientations but the rootViewController (which is a subclass of UINavigationController) only supports the Landscape orientation. Besides that, there was a UINavigationController category which was establishing Portrait as orientation and there was a conflict between those files.
Surprisingly, it was working fine.

Sorry for submitting this and thanks again.

**Comment by jtreanor** [comment]
Thanks for the detail @nachonet 😄
