### ISSUE TITLE
setInAppMessagesVisible(true) displays read messages as unread

### ISSUE THREAD

**Issue by michaelhollman** [intercom/intercom-ios#168]
## Version info
  - Intercom for iOS version: `3.0.10`
  - iOS version: N/A (occurs on at least an 8.1 iPhone 5s, 9.3.3 iPad Air, and 9.3 simulator)

## Expected behavior

Calling `setInAppMessagesVisible(false)` followed by `setInAppMessagesVisible(true)` when the current user has zero unread messages should not display the in-app message UI. 

## Actual behavior

Calling `setInAppMessagesVisible(false)` followed by `setInAppMessagesVisible(true)` when the current user has received, viewed, and dismissed a message during the current session will cause the message to re-appear as if it was just sent. Subsequent calls to `setInAppMessagesVisible(false)` followed by `setInAppMessagesVisible(true)` will repeat the behavior.

Additionally, announcement-style messages will appear fully-opened, instead of in the "minimized" state at the bottom of the screen.

## Steps to reproduce

I forked this repo and made additions to the included `Sample-Swift` project to help test `setLauncherVisible(…)`, `setInAppMessagesVisible(…)`, `IntercomUnreadConversationCountDidChangeNotification`, and `unreadConversationCount()`. Those changes are on the `SetInAppMessagesVisibleBugResearch` branch of my fork ([comparison](https://github.com/intercom/intercom-ios/compare/master...michaelhollman:SetInAppMessagesVisibleBugResearch)).

Here is a screen recording of me doing the following steps on that branch: [inappmessages-bugresearch.mov.zip](https://github.com/intercom/intercom-ios/files/438005/inappmessages-bugresearch.mov.zip).

1. Log in (I did this before I started recording; used a new, fake email address)
2. Manually send a message via intercom.io
3. After receiving the message in the app, tapping `Hide` and `Show` next to `In App Messages` will appropriately hide and show the unread in-app message, as expected.
4. Open and close the message. The unread conversation count goes down to 0, as expected.
5. Tap `Hide` next to `In App Messages`, which calls `setInAppMessagesVisible(false)`. Nothing changes visually, as expected.
6. Tap `Show` next to `In App Messages`, which calls `setInAppMessagesVisible(true)`. The last message appears again as if it were brand new. This is _not_ what I expect.
7. Manually send an announcement-style message via intercom.io.
8. The announcement will appear "minimized," as expected.
9. Repeat steps 5 & 6.
10. The announcement immediately appears "maximized".

In some scenarios, step 8 seemed to be skipped, and a new announcement-style message would immediately appear "maximized." I wasn't able to consistently reproduce this, though.

## Logs

No logs appeared in Xcode's output window, even with calling `enableLogging()`.

**Comment by jtreanor** [comment]
Thanks for the detailed report @michaelhollman. We will investigate this and get back to you.

**Comment by camclendenin** [comment]
I've experienced what may be the same issue. The issue doesn't seem to happen with "chat" style messages, but it consistently happens with "post" message types.

**Steps to reproduce**
1. Have a view controller embedded in a navigation controller (view controller's viewDidAppear: should call setInAppMessages(true) )
2. Send a "post" message to the app while the app is open and on that initial view controller.
3. Tap the "post" when it appears so that it is in fullscreen
4. Close the fullscreen post via the "X" button on the upper right
5. Tap a button on the main view controller that trigger's a new view controller to be pushed into the navigation controller (This controller should have setInAppMessages(false) in its viewDidLoad: )
6. Pop this second view controller by tapping the back button on the nav bar.
7. The fullscreen post that will appear again, even though you already read and closed it.

**Comment by jtreanor** [comment]
Hi @michaelhollman and @camclendenin,

Just a quick update here. We have got to the bottom of this issue and are currently working on a fix. It will be included in our next released which will be available within the next week.
I'll keep you posted.

Thanks again for reporting this 😄

**Comment by michaelhollman** [comment]
@jtreanor Any further word on this or any update on an ETA? I'm working on planning my work for the next couple weeks and wondering when I can expect the next release. If it's been pushed back, no worries, just let me know.

Thanks again! 😄

**Comment by jtreanor** [comment]
[3.0.11](https://github.com/intercom/intercom-ios/releases/tag/3.0.11) has now been released. The fix for this issue is included 😄 

Thanks everyone for your help.
