### ISSUE TITLE
Import Intercom.framework

### ISSUE THREAD

**Issue by lowki93** [intercom/intercom-ios#170]
I use intercom with Pods.

My test crash because Intercom.Framework is not linked in projet during pod installation.

Please fix it please.

Thanks

**Comment by jtreanor** [comment]
@lowki93 could you give some more detail on the issue?

What version are you using? What is the error you are seeing?

**Comment by ariyandiwidarto** [comment]
Hi, I am having the same issue too.
The crash occurred after I upgrade the Intercom iOS SDK from version 2.3.21 to version 3.0.9 with CocoaPods. Here is the error:

dyld: Library not loaded: @rpath/Intercom.framework/Intercom
  Referenced from: /Users/<MY_USER_NAME>/Library/Developer/CoreSimulator/Devices/<DEVICE_ID>/data/Containers/Bundle/Application/<APPLICATION_ID>/<APPLICATION_NAME>.app/<APPLICATION_NAME>
  Reason: image not found

Thank you in advance.

**Comment by ariyandiwidarto** [comment]
Ok, upgrading to version 3.0.10 solve the problem.

Thank you for your fast response.

**Comment by jtreanor** [comment]
@lowki93 I believe your issue will also be solved by upgrading to 3.0.10.

If you are still seeing issues, feel free to reopen this with more details.
