### ISSUE TITLE
presentMessenger

### ISSUE THREAD

**Issue by syrakozz** [intercom/intercom-ios#171]
presentMessenger not found , 
plz update the example with the correct method

**Comment by bboyle18** [comment]
Hi @syrakozz 👋
Thanks for getting in touch. 
Can you please provide us with a little more info of the issue you are having? Can you attach logs from the console?

Thanks

Brian

**Comment by jtreanor** [comment]
@syrakozz It looks like you may be using an older version on Intercom. `presentMessenger` was introduced in 3.0.0. Feel free to reopen this if you are still seeing an issue.
