### ISSUE TITLE
How to Detect intercom view closed?

### ISSUE THREAD

**Issue by pocket7878** [intercom/intercom-ios#175]
Hi, I want to run callback when Intercom view is closed by user.
Is there any method or option to detect intercom view visibility changed?

**Comment by bboyle18** [comment]
Hi @pocket7878 👋

Thanks for your question!
Yes, it's possible to detect when Intercom's window changes. We have two NSNotifications you can listen to

IntercomWindowWillHideNotification
IntercomWindowDidHideNotification

Cheers

Brian

**Comment by mkeremkeskin** [comment]
NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(keyboardWillShow(_:)), name: IntercomWindowDidHideNotification, object: nil)

I'm using as above not working. What am I missing?

**Comment by bboyle18** [comment]
Hi @mkeremkeskin 

Thanks for getting in touch 😄 
It looks like the code you are using is not valid Swift. You should check out Apple's documentation on `NotificationCenter` https://developer.apple.com/reference/foundation/notificationcenter

In the meantime, the following works for me:

``` 
NotificationCenter.default.addObserver(self, selector: #selector(self.intercomClosed), name: NSNotification.Name.IntercomWindowDidHide, object: nil)

func intercomClosed() -> Void {
        print("hello");
    }
```

Brian

**Comment by mkeremkeskin** [comment]
Hi @bboyle18 thnx for the quick response.

I'm sure my code is valid and works. It's swift 2.3 .

    NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(keyboardWillShow(_:)), name: UIKeyboardWillShowNotification, object: nil)


for example above is the same code just with different notification identifier and works as intended.

`NSNotification.Name.IntercomWindowDidHide` part in your code is giving error for me. Should the notification identifier be taken directly from NSNotification?

**Comment by bboyle18** [comment]
@mkeremkeskin The example I gave can be disregarded if you are using Swift 2.3. That example is Swift 3.0 syntax.

You will receive the notification when the Intercom window is closed. So I would have a look at how and when you are subscribing to this event.

Cheers

Brian

**Comment by mkeremkeskin** [comment]
@bboyle18 I'm subscribing in `viewDidLoad()`

    NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(keyboardWillShow(_:)), name: IntercomWindowDidHideNotification, object: nil)

this is the code I'm using for subscribing.

Notification is not triggered I guess, but don't know why.

**Comment by bboyle18** [comment]
@mkeremkeskin Can you explain the specific scenario you are trying to listen for events for?
- Is it when the Intercom Window closes?
- Or is it when an inapp notification disappears?

Thanks

Brian

**Comment by mkeremkeskin** [comment]
@bboyle18 
I want to detect when user taps X button on Intercom support window. So I want to detect closing of intercom window to open keyboard. 

Thanks.

**Comment by bboyle18** [comment]
Ok, thanks for confirming. 👍 
This event should fire in that situation.
Can you test your snippet of code in the Swift sample app? https://github.com/intercom/intercom-ios/tree/master/Examples/Sample-Swift

Confirming that it works here should help with identifying the problem.

Thanks!

**Comment by mkeremkeskin** [comment]
@bboyle18 

It was a problem with my method definition and its arguments. Now I can detect closing of the intercom screen thanks for the all help.

Also it would be good if you provide a callback mechanism instead of notification for future releases.

Regards,

**Comment by bboyle18** [comment]
Glad it worked out for you 🎉 
We'll take you suggestion about a callback mechanism into consideration.

Cheers

Brian

**Comment by mkeremkeskin** [comment]
@bboyle18  Of course. It's nearly same as your example. 

        NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(intercomClosed), name: IntercomWindowDidHideNotification, object: nil)

        func intercomClosed(){
               textField.becomeFirstResponder()
        }

Above code is written in Swift 2.3
