### ISSUE TITLE
Message Disappears

### ISSUE THREAD

**Issue by yoon-boom** [intercom/intercom-ios#177]
## Version info
- Intercom for iOS version: Latest
- iOS version: 8.xx - 10.0 (Simulator & Device)
## Expected behavior

iOS Client (ME) - Web Client (ME)
iOS Client (Unregistered Anonymous) - Web Client (ME)
Message should communicates between iOS and Web end.
## Actual behavior

iOS Sends message then once Web Client receives, reads and iOS end message disappears. As soon as Web Client sees message iOS end all messages are gone. It works find with example code that provided. But on my company project, this unexpected behavior only happens. 
## List of frameworks used in project

pod 'AFNetworking'
pod 'Fabric'
pod 'Crashlytics'
pod 'ACPDownload'
pod 'DTCoreText', :git => 'https://github.com/yoon-boom/DTCoreText.git',
                  :branch =>'master'
pod 'FastImageCache'
pod 'GoogleAnalytics'
pod 'MZFormSheetController'
pod 'AGWindowView'
pod 'Reachability'
pod 'SVPullToRefresh'
pod 'DZNEmptyDataSet'
pod 'Ono'
pod 'PPSSignatureView'
pod 'AWSCore'
pod 'AWSS3'
pod 'AWSCognito'
pod 'FontAwesomeKit'
pod 'Harpy'
pod 'PSTAlertController'
pod 'AFDownloadRequestOperation'
pod 'MMDrawerController', :git => 'https://github.com/yoon-boom/MMDrawerController.git'
pod 'DAKeyboardControl', :git => 'git@github.com:WhatYoonSays/DAKeyboardControl.git'
pod 'LKBadgeView', :git => 'https://github.com/yoon-boom/LKBadgeView.git'
pod 'HTAutocompleteTextField'
pod 'libPhoneNumber-iOS', '~> 0.7'
pod 'DGActivityIndicatorView'
pod 'DFImageManager'
pod 'Intercom'
## Steps to reproduce
1. on `application:didFinishLaunchingWithOptions:`
2. `[Intercom setApiKey:@"ios_sdk-XXX" forAppId:@"XXX"];`
   `[Intercom setLauncherVisible:YES];`
   `[Intercom enableLogging];`
   `[Intercom registerUnidentifiedUser];`
## Screen Shots

https://cl.ly/0l1M1l1o3X3I
![intercom bug](https://cloud.githubusercontent.com/assets/7377941/18652302/2053082e-7e86-11e6-9d79-78c04dc0afe4.gif)

**Comment by jtreanor** [comment]
Thanks for reporting this @yoon-boom.

We will investigate this and let you know what we find.

James

**Comment by bboyle18** [comment]
Closing this issue as its specific to this customer's implementation. Its not reproducible and has not been reported by any other customers.
@yoon-boom Feel free to reopen if its still causing a problem and you can provide info to help us reproduce it.

Brian
