### ISSUE TITLE
Push notifications for development version.

### ISSUE THREAD

**Issue by fcamaster** [intercom/intercom-ios#179]
Hi, we're not able to send push notifications to our development builds.

## Version info
  - Intercom for iOS version:  3.0.12
  - iOS version: iOS 9.3.1 - iOS 10

## Expected behaviour

Receive notifications
## Actual behavior

The notifications are not received
## Steps to reproduce
 1. Create test app on Intercom
 2. Configure and upload the .pem file for the development apns env.
 3. Send a manual message.

Note: I've test to send a notification from the command line and from another testing tools and it worked.
## Logs

[Intercom] INFO - Registering device token for push notifications

**Comment by jtreanor** [comment]
Hi @fcamaster 

Thanks for sending this in.

Development push notifications should work correctly. Can you try uploading a production .pem file and test development push with that (both prod and dev push works with production certs)?

**Comment by fcamaster** [comment]
Hi @jtreanor 

I've tried with the production .pem file and now it works.
I really thought that for the test app a development certificate was needed.

Thanks.

**Comment by jtreanor** [comment]
I'm glad this worked for you @fcamaster.

I'll investigate why the development cert didn't work as expected.
