### ISSUE TITLE
IntercomWindowWillShowNotification not fired

### ISSUE THREAD

**Issue by app-buzz** [intercom/intercom-ios#183]
If i send a test in-app-message to my IOS app, the windowWillShow: method never gets called. The message is displayed so Intercom works correctly in the app and logs all events and user attributes:

`NSNotificationCenter *nc = [NSNotificationCenter defaultCenter];
[nc addObserver:self selector:@selector(windowWillShow:) name:IntercomWindowWillShowNotification object:nil];`

## Version info
  - Intercom for iOS version: 3.0.13
  - iOS version: 9.3

## Expected behaviour

Notification is fired when intercom window is shown.

## Actual behaviour

Notification never gets fired.

## Logs

**Comment by bboyle18** [comment]
Hi @app-buzz 👋 

Are you expecting that the `IntercomWindowWillShowNotification` notification will get fired when an in-app (chathead + message snippet) is displayed on screen? It will not get fired in this situation.
That notification only gets fired when you open the Messenger window.

Cheers

Brian

**Comment by app-buzz** [comment]
So there is no way to detect when Intercom shows anything on your screen?

**Comment by jtreanor** [comment]
Hi @app-buzz,

Unfortunately there is not right now. That is a valid feature request however, we'll look at adding this in a future version.

JAmes
