### ISSUE TITLE
Crash on iOS 8 or 9

### ISSUE THREAD

**Issue by phatmann** [intercom/intercom-ios#187]
## Version info
  - Intercom for iOS version: 3.0.16
  - iOS version: 9.3

## Expected behavior

App starts.

## Actual behavior

App crashes.

## Steps to reproduce
 1. Install Intercom via CocoaPods
 2. Run app on iOS 8 or 9
 3. App crashes

## Logs
```
dyld: Library not loaded: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
  Referenced from: /Users/tony/Library/Developer/CoreSimulator/Devices/93E3E2B3-70BE-45D7-8EC3-0B8B0196226C/data/Containers/Bundle/Application/C6FC9FC5-6391-4556-8818-FD69AFB914C9/NextHelper.app/NextHelper
  Reason: image not found
```

Note that I commented out all of my code that imported `Intercom` or `UserNotifications`. If I remove Intercom from my Podfile no crash, and if I add it back I crash. So it is clearly the culprit.

**Comment by bboyle18** [comment]
Hi @phatmann 

Thanks for reporting this. We're investigating it.

Brian

**Comment by bboyle18** [comment]
Hey @phatmann 
Would you be able to open `Intercom.h` in your project and tell me what version you see at the top of the file?
Cocoapods are currently having issues so I just want to make sure that you have version 3.0.16 installed, and not an older version.

Cheers

Brian

**Comment by blommegard** [comment]
I experienced the same issue running version 3.0.16 of Intercom.

It seems that you (Intercom) have not weakly linked `UserNotifications.framework`

The workaround for now is to to weakly link it yourself:
![screenshot 2016-10-19 13 50 55](https://cloud.githubusercontent.com/assets/86447/19517727/225a8a68-9603-11e6-8d69-7482d3bbfb54.png)

**Comment by bboyle18** [comment]
Hi @blommegard 
We are working on a fix and will have a new version available later today.
Cheers

Brian

**Comment by bboyle18** [comment]
Hi @phatmann & @blommegard 

I've just release 3.0.17 which fixes this issue. 
The cause of this was that our podspec was not updated correctly and still contained a reference to UserNotifications. We since put in place checks so that this can't happen again.

Apologies and thanks for bringing this to our attention 👍 

Cheers

Brian

**Comment by UpKeepInfo** [comment]
:(
