### ISSUE TITLE
404 error on iPhone 7 simulator with multiple intercom apps

### ISSUE THREAD

**Issue by mjmayank** [intercom/intercom-ios#188]
## Version info
  - Intercom for iOS version: 'Intercom', '~>3.0.17'
  - iOS version: iPhone 7 Simulator Version 10.0 (SimulatorApp-700.5.3

## Expected behavior
Intercom to load conversations

## Actual behavior
404 error

## Steps to reproduce
 1. Create 2 different but very simple apps with Intercom installed with same app ID and API key
 2. Open one app and a conversation with a registered user, it should work.
 2. Open a second app and register the same user
 3. Fail

## Logs
[Intercom] ERROR - Tried to get conversations for display in the conversations list but there was a network error - Request failed: not found (404)

I'm not really sure what's going on because everything works fine in the iPhone 7 plus, iPhone 6 plus, and iPhone 6S simulator, and it works fine on my iPhone 6S device. I haven't tested it on an iPhone 7 device.

I don't really need this functionality but I started by using the sample app and then as I switched to my own app it kept failing and I couldn't figure out why and finally this is what I diagnosed.

**Comment by bboyle18** [comment]
Hi @mjmayank 👋

Intercom was down for a period today due to an issue with Amazon Web Services. This may be what caused your issue. 
Can you retest it and see if it's working now?

Thanks
Brian

**Comment by mjmayank** [comment]
Hmmm, it seems to be working now. Although when I was testing it on all those different simulators and sometimes it would work and sometimes it wouldn't (within seconds of each other). This same bug also happened to me a couple days ago. I'm not convinced it's related to the widespread outages that happened today, but for now it's working! I can let you know if it comes back.

Maybe some of the conversations were cached? But I also did some hard simulator resets while testing.

**Comment by bboyle18** [comment]
Yeah, some requests would have succeeded and others wouldn't, even within seconds of each other. We don't do any caching on the conversation list. 

Thanks for reporting the issue 👍🏻

Brian
