### ISSUE TITLE
Unable to switch users properly

### ISSUE THREAD

**Issue by mhemmings** [intercom/intercom-ios#189]
We allow users to login as another user. To do this we call:
`[Intercom reset]`
followed by
`[Intercom registerUserWithUserId:userIdString];`

However, this is causing all sorts of issues with Intercom. Two users being merged into one, duplicate users, etc.

Sparing huge detail as not to clutter this issue, but if this is actually the correct way to switch users  then I'm more than happy to provide more.

**Comment by jtreanor** [comment]
Hi @mhemmings,

Thanks for writing in. I don't understand the issue you are describing here.

Calling `[intercom reset]` followed by `[Intercom registerUserWithUserId:userIdString]` is the correct way to switch users.

Can you provide more detail on the issues you are seeing with it?

**Comment by jtreanor** [comment]
@mhemmings Any update here? Unfortunately I don't understand the issue you are describing.

**Comment by jtreanor** [comment]
@mhemmings I'm closing this issue as it appears to be an integration issue.
If you think there is an issue with Intercom here, please let us know.
