### ISSUE TITLE
Linker error when manually installing 3.0.18

### ISSUE THREAD

**Issue by rogchap** [intercom/intercom-ios#193]
I'm manually installing `Intercom.framework` and get a Linker Error:

```Obj-C
Undefined symbols for architecture x86_64:                                                                              
  "_OBJC_CLASS_$_Intercom", referenced from: 
```

All I'm doing is "Dragging" into `Embedded Binaries` (making sure to copy)

I then tried with an older version of `Intercom.framework`  v3.0.0 and it all built successfully (no issues)

This leads me to believe that there is an issue within the latest binary.

**Comment by jtreanor** [comment]
Hi @rogchap,

Thanks for reporting this. The issue was a mistake when pushing up the latest binary. It is now fixed.
