### ISSUE TITLE
Blank messages

### ISSUE THREAD

**Issue by antonholmquist** [intercom/intercom-ios#195]
See screenshot. Seems to happen randomly for our users. Closing and re-opening the chat sometimes solves the issue temporarily.

## Version info
  - Intercom for iOS version: 3.0.10
  - iOS version: 10.1.1

![img_0713](https://cloud.githubusercontent.com/assets/505089/20052123/cf1c1982-a4d2-11e6-97a4-c9c02d364127.png)

**Comment by bboyle18** [comment]
Hi @antonholmquist 👋

This is a bug in Apple's UICollectionView in iOS 10. We have put in a fix in our code to prevent this happening until Apple fixes the underlying problem. 
If you update to the latest version of Intercom iOS it should fix this issue for you. 

Cheers

Brian
