### ISSUE TITLE
Intercom.framework file not going to Carthage Build folder.

### ISSUE THREAD

**Issue by Coooi** [intercom/intercom-ios#196]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.18
  - iOS version: 9.0

## Expected behavior
Intercom.framework file should go to Carthage/Build/iOS folder.

## Actual behavior
Log
*** Skipped building intercom-ios due to the error:
Dependency "intercom-ios" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at Optional("https://github.com/intercom/intercom-ios/issues/new")

## Steps to reproduce
 1. Run `carthage update --platform iOS --no-use-binaries`

## Logs
*** Skipped building intercom-ios due to the error:
Dependency "intercom-ios" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at Optional("https://github.com/intercom/intercom-ios/issues/new")

**Comment by jtreanor** [comment]
Hi @Coooi,

Intercom.framework is distributed as a binary so the `--no-use-binaries` flag prevents it from being installed. The error you are seeing is from Carthage attempting and failing to build Intercom itself.

The solution here is to not use `--no-use-binaries`
