### ISSUE TITLE
Invalid bitcode version on Xcode 7.3.1

### ISSUE THREAD

**Issue by nucauthu** [intercom/intercom-ios#200]
Hi. I known that we can solve this error by disable bitcode but I'm really prefer that solution. Are there anyway to archive successful on Xcode 7? We are not able to upgrade to Xcode 8 (means Swift 3). Thanks!

## Version info
  - Intercom for iOS version: 3.0.20
  - Xcode version: 7.3.1

## Expected behavior: 
archive successful

## Actual behavior: 
Invalid bitcode version (Producer: '800.0.42.1_0' Reader: '703.0.31_0')

## Steps to reproduce
 1. Update cocoapod from 3.0.12 to 3.0.20
 1. Pod install
 2. Archive project

## Logs
Invalid bitcode version (Producer: '800.0.42.1_0' Reader: '703.0.31_0')

**Comment by jtreanor** [comment]
Hi @nucauthu,

You are receiving this error because recent versions of Intercom have been built with Xcode 8. 

Unfortunately the solutions for the error are either to disable bitcode or use Xcode 8. I understand this is not ideal but the incompatibility is outside our control.

James
