### ISSUE TITLE
Framework isn't marked as safe for extension use

### ISSUE THREAD

**Issue by MrAlek** [intercom/intercom-ios#202]
The current framework version (`3.0.21`) isn't marked as safe for use in extensions. Is that on purpose or could you just turn on the "[Require Only App-Extension-Safe API](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html)" build setting in the framework?

We'd like to do some events tracking in a share extension and this is currently stopping us from doing that.

**Comment by jtreanor** [comment]
Thanks @MrAlek.

As you correctly point out, Intercom cannot currently be used in an extension. I understand why you would like to do this and we will consider your feature request.

In the meantime, you can use our [public API](https://developers.intercom.com/reference) to log user events.
