### ISSUE TITLE
update_last_request_at and last_request_at are not updated

### ISSUE THREAD

**Issue by pacification** [intercom/intercom-ios#204]
## Version info
  - Intercom for iOS version: 3.0.22
  - iOS version: 10.2

## Expected behavior

When i send `Intercom.updateUserWithAttributes(["email": email, "update_last_request_at": true]` on server every 15 sec, the value `LAST SEEN`  

<img width="114" alt="last_seen" src="https://cloud.githubusercontent.com/assets/2921634/21430306/b6451b88-c873-11e6-86a8-289887024556.png">
 must be updated (set to "Just now") in my web application and user should be "green" (online).

## Actual behavior

Unfortunately, the value `Last seen` not updated and user is offline.

## Steps to reproduce
 1. `Intercom.updateUserWithAttributes(["email": email, "update_last_request_at": true]` every 15 sec

## Logs
There are no logs because of `Intercom.enableLogging()` doesn't show me any kind of information :(

**Comment by jtreanor** [comment]
Hi @pacification,

Although we can certainly do a better job documenting it, updating last seen in this way is not supported.
Last seen is updated automatically every time the app is opened. Why do you update it every 15 seconds?

**Comment by pacification** [comment]
Hi, @jtreanor,

> Why do you update it every 15 seconds?
I need user to be online when he uses the app. Maybe there is another method to achieve it?

**Comment by jtreanor** [comment]
Sorry for the delay @pacification, the team was on a break for the holidays.

Without adding any explicit update calls, your users will show as online every time the app is opened? Is this the behavoiur you are looking for?

**Comment by pacification** [comment]
> Without adding any explicit update calls, your users will show as online every time the app is opened? Is this the behavoiur you are looking for?
Exactly.

**Comment by jtreanor** [comment]
@pacification in that case you don't need to do any user updates. Your users' last seen should update when they open the app. Is this happening as expected?

**Comment by bboyle18** [comment]
Hi @pacification 👋 
I'm just following up on this issue. Is Intercom working as expected for you now? (i.e. Your users' last seen time should update when they open the app.)

It would be great to let us know so that we can close this issue, or help you further if you are stil having problems.

Thanks!

Brian

**Comment by delight-by** [comment]
Didn't want to open new issue with the same question.

You API reference states:
**update_last_request_at** A boolean value, which if true, instructs Intercom to update the users' last_request_at value to the current API service time in UTC.

I too thought that last_request_at and Last Seen are interconnected if not the same, but this appeared not to be the case.
Web widget sends pings constantly (I mean when user just has the page open), that's probably why Last Seen is properly updated for web users. What's the mobile SDK way of achieving the same behavior - making Last Seen showing "Just now" when user **uses** our application, not just when they **open** it.
