### ISSUE TITLE
Errors submitting to app store - fails at xcode submission

### ISSUE THREAD

**Issue by Hendler** [intercom/intercom-ios#205]
- unsupported architectures. The executable for xxx/intercom.framework contains unsupported architectures '[x86_64, i386]'."
- "invalid segment alignment. The app binary at xxx/frameworks/intercom.framework/intercom' does not have proper segment alignment. Try rebuilding the app with the latest xcode version".
- The executable 'payload/xx/frameworks/intercom.framework' is not a position independent executable. Please ensure that your build settings are configured to create PIE executables.

## Version info
  - Intercom for iOS version:
3.0.22 for Intercom
xcode version 8.0 - (asked him about upgrading to 8.2, says that's not the main build line, says it's irrelevant)
OSX 10.11.6

https://app.intercom.com/a/apps/tx2p130c/inbox/jonathan.hendler@intercom.io/conversations/7482133306

**Comment by bboyle18** [comment]
Converting to a private issue

**Comment by cpytel** [comment]
Sorry, but I'm getting these same errors. Is there a resolution that can be documented for myself and others?

**Comment by bboyle18** [comment]
Hi @cpytel 👋 
Have you integrated Intercom manually or using Cocoapods or Carthage?

**Comment by cpytel** [comment]
I've integrated via Carthage.

**Comment by bboyle18** [comment]
Ok great 😄 
Can you confirm that you've completed this step? https://github.com/Carthage/Carthage#adding-frameworks-to-an-application
Omitting this step can lead to the error you are seeing.

Let me know how you get on 👍 

Brian

**Comment by cpytel** [comment]
Yes, I've done that - here is what my configuration looks like:

![frameworks](https://cloud.githubusercontent.com/assets/5015/22068904/7fb2c5ec-dd64-11e6-8729-1f56f01bc46d.png)

**Comment by bboyle18** [comment]
Can you send me the exact errors you are getting please?
Thanks!

**Comment by bboyle18** [comment]
@cpytel I've found a similar issue for Carthage on Stackoverflow http://stackoverflow.com/a/39489491/260506
It might be worth moving your `Embed Frameworks` step so that it runs before `Copy Frameworks`.

Brian

**Comment by cpytel** [comment]
Thanks, @bboyle18 that appears to have fixed it! Thanks again.

**Comment by sunto** [comment]
I'm still getting the errors.  I've brought in Intercom manually, and I've added strip frameworks properly as per instructions but I still seem to be getting the unsupported architectures issue:

```
[16:29:36]: [Transporter Error Output]: ERROR ITMS-90087: "Unsupported Architectures. The executable for LendeskMobile.app/Frameworks/Intercom.framework contains unsupported architectures '[x86_64, i386]'."
[16:29:36]: [Transporter Error Output]: ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'LendeskMobile.app/Frameworks/Intercom.framework/Intercom' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
[16:29:36]: [Transporter Error Output]: ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
[16:29:36]: [Transporter Warning Output]: WARNING ITMS-90080: "The executable 'Payload/LendeskMobile.app/Frameworks/Intercom.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."
[16:29:37]: Transporter transfer failed.
[16:29:37]: WARNING ITMS-90080: "The executable 'Payload/LendeskMobile.app/Frameworks/Intercom.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."
```

**Comment by jtreanor** [comment]
Hi @sunto,

Thanks for sending on these details. Would you mind sending a screenshot of your "Build Phases" tab? I can see the 'Run Script' phase is running but it would be good to double check its contents.

Also, I see you have CocoaPods installed. If you wish you can install Intercom via CocoaPods and bypass all these issues.

**Comment by sunto** [comment]
<img width="1093" alt="screen shot 2017-01-30 at 8 21 18 am" src="https://cloud.githubusercontent.com/assets/607956/22433854/ab71cb4c-e6ce-11e6-9b0a-df4cab74a398.png">

**Comment by jtreanor** [comment]
@sunto Do you have multiple targets in your app? If so, is this added to every target?

**Comment by sunto** [comment]
There is one target for the app itself, and there is a second Tests target which doesn't have the capabilities tab.  Let me try that as well, it seems odd that it would be required there.

**Comment by jtreanor** [comment]
@sunto I'm afraid I'm not sure what may be happening here. This has not been a problem for any of our other customers.

In the absence of am immediate solution, could you consider installing via CocoaPods? This would completely remove the need for the script.

**Comment by sunto** [comment]
It's weird...we've tested the same code base running the same OS and xcode versions.  It seems like the strip frameworks fails on one computer, but not the other.  It's probably something deeper in the settings or permissioning. 

Trying out cocoapods getting an error on "Argument list too long: recursive header expansion failed "

**Comment by Twinski** [comment]
@sunto
You have to put this full script in "Run script" step:
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Intercom.framework/strip-frameworks.sh"

You only had "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Intercom.framework/strip-frameworks.sh"

So you forgot the bash at the front.. It seems to work for me. It's uploading to TestFlight right now.

**Comment by jtreanor** [comment]
Hi @Twinski,

Thanks for letting us know about this. Do you know where you saw this error?

**Comment by Allan-Nava** [comment]
I have this problem when I i try to upload the Archive Release.
> ERROR ITMS-90087: "Unsupported Architectures. The executable for Sportube.app/Frameworks/GoogleCast.framework contains unsupported architectures '[x86_64, i386]'."

I use this script:
```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
    FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
    FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
    echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

    EXTRACTED_ARCHS=()

    for ARCH in $ARCHS
    do
        echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
        lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
        EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
    done

    echo "Merging extracted architectures: ${ARCHS}"
    lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
    rm "${EXTRACTED_ARCHS[@]}"

    echo "Replacing original executable with thinned version"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

I use ionic cordova build ios --release and it works "build succeeded", but when I try to upload to app store I have this problem:
> ERROR ITMS-90087: "Unsupported Architectures. The executable for Sportube.app/Frameworks/GoogleCast.framework contains unsupported architectures '[x86_64, i386]'."

**Comment by bboyle18** [comment]
Hi @Allan-Nava 👋 
This doesn't look like an Intercom issue. You should probably get onto `GoogleCast` guys to fix this. 👍 
Brian

**Comment by Allan-Nava** [comment]
Hi @bboyle18 ,

Ok, but is very strange...
