### ISSUE TITLE
Increase in memory use each time an app is moving to background and back to foreground

### ISSUE THREAD

**Issue by EdiZeituni** [intercom/intercom-ios#207]
## Version info
  - Intercom for iOS version: 3.0.12
  - iOS version: 10.1.1

## Expected behavior
Memory should not increase

## Actual behavior
Memory increases by ~500KB

## Steps to reproduce
 1. Launch an app that uses Intercom (this is enough to call Intercom::setApiKey on AppDelegate)
 2. Move to background
 3. Return to the app

**Comment by bboyle18** [comment]
Hi @EdiZeituni 👋 

Thanks for reporting this 👍 
We'll look into this and get back to you here with any updates.

Thanks

Brian

**Comment by bboyle18** [comment]
Hi @EdiZeituni 

Would you be able to share your memory analysis with us please? We'd love to take a closer look at it 😄 
Have you got an Instruments file you can send us? If you don't want to share that here, you can do so via the Messenger on intercom.com.

Thanks a lot!

Brian

**Comment by EdiZeituni** [comment]
I can't reproduce this issue :-/
You can close it.
Thank you for the response.
