### ISSUE TITLE
API deprecation & new access token usage

### ISSUE THREAD

**Issue by ded** [intercom/intercom-ios#212]
This is a matter of asking how we take advantage of using the new access keys with the iOS SDK, and replacing our old API keys.

Currently we're being asked to do this:

`Intercom.setApiKey("123", forAppId: "xxxxxx")`

But I don't see any documentation on how to move forward using access tokens.

**Comment by bboyle18** [comment]
Hi @ded 👋 

Thanks for getting in touch.
The new access tokens are currently only available for Intercom's REST API.
The iOS SDK still uses the API and AppId. You can continue to use this like your code sample above demonstrates. Theres more documentation on using your API key and your AppId [here](https://developers.intercom.com/docs/ios-installation#section-step-3-initialize-intercom).

Thanks

Brian

**Comment by ded** [comment]
OK cool, so API keys will not be deprecated for mobile SDKs?

**Comment by bboyle18** [comment]
Not for the foreseeable future. 
Brian
