### ISSUE TITLE
spelling issue

### ISSUE THREAD

**Issue by yjb94** [intercom/intercom-ios#213]
in swift sample, appdelegate

it is written like

let INTERCOM_APP_ID = "<#YOUR APP ID#>"
let INETERCOM_API_KEY = "<#YOUR API KEY#>"

think this should change into

let INTERCOM_APP_ID = "<#YOUR APP ID#>"
let INTERCOM_API_KEY = "<#YOUR API KEY#>"

**Comment by DaleCantwell** [comment]
@yjb94 thanks for letting us know, we will update the sample with the correct spelling.

**Comment by bboyle18** [comment]
@yjb94 This is now fixed. Thanks for letting us know 👍
