### ISSUE TITLE
cannot load conversations list.

### ISSUE THREAD

**Issue by yjb94** [intercom/intercom-ios#216]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3
  - iOS version: 10.2

## Expected behavior
conversations list should be loaded

## Actual behavior

[Intercom] ERROR - Tried to get conversations for display in the conversations list but there was a network error - Request failed: unauthorized (401)

and never loads conversations list.

it did work at first time when i tested, but after log out, it never worked.

and I removed that user(which i was testing) who occurs error, but the user revives after login. I think sth went wrong in your DB.

## steps i registered my account

1. In my simulator, I registerd with my email.
2. Using the same simulator, I registered with my own app's User ID(which has the same email)
3. Using the same simulator, I did "registerUnidentifiedUser" and sent some messages. after this,  I logged in, which means I registered with my email.
4. I've got my conversations list in STEP 3, but after re-run, it never loads.

**Comment by bboyle18** [comment]
Hi @yjb94 👋 

Thanks for getting in touch.
You're getting a 401 error, so you're having issues authorising with Intercom. Would you be able to send me a snippet of code showing how and where you are setting your AppId and API Key?
Please be careful not to send your actual API Key or App ID for security reasons 👍 

Thanks

Brian

**Comment by yjb94** [comment]
@bboyle18 

this is where i call,
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // ... some other initializes
        //init intercom
        IntercomManager.Instance.setAPI()
        return true
    }
```
and this is the setAPI funciton
```
func setAPI() {
        //initialize
        Intercom.setApiKey(INTERCOM_API_KEY, forAppId: INTERCOM_APP_ID)
        
        #if DEBUG
            Intercom.enableLogging()
        #endif
    }
```

**Comment by bboyle18** [comment]
Thanks for sending that on, it looks ok.
Have you enabled [secure mode](https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enabling-secure-mode-in-intercom-for-ios) for your app? You can find out by checking your iOS settings in Intercom.

Thanks

Brian

**Comment by yjb94** [comment]
@bboyle18 
Thanks..
I just set secure mode to "Disabled" and it kinda worked...

Any ideas to make it work in "Enabled"?

**Comment by bboyle18** [comment]
Hi @yjb94 
To use secure mode in your app you need to follow these steps to configure it properly https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enabling-secure-mode-in-intercom-for-ios

Once you have turned on secure mode and following the above steps, it should work.

Cheers

Brian
