### ISSUE TITLE
Is it possible for me to Test Push Notifications with Resolve(Lite) + Acquire(Lite)?

### ISSUE THREAD

**Issue by yjb94** [intercom/intercom-ios#217]
Is it possible for me to Test Push Notifications with Resolve(Lite) + Acquire(Lite)?

In the tutorials of push notifications, it is written like 

> Step 7: Testing Intercom Push Notifications
> You can easily test if push notifications are working properly in your app. Just send a manual message to the app user via Intercom.

but manual message needs a "engage" account.

is it possible to send push notifications with Resolve account?

## expected

i am replying what the user have send, and i want the reply with push notifications(when app is on background)

## actual

no push notifications background, but can get messages when application is launching.

**Comment by jtreanor** [comment]
Hi @yjb94,

Yes, push notifications will work with Resolve. When you reply to a user's conversation, they will receive a push notification.

If you send a message in through the Messenger on [intercom.com](https://www.intercom.com) we will be able to help you figure out any issues with your integration.

**Comment by yjb94** [comment]
@jtreanor is it possible to get notifications from background? I can't get push notifications outside my application

**Comment by jtreanor** [comment]
@yjb94 Yes, receiving push notifications while your app is backgrounded is supported. If need need help setting this up, feel free to write on on [intercom.com](https://www.intercom.com/)
