### ISSUE TITLE
Missing localisation?

### ISSUE THREAD

**Issue by rpranata** [intercom/intercom-ios#218]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.22
  - iOS version: 10.2

## Expected behavior
All strings displayed in Japanese

## Actual behavior
All strings displayed in English

## Steps to reproduce
 1.  Language is set to Japanese and region is set to Japan (`ja_JP`)
 2. `[Intercom presentMessenger]`

## Logs
_None_

**Comment by jtreanor** [comment]
Hi @rpranata,

In order to use Intercom in Japanese, you must enable that language in your [Intercom settings](https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/localize-intercom-to-work-with-multiple-languages). 
This is so that the Messenger isn't translated into languages which your app isn't/

**Comment by rpranata** [comment]
@jtreanor Thank you. Is the feature not enabled in the `[TEST]` environment? We have enabled the `Japanese` language in the TEST environment but the interface still not showing in Japanese.

![screen shot 2017-02-06 at 10 21 10 1](https://cloud.githubusercontent.com/assets/354678/22630894/37953492-ec56-11e6-8485-693be2586fe6.png)

**Comment by rpranata** [comment]
@jtreanor Even when the `Japanese` language is set as a default language, the messenger interface is still displayed in `English`.

![pasted image at 2017_02_06 11_13 am](https://cloud.githubusercontent.com/assets/354678/22632809/8e24a08a-ec70-11e6-9fea-3d2cf99b97a2.png)

**Comment by rpranata** [comment]
Sorry I finally understand what is going on. Seems like our web app sets a value in the `language_override` that gets used by the iOS App SDK (I finally understand what is going on), sorry for a lot of message. 

I guess that is an intended behaviour?
