### ISSUE TITLE
Carthage issue

### ISSUE THREAD

**Issue by romanmiller** [intercom/intercom-ios#219]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.24
  - XCode version: 8.1
  - Carthage version: 0.17.2

## Expected behavior
successfully loaded framework "intercom-ios" via carthage 

## Actual behavior
loading via carthage freezing terminal and never execute

## Steps to reproduce
 1. place in cartfile github "intercom/intercom-ios"
 2. call command  - carthage update

**Comment by victoraugustolls** [comment]
Having the same problem here! I do use Carthage a lot more when compared to CocoaPods, so it would be nice to have an answer here, and a possible fix!

**Comment by victoraugustolls** [comment]
Carthage manage to output an error when building intercom:

> Dependency "intercom-ios" has no shared framework schemes for any of the platforms: iOS
If you believe this to be an error, please file an issue with the maintainers at https://github.com/intercom/intercom-ios/issues/new

**Comment by jtreanor** [comment]
Hi @romanmiller and @victoraugustolls,

Apologies for the delayed response here. Are you using the `--no-use-binaries` flag? Intercom is distributed as a binary so it will not work with this flag.

See a related issue here: https://github.com/intercom/intercom-ios/issues/221.

**Comment by jtreanor** [comment]
I'm closing this on the assumption that you are using `--no-use-binaries`. If this is not the case, please let us know.
