### ISSUE TITLE
The textfield never appears when the keyboard rises

### ISSUE THREAD

**Issue by JulienLevallois** [intercom/intercom-ios#220]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.24
  - iOS version: 10.0

## Expected behavior

The textfield never appears when the keyboard rises

## Steps to reproduce
 1.  [Intercom presentMessenger];
 2. Open the keyboard to create a new messabe
 3. The textfield never appears 
![image](https://cloud.githubusercontent.com/assets/5727223/22605460/f19277fa-ea1d-11e6-996f-9e9f52c16855.png)
 

## Logs

**Comment by bboyle18** [comment]
Hi @julienlevallois 👋

Can you send a list of the 3rd party libraries you are using please?
Issues like this have occurred in the past when certain 3rd party libs interfere with the inputAccessoryView. Seeing what 3rd party libs you are using might help diagnosing the problem. 

Thanks!

Brian

**Comment by skylerwshaw** [comment]
@JulienLevallois Closing as we don't have the additional information requested 21 days ago. Feel free to message back here if you are still experiencing this, with the additional details. Thanks!
