### ISSUE TITLE
Carthage install: Dependency "intercom-ios" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by TofPlay** [intercom/intercom-ios#221]
## Version info
  - `carthage version`: 1.18.1
  - `xcodebuild -version`: Xcode 8.2.1 Build version 8C1002
  - Are you using `--no-use-binaries`? YES
  - Intercom for iOS version: 3.0.24
  - iOS version: 10.2.0

## Expected behavior
* Build intercom-ios

## Actual behavior
* Generate error: 
```
*** Skipped building intercom-ios due to the error:
Dependency "intercom-ios" has no shared framework schemes for any of the platforms: iOS
```

## Steps to reproduce
 1. Configure `Cartfile` like this:
```
github "intercom/intercom-ios" == 3.0.24
```
 2. Execute `carthage update --platform iOS --no-use-binaries`

## Logs

**Comment by bboyle18** [comment]
Hi @TofPlay 👋 

Intercom.framework is distributed as a binary so the --no-use-binaries flag prevents it from being installed. The error you are seeing is from Carthage attempting and failing to build Intercom itself.

The solution here is to not use --no-use-binaries

Brian

**Comment by TofPlay** [comment]
Hi @bboyle18 I just figure out about --no-use-binaries. I'm checking if I can remove this option. I'm not sure I can work well with other components of my project.

**Comment by bboyle18** [comment]
👍 
Unfortunately the source code for Intercom for iOS is not publicly available so the only option for using it is to use the provided binaries.

Brian

**Comment by goto10** [comment]
In case anyone else runs into this issue as I just have, and has to use --no-use-binaries for other dependencies that you have. 

Run Carthage update with the --no-use-binaries flag and let it build your other dependencies, intercom will fail for now and that's ok. 
Then run: `carthage update intercom-ios`
That will update just the intercom dependency using their pre-build binary.
