### ISSUE TITLE
back

### ISSUE THREAD

**Issue by mkeremkeskin** [intercom/intercom-ios#222]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version:
  - iOS version:

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs

**Comment by bboyle18** [comment]
Hi @mkeremkeskin 👋 
Not sure if you created this issue by mistake?
I'm going to close it, if you have an issues you need help with, feel free to create another one.

Thanks

Brian
