### ISSUE TITLE
How to present View Controller On top of Messenger 

### ISSUE THREAD

**Issue by perlasivakrishna** [intercom/intercom-ios#225]
I have Background thread running in my app, Based on some condition i need to present view modally. 
View is presented correctly if Didn't open the messenger, If i open the messenger, now if my background thread presents modal view controller, Its presenting but all of my view controller subviews background colour is cleared. 

class func topViewController(controller: UIViewController? = UIApplication.shared.keyWindow?.rootViewController) -> UIViewController? {
        if let navigationController = controller as? UINavigationController {
            return topViewController(controller: navigationController.visibleViewController)
        }
        if let tabController = controller as? UITabBarController {
            if let selected = tabController.selectedViewController {
                return topViewController(controller: selected)
            }
        }
        if let presented = controller?.presentedViewController {
            return topViewController(controller: presented)
        }
        return controller
    }

This is how Im getting Top controller of my window. Now in this case, Im getting top controller as 
"ICMSplitViewController", So Im presenting on top of that.
1. Where its going wrong,
2. Is there any way I can know whether messenger is already presented ?

**Comment by bboyle18** [comment]
Hi @perlasivakrishna 👋 
Thanks for getting in touch.
When the Intercom Messenger is displayed, it is the top of all your other views and becomes the keyWindow. Thats why you are having problems when you try to present another modal on top of that.

Its possible to keep track of when the Intercom Messenger is open by listening to the following `NSNotifications`:

`NSNotification.Name.IntercomWindowWillShow`
`NSNotification.Name.IntercomWindowDidShow`

You can then call `Intercom.hideMessenger()` before you present your modal view.

Hope this helps,

Brian

**Comment by perlasivakrishna** [comment]
Can't I present on the top of Messenger ?

**Comment by bboyle18** [comment]
Unfortunately not. The messenger is already presented as a modal so you'll need to dismiss it with `Intercom.hideMessenger()` before you present your own modal.

Brian

**Comment by perlasivakrishna** [comment]
But I tried Presenting, Here is how my controller are normal and on messenger 
![simulator screen shot 10-feb-2017 2 32 27 pm](https://cloud.githubusercontent.com/assets/6779941/22824237/105afa6a-efad-11e6-984c-3c826d8abbb4.png)
![simulator screen shot 10-feb-2017 3 48 05 pm](https://cloud.githubusercontent.com/assets/6779941/22824239/10956100-efad-11e6-920c-5b7ec6c00119.png)

**Comment by bboyle18** [comment]
Have you tried to hide the Intercom Messenger before you presented your view controller?

**Comment by perlasivakrishna** [comment]
No. I don't want to present this view if intercom is presented (or) if my view presents as normal case then no problem ?

**Comment by bboyle18** [comment]
If you don't want to present this view when Intercom is presented, then you will need to keep track of when the Intercom Messenger is shown and hidden. You can use the following `NSNotifications` to keep track of Intercom's visibility.
```
NSNotification.Name.IntercomWindowWillShow
NSNotification.Name.IntercomWindowDidShow
NSNotification.Name.IntercomWindowWillHide
NSNotification.Name.IntercomWindowDidHide
```

Unfortunately you won't be able to show your view on top of Intercom without dismissing the Intercom Messenger first.

Brian

**Comment by perlasivakrishna** [comment]
Ok.I will impelment that, Thnx for helping out.

**Comment by bboyle18** [comment]
No problem 👍

**Comment by adambolcsfoldi** [comment]
Hi, is this still true? Is there no way to a present a view controller on top of the messenger?
