### ISSUE TITLE
SIGSEGV Crash Issue

### ISSUE THREAD

**Issue by siliconprime-hoangho** [intercom/intercom-ios#226]
Hi Dev team, we have seen 1 crash from Intercom framework.

Here's the information:

## Version info
  - Intercom for iOS version: 3.0.18
  - iOS version: 10.0.2
  - Device: iPhone 5S 

## Expected behavior
 App would not crash

## Actual behavior
App crashes

## Steps to reproduce
Unknown

## Logs

Hardware Model:      iPhone 5S (iPhone6,1)

OS Version:      iOS 10.0.2 (14A456)

Exception Type:  SIGSEGV
Crashed Thread:  0

Application Specific Information:
*** Terminating app due to uncaught exception 'SIGSEGV', reason: ''

Thread 0 Crashed:
0   libobjc.A.dylib               0x18be92f30 objc_msgSend + 199049232
1   AppName                0x1004f8fa0 [ICMMetricEvent eventDictionary] + 671804
2   Foundation                    0x18de303a8 [NSObject(NSKeyValueCoding) valueForKey:] + 199049480
3   Foundation                    0x18deeb4d8 [NSSet(NSKeyValueCoding) valueForKey:] + 199049572
4   AppName                0x1004def70 [ICMHTTPBridge submitMetrics] + 672108
5   libdispatch.dylib             0x18c2d1200 _dispatch_call_block_and_release + 199049240
6   libdispatch.dylib             0x18c2d11c0 _dispatch_client_callout + 199049232
7   libdispatch.dylib             0x18c2d5d6c _dispatch_main_queue_callback_4CF + 199050216
8   CoreFoundation                0x18d3f5f2c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 199049228
9   CoreFoundation                0x18d3f3b18 __CFRunLoopRun + 199050876
10  CoreFoundation                0x18d322048 CFRunLoopRunSpecific + 199049660
11  GraphicsServices              0x18eda5198 GSEventRunModal + 199049396
12  UIKit                         0x1932fc628 [UIApplication _run] + 199049900
13  UIKit                         0x1932f7360 UIApplicationMain + 199049424
14  AppName                0x1000d6b70 main (main.m:33)
15                                0x18c3045b8 0 + 6646941112

Thread 1:
0   libsystem_kernel.dylib        0x18c3f816c mach_msg_trap + 199049224
1   CoreFoundation                0x18d3f5cec __CFRunLoopServiceMachPort + 199049408
2   CoreFoundation                0x18d3f3908 __CFRunLoopRun + 199050348
3   CoreFoundation                0x18d322048 CFRunLoopRunSpecific + 199049660
4   Foundation                    0x18de30b1c [NSRunLoop(NSRunLoop) runMode:beforeDate:] + 199049520
5   Foundation                    0x18de5160c [NSRunLoop(NSRunLoop) runUntilDate:] + 199049312
6   UIKit                         0x193c71c7c [UIEventFetcher threadMain] + 199049352
7   Foundation                    0x18df2e50c __NSThread__start__ + 199050240
8   libsystem_pthread.dylib       0x18c4db860 _pthread_body + 199049456
9   libsystem_pthread.dylib       0x18c4db770 _pthread_start + 199049500
10  libsystem_pthread.dylib       0x18c4d8dbc thread_start + 199049220

**Comment by skylerwshaw** [comment]
Hey @siliconprime-hoangho, please let us know if you see this crash again. We'll certainly look into it but it's often difficult to corroborate a single crash.

**Comment by siliconprime-hoangho** [comment]
@skylerwshaw This issue is difficult to reproduce and It just occurs one time on my project.

So I'll close this issue for now and inform you if it happens again.

Thanks
