### ISSUE TITLE
File attachments

### ISSUE THREAD

**Issue by leojkwan** [intercom/intercom-ios#227]
Android SDK allows file attachments, iOS SDK doesn't seem to reflect that. Am I missing a configuration property for the chat messenger api to send file attachments?

**Comment by bboyle18** [comment]
Hi @leojkwan 👋 
Thanks for getting in touch.
iOS doesn't allow file attachments. However, it does allow you to attach photos. To do this, you need to grant access to the device's photo library. You'll need to make sure you have added `"Privacy - Photo Library Usage Description" ` to your `info.plist`.[ Heres instructions](https://developers.intercom.com/docs/ios-installation#section-step-2-update-infoplist) how to do that.

Cheers

Brian

**Comment by jaymjax1** [comment]
@leojkwan Will there ever be a future enhancement to add this functionality?

**Comment by semerda** [comment]
Ditto. Would love to see attachments added to iOS. Timeline?

**Comment by bboyle18** [comment]
@semerda @jaymjax1 👋 
Right now, adding attachments is not on our roadmap. I'll take note of this feature request. 
Thanks!
cc. @patrickjandrews
