### ISSUE TITLE
Intercom.framework fails TestFlight validity checks when integrated with Carthage

### ISSUE THREAD

**Issue by algal** [intercom/intercom-ios#231]
For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.25
  - iOS version: 10.2.1

## Expected behavior

If I follow the README's instructions on how to integrate Intercom via Carthage, and then do a Release build (via Xcode's command Product / Archive), then I should be able to submit the resulting build to Apple's TestFlight service.

## Actual behavior

I can build successfully, but when I submit to TestFlight I get a variety of errors which all concern how the Intercom binary framework was built.

Some errors:
- ERROR ITMS-90087: Unsupported Architectures. This is because the Intercom.framework includes x86_64 and i386 code for the Simulator, but the README provides no instructions on any additional configurations I need to install in order to strip those architectures before submitting.

- ERROR ITMS-90635: Inconsistent Mach-O format within main bundle. This seems to be due to the fact that Intercom.framework was built without bitcode disabled. To use it, it seems I then need to modify the build settings of all my other frameworks so they also disable bitcode. But I do not want to do that and I am not sure I can (e.g., what if one of them is also distributed as a binary?)

- ERROR ITMS-90209: Invalid Segment Alignment. I don't know what this means but Xcode suggests that Intercom.framework was built with an outdated version of Xcode.

- ERROR ITMS-90125: Binary invalid. "Encryption info in LC_ENCRYPTION_INFO load command is either missing of invalid". The error goes on to say it seems like the binary was built not using Apple's linker

- ITMS-90080: Intercom.framework is not a Position Independent Executable.

To summarize, there seem to be at least 4-5 distinct issues here with Intercom.framework, which arose when I tried to integrate Intercom.framework by following the README's instructions. It also seems that all of these issues are a result of the way the Intercom.framework was compiled, and could be resolved if I could just compile the framework myself.

## Steps to reproduce
 1. Create a fresh app from Xcode's default template in Xcode 8.2.1 
 2. Do nothing at all to the app, except to add Intercom via Carthage following the README instructions, and then link and embed Intercom.framework into the app
 3. Submit the app via Xcode.
4. Observe the following collection of 4 error message and 1 warning message

## Logs

<img width="1098" alt="intercomtest" src="https://cloud.githubusercontent.com/assets/264412/23176272/35d0ae08-f817-11e6-8e15-fb6896dbeaed.png">

**Comment by bboyle18** [comment]
Hi @algal 👋 
You might find the answer to your question in [this issue](https://github.com/intercom/intercom-ios/issues/205)

Let me know if this helps you

Brian

**Comment by algal** [comment]
Hurray! Following step 4 in the section "If you're building for iOS, tvOS, or watchOS" of [this document](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application)  did solve the issue.

May I suggest that you might want to update your README.md instructions for Carthage users so that it includes this instruction? Currently, your instructions are incomplete, and there is no pointer to this Carthage incantation, which is a bit unfamiliar since it is only necessary if you're integrating a binary-only framework that includes Simulator architectures.

**Comment by bboyle18** [comment]
Hi @algal 
Glad you got it sorted. We'll take your feedback about our docs on board. 👍 

Brian
