### ISSUE TITLE
Cocoapods install just hangs

### ISSUE THREAD

**Issue by philipengberg** [intercom/intercom-ios#232]
## Version info
  - Intercom for iOS version: `3.0.25`
  - iOS version: `10.2`

## Expected behavior
Running `pod install` just installs the library

## Actual behavior
When installing pods, a lot of data is downloaded when it comes to the Intercom pod, but then it stop fetching and just hangs there until you abort the installation
It has been like that since at least `3.0.22`.
You have to go in and delete the Intercom folder in the Pods folder to get it to install.

## Steps to reproduce
 1. Try to update Intercom from a previous version

**Comment by skylerwshaw** [comment]
Hey @philipengberg, there are two possibilities here:
1. Cocoapods' repo was down earlier today
2. Can you try `pod repo update` followed by `pod install`?

Let us know! -Skyler

**Comment by philipengberg** [comment]
@skylerwshaw This has been going on consistently for at least the past month.

**Comment by skylerwshaw** [comment]
@philipengberg Have you followed the instructions in step 2 and determined the version of Cocoapods installed on your system per #3?

We are unable to reproduce this but if you can share the information requested above, we'd be more than happy to dig further on this. Feel free to respond here, or message using the Intercom in-app messenger from within your Intercom dashboard. You can reference this issue. Thanks!
