### ISSUE TITLE
Receiving Bad requests (400) per action

### ISSUE THREAD

**Issue by Moliholy** [intercom/intercom-ios#233]
I suspect it's due to Apple's App Transport Security policy. There is no way at all to perform any action since I changed my SDK to 9.0. I have tried enabling the following domains in my info.plist without success:

- api.intercom.io
- mobile-sdk-api.intercom.io
- intercom.io
- intercom.com

Any feedback would be very appreciated.

## Version info
  - Intercom for iOS version: 2.3.21
  - iOS version: 9.0

## Expected behavior
Make some networking action

## Actual behavior
Receiving Bad requests (400)

## Steps to reproduce
 1. Any action inside Intercom that requires networking

## Logs
[Intercom] ERROR - Tried to update user attributes but there was a network error - Request failed: bad request (400)
[Intercom] ERROR - Tried to get conversations for display in the conversations list but there was a network error - Request failed: bad request (400)

**Comment by skylerwshaw** [comment]
Hey @Moliholy, happy to look into this with you. 2.3.21 is the old v2 version of our SDK. Can you please update to [3.0.25](https://github.com/intercom/intercom-ios/releases) and see if you are experiencing the same issue? If you find that Cocoapods is only pulling down 2.3.21, ensure that you are targeting iOS 8.x or higher in your podfile. Best, Skyler

**Comment by Moliholy** [comment]
Good morning, and many thanks for the quick reply.

I've just tried updating Intercom to 3.0.25, checked that my target device in the Podfile is 9.0, and still there is no success. Now the logs changed a bit, I guess due to the new version:

[Intercom] ERROR - Tried to update user but there was a network error (400) - Request failed: bad request (400)
[Intercom] ERROR - Tried to get conversations for display in the conversations list but there was a network error (400) - Request failed: bad request (400)

**Comment by Moliholy** [comment]
I forgot to mention a very important detail: In my iphone  emulator it works like a charm, and instead of the mentioned error I get the following:

PAC Fetch failed with error [NSURLErrorDomain:-1022]
nw_proxy_resolver_create_parsed_array PAC evaluation error: NSURLErrorDomain: -1022

**Comment by skylerwshaw** [comment]
@Moliholy Do you have an Intercom account? It would likely expedite resolution if we could chat there in realtime.

**Comment by Moliholy** [comment]
Sure, it's j2uel0wy.

And yes, I could run the version 3.0.25 under the SDK 9.0, but not in the latest (10.2 if I recall correctly).

**Comment by skylerwshaw** [comment]
Resolved. Integration was identifying users by email, where multiple users existed with the same email address and different user_ids. If user_id is used as a unique identifier, it should be sent in all registration calls to protect against these uniqueness constraint errors.
