### ISSUE TITLE
Navigation Bar disappears after closing Intercom messenger.

### ISSUE THREAD

**Issue by Coooi** [intercom/intercom-ios#235]
## Version info
  - Intercom for iOS version:  3.0.18
  - iOS version: 9.0+

## Expected behavior
Intercom messenger should close without affecting other components of the app.

## Actual behavior
All app Navigation bars disappear.
Not sure if they went up, or got hidden.

## Steps to reproduce
@adamkmccarthy I'm facing the same issue after closing the messenger.
Steps to reproduce:

1. Intercom.presentMessenger()
2. Open any conversation.
3. Close the messenger.
4. All navigation controllers disappear.

## Questions:
Do you know if Intercom SDK is modifying UINavigationBar.appearance() ?
By the way, I'm not using IQKeyboardManager library.

**Comment by skylerwshaw** [comment]
Hey @Coooi, can you please update to 3.1.0 just to control for as many variables as possible?

The SDK holds no reference to any UINavigationBar, nor does it affect its appearance. Are there any particularities about how you manage the UINavigationBar in your app?

**Comment by Coooi** [comment]
Ok, just updated and the issue remains.
I can maybe record a video of the flow.

**Comment by bboyle18** [comment]
Hi @Coooi 👋 
A video would be great to help us diagnose this. 👍 
Also if you could provide a list of your 3rd party libs that you are using as well.
Have you customised your UINavigationBar in any way, including setting its appearance? If so can you provide some info about this along with code sample?

If you can provide us with the above it will help us with trying to recreate the issue.

Thanks!

Brian

**Comment by bboyle18** [comment]
Hey @Coooi 
Any update on this issue? We'd love to be able to fix this for you.

Brian

**Comment by skylerwshaw** [comment]
Closing as no response has been received from @Coooi in 22 days. If you're still experiencing this issue, please provide the requested information. Cheers!
