### ISSUE TITLE
I want my app's badge increased when I recieve Push Notification from Intercom

### ISSUE THREAD

**Issue by yjb94** [intercom/intercom-ios#237]
what i am trying to do is "catch the push notification from back/foreground and increase my badge number".
and i've saw in https://docs.intercom.com/configure-intercom-for-your-product-or-site/configure-intercom-for-mobile/enabling-push-notifications-with-intercom-for-ios#step-7-testing-intercom-push-notifications that intercom does not send me badge numbers.

So i was trying to catch the notification sent from intercom. But i couldn't get it done.

both 
`func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) ` 
and 
`func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any])` 
didn't catch notifications from intercom.

How can I handle with push notifications sent from intercom? I mean both of background and foreground.

**Comment by jtreanor** [comment]
Hi @yjb94,

Thanks for writing in with this. I can certainly understand why you would want to do this so we will treat this as a feature request.
Closing the issue as it is a request for a new feature.

Thanks,
James

**Comment by mhemmings** [comment]
@jtreanor Any news on this? We'd absolutely love app icon badges

**Comment by slorber** [comment]
@jtreanor can a workaroud be easily implemented in userland to intercept intercom push and increment the badge?

**Comment by GutteApps** [comment]
Any update on this? We're in the progress of migrating from Smooch and were surprised to find out this feature is missing.

**Comment by yjb94** [comment]
Time has passed but this issue is still on. 

To fix this issue, when I open my app, I managed to get the unreadCount(I don't remember if this name is right). and then I just changed my badge number locally.

This won't fix the background badge number increasing... but should help a bit.
