### ISSUE TITLE
setInAppMessagesVisible displays nothing after logout

### ISSUE THREAD

**Issue by yjb94** [intercom/intercom-ios#238]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.22
  - iOS version: 10.0.2

## Expected behavior

>if conversationCount > 0 {
                    Intercom.setInAppMessagesVisible(self.launcherVisible)
           } else {
                Intercom.setLauncherVisible(self.launcherVisible)
            }
            if self.launcherVisible == false {
                Intercom.setLauncherVisible(false)
            }

this code works well without logout(reset)

## Actual behavior

but after

Intercom.reset()
Intercom.registerUnidentifiedUser()

and register with the same user.
the conversationCount is bigger then 0, but there are no inAppMessages shown.

**Comment by jtreanor** [comment]
Hi @yjb94,

Firstly, can you explain what the intended purpose of the block of code you provided is? You shouldn't need to set in app messages visible manually.

Secondly, it looks like you are not registering with the same user. `Intercom.registerUnidentifiedUser()` creates a new user as you have not provided any identifying information.
If you wish to register with the same user, you can replace your usage of `Intercom.registerUnidentifiedUser()` with `Intercom.registerUser(withUserId: "<#123456#>")`

**Comment by yjb94** [comment]
1. I have to make in app messages invisible in some  cases(etc, in app messages hide my button / camera things). Thus I am using this code.

> 
    public var launcherVisible:Bool = false {
        didSet { 
            if conversationCount > 0 {
                Intercom.setInAppMessagesVisible(self.launcherVisible)
            } else {
                Intercom.setLauncherVisible(self.launcherVisible)
            }
            if self.launcherVisible == false {
                Intercom.setLauncherVisible(false)
            }
        }
    }

which will make in app message visible when conversation exists.


2. I have my own Login logic. I've followed the instructions written and recommended in the Intercom API's tutorial. `Intercom.registerUser(withUserId: "<#USER_ID#>" )` I call this method when user logs in. `Intercom.registerUnidentifiedUser()` this code is just for logged out user.

**Comment by jtreanor** [comment]
@yjb94  In the case of 1, why are you checking the current `conversationCount`? Its possible this could be causing issues.

**Comment by yjb94** [comment]
@jtreanor it's because In app messages appears when conversationcount is bigger than 1. 

But it would be better if intercom provides somethin like  `appMessageCount` or `appMessageExists` or sth else.

**Comment by jtreanor** [comment]
I think you may be slightly misunderstanding the usage of this method. In app messages will never be shown if there are no unread conversations. 

If I am understanding your use case correctly, your code can be changed to this:
```
public var launcherVisible:Bool = false {
    didSet { 
        Intercom.setInAppMessagesVisible(self.launcherVisible)
        Intercom.setLauncherVisible(self.launcherVisible)
    }
}
```

If you are still seeing issues with this it may speed up getting a resolution here by writing in through the Messenger on [https://www.intercom.com](https://www.intercom.com).

**Comment by skylerwshaw** [comment]
@yjb94 Feel free to let us know if you are still experiencing issues around implementing the `setInAppMessagesVisible` functionality. You can comment here or send an Intercom in-app message through your Intercom dashboard.
