### ISSUE TITLE
Can't set language_override to the user's attribute with ICMUserAttributes leading to language inconsistencies

### ISSUE THREAD

**Issue by rpranata** [intercom/intercom-ios#239]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

We have a web and iOS version with a language toggle on the web. The language toggle on the web would set the `language_override` property to the user's property.

Prior to the 3.1.1 version of Intercom SDK, the iOS version needs to re-override using `updateUserWithAttributes` when the user goes back to the app:

```
NSString *language = [NSBundle mainBundle].preferredLocalizations.firstObject.lowercaseString;
[Intercom updateUserWithAttributes:@{ @"language_override": language }];
```

That is needed **ensure** that the language in the Intercom's panel is **consistent** with the language on the device.

Starting [3.1.0](https://github.com/intercom/intercom-ios/releases/tag/3.1.0), the ability of updating user's preference is moved to `ICMUserAttributes`. However, the attributes that can be changed is very limited and that does not include the `language_override` attribute.

So 

## Version info
  - Intercom for iOS version: 3.1.1
  - iOS version: 10.2

## Expected behavior
Either *ignore* the `language_override` sets by the web SDK **or** allow the iOS SDK to set the `language_override` through `ICMUserAttributes`.

## Actual behavior
None of the things above is provided leading to language inconsistencies between Intercom Messenger interface and the rest of the app.

## Steps to reproduce
 1. Have the website version runs on a computer in Japanese language settings. This sets the `language_override` to `ja` and everything in Intercom interface is displayed in Japanese language. 
 2. On the iOS device, have the language setting on the device to English.
 3. Open the messenger app and the UI is displayed in Japanese.

## Logs
None needed

**Comment by jtreanor** [comment]
Thanks for reporting this @rpranata.

We will add `language_override` in the next release. In the meantime you can continue to use the deprecated method.

**Comment by jtreanor** [comment]
`languageOverride` has been added to `ICMUserAttributes` in [3.1.2](https://github.com/intercom/intercom-ios/releases/tag/3.1.2).

Thanks for reporting this 😄
