### ISSUE TITLE
Wrong Intercom window size on iOS 8.x in only portrait mode

### ISSUE THREAD

**Issue by narekam** [intercom/intercom-ios#240]
When we try to open Intercom window from turned to landscape position iOS 8.x device (remembering that current app context implies only Portrait mode) Intercom window open with wrong size. Please see screenshots.

## Version info
  - Intercom for iOS version: 3.0.24
  - iOS version: 8.x

## Expected behavior
Proper size of Intercom window

## Actual behavior
-

## Steps to reproduce
-

## Logs
![simulator screen shot mar 13 2017 12 03 43](https://cloud.githubusercontent.com/assets/13750851/23846292/3bb66c48-07e6-11e7-94b4-51a90f7912f0.png)
![simulator screen shot mar 13 2017 11 58 07](https://cloud.githubusercontent.com/assets/13750851/23846312/52d8eb94-07e6-11e7-951f-0c049034a739.png)

**Comment by bboyle18** [comment]
Hi @narekam 
Apologies for the delay in getting back to you.
I downloaded the current version of Joomag and had a look at how you handle device rotation. It appears that your app does support landscape when reading magazine content but your homescreen/menu does not rotate to landscape. 
I can see that by swiping up to show the iOS Control Center that iOS is actually in landscape mode, but you have overridden the rotation mechanism for the homescreen/menu.

Intercom observe's the rotation state of the foremost ViewController. In this case the ViewController is actually in landscape.

I hope this makes sense. 
Please feel free to reopen the issue if you have any further questions.

Brian
