### ISSUE TITLE
The send button can get locked out

### ISSUE THREAD

**Issue by jmbeck** [intercom/intercom-ios#243]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.1.2
  - iOS version: 10.2.1

## Expected behavior
Message sends when send it tapped.

## Actual behavior
Message is not sent

## Steps to reproduce
 1. Send a message from the phone
 2. Receive reply on the web live chat client
 3. Prepare a response on the phone that includes autocorrect
 4. Send a response from the web
 5. Immediately try to send the message from the phone, once the message from web is received.

https://goo.gl/photos/5t3bwen8tfy1ySZg6

## Logs

**Comment by bboyle18** [comment]
Hi @jmbeck 👋 

Thanks for getting in touch.
Would you be able to provide a little more detail on this issue? If you had a video of whats happening on the device it would help us to understand it a little better.

Thanks

Brian

**Comment by jmbeck** [comment]
Hey @bboyle18,

I included a video, see the google photos link above.

**Comment by bboyle18** [comment]
Thanks @jmbeck! I see it now....that video wasn't auto playing for me so it just looked like a screenshot. Taking a look now 👍

**Comment by jmbeck** [comment]
Yeah it leaves a bit to be desired.  I'll choose a better platform next time.

Thanks, good luck!

**Comment by bboyle18** [comment]
@jmbeck Is this something that you are consistently able to reproduce?

**Comment by jmbeck** [comment]
Oh yeah, many times.  Can you not reproduce it?  I'd say it's about 1 out of every 4 times I try it.

This example in the video is from your intercom-ios example swift project, with no modifications other than adding in they api key and id.

**Comment by bboyle18** [comment]
Works fine for me and haven't seen anything like this reported before.
Does the admin have be to typing like in your video or do you get it when autocomplete pops up normally?

**Comment by jmbeck** [comment]
I just got 6 for 6 to work with no admin messages, so it's only when typing clashes with an incoming message.

**Comment by bboyle18** [comment]
Ok, thanks for that. I'll continue to investigate and get back to you here with any updates.

**Comment by jmbeck** [comment]
And to be clear, although they video shows the admin typing, it actually happens after the admin hits send, and nothing else is being typed on their end.

**Comment by bboyle18** [comment]
Got it thanks. I've managed to recreate it 👍

**Comment by bboyle18** [comment]
@jmbeck This will be fixed in the next release. We'll post an update here when its available.
Thanks again for reporting this.

Brian

**Comment by jmbeck** [comment]
@bboyle18, thanks for your quick action!

**Comment by jtreanor** [comment]
The fix is now included in 3.1.3.

Thanks again for reporting this @jmbeck 😄
