### ISSUE TITLE
App turns white when displaying the Message Composer

### ISSUE THREAD

**Issue by nerdmed** [intercom/intercom-ios#244]
## Version info
  - Intercom for iOS version: 3.1.2
  - iOS version: 10.2

## Expected behavior
The app should be behind the intercom messenger

## Actual behavior
My app turns white as soon as i open the messenger.

![bildschirmfoto 2017-03-27 um 14 35 58](https://cloud.githubusercontent.com/assets/3820220/24356722/71a67058-12fb-11e7-91ec-1ba43bdeb99e.jpg)

The white background becomes visible for a moment when i close the messenger.
Then my app becomes visible again.
My app is displayed via React-Native 0.42

Here is the whitescreen:
![whitescreen](https://cloud.githubusercontent.com/assets/3820220/24356745/87a05342-12fb-11e7-9e42-8b26e67230e8.jpg)

**Comment by jtreanor** [comment]
Hi @nerdmed,

Thanks for sending this in. Does this occur every time you open Intercom or just in some cases (e.g. coming from a push notification)?

**Comment by nerdmed** [comment]
@jtreanor happens everytime

**Comment by jtreanor** [comment]
Thanks @nerdmed. I'll check this out and get back to you here.

**Comment by nerdmed** [comment]
@jtreanor thanks a lot and 👍 for your fast support!!!

**Comment by jtreanor** [comment]
@nerdmed Unfortunately I haven't been able to reproduce this so far. I have tested it in a React Native app with no luck yet.
Can you think of any details of your app that may cause it to behave differently? Perhaps a dependency you are using could be changing the window hierarchy.

**Comment by nerdmed** [comment]
@jtreanor oh ok thats really strange, can you share your example i will try to reproduce it there?

**Comment by jtreanor** [comment]
Sure, here is a simple hello world app that includes Intercom: [react-native-sample.zip](https://github.com/intercom/intercom-ios/files/876193/react-native-sample.zip).

**Comment by nerdmed** [comment]
@jtreanor it just magically disappeared with a react native update. I think this can be closed!

**Comment by jtreanor** [comment]
I'm glad this was resolved for you. If you see the issue again, please let us know 😄

**Comment by nerdmed** [comment]
@jtreanor for sure! Thanks for your excellent support!
