### ISSUE TITLE
IntercomAutoIntegratePushNotifications works only on first run

### ISSUE THREAD

**Issue by alessandroorru** [intercom/intercom-ios#246]
## Version info
  - Intercom for iOS version: 3.1.3
  - iOS version: 10.3

## Expected behavior
`application:didReceiveRemoteNotification:` should get called when using IntercomAutoIntegratePushNotifications. On iOS 10, the user notification center method should get called.

## Actual behavior
The app delegate method gets called only on first run. If after first run I kill the app and open it again, it stops working and doesn't get called, like if IntercomAutoIntegratePushNotifications doesn't take effect and the method is swizzled again.

## Steps to reproduce
 1. Add `IntercomAutoIntegratePushNotifications` to Info.plist, set to NO
 2. Add a breakpoint or log in `application:didReceiveRemoteNotification:`. Launch the app and send a notification. Breakpoint/Log should be called.
 3. Kill the app and open it again. Send a notification. Breakpoint/Log now doesn't get called, but Intercom handles the notification anyway.
 4. This also happens on iOS 10, using the new UNUserNotificationCenterDelegate methods.

I also noticed that regardless of the key, Intercom implementation seems to be called way before that my app manually calls `handlePushNotification` manual method.

**Comment by jtreanor** [comment]
Hi @alessandroorru,

First of all its worth pointing out that manually integrating push notifications is an entirely optional step (see our docs [here](https://developers.intercom.com/docs/ios-push-notifications#section-step-6-handling-intercom-push-notifications)).

Assuming you wish to continue with the manual integration, I have explained what is happening below.

Apple's docs for [`application:didReceiveRemoteNotification:`](https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623117-application) state:

> If the app is running, the app calls this method to process incoming remote notifications.

> If the app is not running when a remote notification arrives, the method launches the app and provides the appropriate information in the launch options dictionary. The app does not call this method to handle that remote notification. Instead, your implementation of the application(_:​will​Finish​Launching​With​Options:​) or application(_:​did​Finish​Launching​With​Options:​) method needs to get the remote notification payload data and respond appropriately.

The easiest solution is to use [`application:did​Receive​Remote​Notification:​fetch​Completion​Handler:`](https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623013-application) instead. Alternatively you can use `UIApplicationLaunchOptionsRemoteNotificationKey` from `launchOptions` in `application:didFinishLaunchingWithOptions:`.

It is also worth noting that `application:didReceiveRemoteNotification:` was deprecated in iOS 10.

Let me know if I can help clarify any of this.

**Comment by jtreanor** [comment]
Apologies, didn't mean to close. I'll leave this open until we confirm there is not an issue.

Quick note about `UserNotifications` on iOS 10; when `IntercomAutoIntegratePushNotifications` is set to `NO`, Intercom does not interfere with this in any way.

**Comment by alessandroorru** [comment]
It is the same using `application:did​Receive​Remote​Notification:​fetch​Completion​Handler:`. If I implement that it gets called instead of the other one, but only on the first app run. Keep in mind that I'm *always* trying it when the app is in foreground. Again:

1) I install the app from scratch, launch it, send a notification: Intercom handles it AND my implementation of the delegate method gets called
2) I close the app, launch it again, send a notification: Intercom handles it BUT my implementation doesn't get call.

Moreover, what I find weird is that when the delegate method gets called, it is called AFTER the intercom popup appears, but in theory the popup should be triggered by my call to `handlePushNotification`.

**Comment by jtreanor** [comment]
Thanks for the detailed response @alessandroorru. I didn't fully understand your original question.

It does sound like the swizzle is happening in your app, although your implementation should always be called, even with swizzling. I'm sure we can get to the bottom of this.

To give you a little more context, here are some snippets showing how this works:

```
- (BOOL)autoIntegratePushNotifications {
    NSNumber *autoIntegrationEnabled = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"IntercomAutoIntegratePushNotifications"];
    if ([autoIntegrationEnabled isKindOfClass:[NSNumber class]]) {
        return [autoIntegrationEnabled boolValue];
    }
    return YES;
}

- (void)swizzlePushNotifications {
    if (![self autoIntegratePushNotifications]) {
        return;
    }
    // Swizzle logic here
}
```

`swizzlePushNotifications` is called on class load to ensure that push notifications are ready to be handled. But as you can see, it will not do anything if auto integration is disabled. It is also called when a device token is set for the first time.

Could you send on the snippet from your `Info.plist` that has the `IntercomAutoIntegratePushNotifications` configuration? Are there multiple bundles in your app?

Do you have any other 3rd party libraries in your app for handling push notifications?

**Comment by alessandroorru** [comment]
Seems like I just found out the solution, but there still seems to be a bug in your code.

Basically, when I open up my app from scratch, the user is always forced to login. Just after the login, I run the following code:

`
Intercom.reset()
Intercom.registerUser(withUserId: user.id, email: user.email)
`

It seems that the reset() call just before the registerUser() creates issues. If I remove that line, everything works as expected. Maybe the reset() call is asynchronous and finishes after the registerUser ?

**Comment by jtreanor** [comment]
Interesting, thanks @alessandroorru.

`Intercom.reset()` is synchronous and should not impact the push notification behaviour. However, we will dig a little deeper into this and update here.

**Comment by alessandroorru** [comment]
Thank you, anyway it is not urgent anymore since I can safely remove that line.

**Comment by alessandroorru** [comment]
I add that if I call reset() right before the initialization of Intercom (so a bit of time before the user logs in), the behavior works as expected. 

The reason why I need to call reset() on launch is that if the user needs to login again I don't want to make them interact with the conversation screen, that otherwise would be automatically opened if the app is launched from the notification.

**Comment by jtreanor** [comment]
Thanks @alessandroorru, this is helpful.

**Comment by levent** [comment]
I have no idea if this is related, so apologies in advance.

When I use the default/automatic Intercom integration ie. I only call:

1. ```Intercom.setApiKey("XXX", forAppId: "AppId")```
2. ```Intercom.registerUserWithUserId(currentUserId)```

If I send a message from app.intercom.io, the messenger pops up "magically".
If I then minimise the app (press the physical home button) and then bring my app back into the foreground, no subsequent messages from app.intercom.io appear.
I have sent messages whilst our app is in the minimised state and once the user has re-focused the app and also if the user has or hasn't interacted with the first conversation from the app.

I raised an issue with support, which they said they had fwd on to dev.

Thanks!

**Comment by bboyle18** [comment]
Hi @alessandroorru 
I'd like to confirm the re-creation steps you specified in [your first message](https://github.com/intercom/intercom-ios/issues/246#issue-219291167).

> 3. Kill the app and open it again. Send a notification. Breakpoint/Log now doesn't get called, but Intercom handles the notification anyway.

Can you tell me what notification are you talking about here.....a push notification or an Intercom in-app notification?

Thanks

Brian

**Comment by bboyle18** [comment]
Hi @levent 
This isn't related to this issue.
Hopefully you got sorted with our support team.

Thanks

Brian

**Comment by alessandroorru** [comment]
@bboyle18 I'd like to intercept ANY kind of notification in the `application:did​Receive​Remote​Notification:​fetch​Completion​Handler:`, and then eventually forward them to Intercom. 
As I said, if I remove the `reset()` call from the following code it works, so on my side this isn't an issue anymore, anyway I believe it is a bug that could impact on other users.

```
Intercom.reset()
Intercom.registerUser(withUserId: user.id, email: user.email)
```

**Comment by bboyle18** [comment]
I understand, but just wanted to confirm that its push notifications you want to intercept.
If your app is open and we send an Intercom in-app notification, this does not pass through `application:did​Receive​Remote​Notification:​fetch​Completion​Handler:`

Brian

**Comment by alessandroorru** [comment]
@bboyle18 this is not true. After I removed the reset() call, that method gets called when I send a push notification from intercom.

**Comment by bboyle18** [comment]
Yep, I'm not talking about push notifications 😄 , but Intercom's own in-apps.
Thanks for the info, I just wanted to clear up any confusion as we investigate. 👍

**Comment by jtreanor** [comment]
Hi @alessandroorru,

I have spent some time thinking more deeply about this issue and I think I know what was happening here:

1. When the app was opened from the push notification Intercom didn't have the swizzle so did not handle it.
2. Since the user was still registered (i.e. not reset), Intercom checked for new messages (and showed the in app pop up).
3. The user logged in and the push payload is finally passed to Intercom. It works, but the chat head was shown early.

I hope this is clear. As a result of this, I think your correction of moving your own `Intercom.reset()` earlier in the launch cycle was the correct thing to do and does not represent a bug in Intercom. I'm happy to re-open this if there is evidence to suggest there .

@levent I believe your issue is unrelated and should be fixed in the latest version.

Cheers,
James

**Comment by jtreanor** [comment]
One more quick note on this for future referernce. Another way to achieve the same thing would be to call `Intercom.setInAppMessagesVisable(false)` when the app launches and then `Intercom.setInAppMessagesVisiable(true)` when login/splash screen is complete.

**Comment by alessandroorru** [comment]
> One more quick note on this for future referernce. Another way to achieve the same thing would be to call Intercom.setInAppMessagesVisable(false) when the app launches and then Intercom.setInAppMessagesVisiable(true) when login/splash screen is complete.

@jtreanor using this method, what happens if I tap on a notification while the app is in background? would the app move to foreground showing the conversation?

**Comment by alessandroorru** [comment]
> When the app was opened from the push notification Intercom didn't have the swizzle so did not handle it.

This isn't the behavior I described. The first launch of the app wasn't through a tap on a notification.

The behavior (prior the reset() move) was:
- Manually launch the app, and THEN, while the app is in foreground, receive a notification. This would cause the app delegate method to be called
- Kill the app, open it again manually, and then send another notification. This will not call the app delegate method.

**Comment by jtreanor** [comment]
> @jtreanor using this method, what happens if I tap on a notification while the app is in background? would the app move to foreground showing the conversation?

Since you have `IntercomAutoIntegratePushNotifications` set to `NO`, if you call `Intercom.handlePushNotification()` it will show the conversation, but otherwise it will not.

> The behavior (prior the reset() move) was:
>
> - Manually launch the app, and THEN, while the app is in foreground, receive a notification. This would cause the app delegate method to be called
> - Kill the app, open it again manually, and then send another notification. This will not call the app delegate method.

I think I may have slightly misunderstood you but the answer above should still be relevant and I can explain what is happening here.

Push notification handling is designed only for those cases where the app is opened from a push notification. When the app is running in the foreground, new messages are received and displayed by Intercom automatically (these are what we can in app messages). Calling `Intercom.setInAppMessagesVisible(false)` will stop any of these messages from being displayed as they are received. Subsequently calling `Intercom.setInAppMessagesVisible(true)` tells Intercom it can display new messages again, including any messages received while they were hidden.

Does this make sense? Let me know if I can clarify anything.

**Comment by alessandroorru** [comment]
This makes more sense. Anyway, I think it is a lack of the SDK and/or of the documentation if using `IntercomAutoIntegratePushNotifications` set to `NO` I get a different behavior depending on the app being in background or in foreground.

I would expect that the notification calls `application:did​Receive​Remote​Notification:​` in both cases, and Intercom should simply ignore the `Intercom.handlePushNotification()` call if that notification is already treated. IMHO, swizzling a method should be a way to intercept a call but forward it *anyway* to the method that was expected to be called.

**Comment by jtreanor** [comment]
This is great feedback. You're absolutely right; the documentation should be much clear on this.

> I'd rather prefer that IntercomAutoIntegratePushNotifications to NO involves no swizzling at all, relying on the developers implementation to integrate it as they want.

I know its a little confusing but it is already the case that if `IntercomAutoIntegratePushNotifications` is set to `NO`, Intercom does absolutely no swizzling. Messages are just received by other means (i.e. not via push notifications) when the app is open. In fact, if the user has the app open, no push notification will be sent.
