### ISSUE TITLE
setApi risks deadlock by invoking NSNotification in class initialize method

### ISSUE THREAD

**Issue by algal** [intercom/intercom-ios#252]
## Version info
  - Intercom for iOS version: 3.1.2
  - iOS version: 10.3.1

## Expected behavior

I expect to be able to call `Intercom.set(apiKey,appId)` from a background thread safely in `didFinishLaunching`.

## Actual behavior

I am experiencing occasional deadlocks that hang the main thread on launch, and cause watchdog to kill the app. The crash log shows that many different system which use NSNotification center are blocked trying to post a notification, and/or that they are blocked waiting for another class to finish calling the class method `initialize`.

These logs also all show that the Intercom class ICBMBridge is calling Notification Center from in its `+[ICMBridge initialize]`.

`initialize` offers subtle exclusion guarantees that can lead to deadlock: 

http://www.mail-archive.com/cocoa-dev@lists.apple.com/msg106988.html

I cannot be sure, but my best guess as to what is happening is that Intercom is doing complex work in `initialize`, involving NSNotifications, and that this is deadlocking with other systems that want to run at launch time.

## Steps to reproduce

I cannot reproduce this consistently.

## Logs

I attach one sample crash log. There are others just 
[BespokeApp  4-24-17, 2-35 PM - Eric iPhone - launch crash.crash.zip](https://github.com/intercom/intercom-ios/files/962491/BespokeApp.4-24-17.2-35.PM.-.Eric.iPhone.-.launch.crash.crash.zip)

like it.

**Comment by jtreanor** [comment]
Hi @algal,

Thanks for the detailed write up.
Your analysis is correct; `[ICMBridge initialize]` does reference `NSNotificationCenter` in order to observe `UIApplicationDidBecomeActiveNotification` so that Intercom can record sessions correctly.

We will get this fixed in an upcoming release.

**Comment by algal** [comment]
Great to hear it! For what it's worth, my workaround for this issue right now has been to call `Intercom.setApiKey(_:forAppId:)` very early in `didFinishLaunching` (its the first thing after Crashlytics) and on the main thread.

My hope is that then it completes all its synchronous setup before other services start, so that it does not need to be able to run concurrently with them. This seems to be working, because I haven't seen any of these launch crashes since making this change.

However, what seems bad about this workaround is that I may be moving networking onto the main thread, if `Intercom.setApiKey(_:forAppId:)` does synchronous networking as part of its setup. This would slow down launch in bad network environments. 

Can you tell me if `Intercom.setApiKey(_:forAppId:)` does synchronous networking on the calling thread? Or does that function internally dispatch the networking to another thread?

**Comment by jtreanor** [comment]
@algal There is no synchronous networking in `Intercom.setApiKey(_:forAppId:)` or any other Intercom method. All networking is dispatched to an appropriate thread using `NSURLSession`.

The work done by `Intercom.setApiKey(_:forAppId:)` and `+[ICMBridge initialize]` is very small. However, I agree that it should be possible to call from a background thread so this will be resolved in the next release.

**Comment by jtreanor** [comment]
@algal 3.2.1 now observes `NSNotificationCenter` asynchronously, so this deadlock issue is resolved.

Thanks again for the clear and detailed report.
