### ISSUE TITLE
Update user image

### ISSUE THREAD

**Issue by vitormf** [intercom/intercom-ios#255]
Hi,

Using a previous version of Intercom I was able to update the user avatar image using the code:

    NSDictionary *attributes = @{
                                 @"name": name,
                                 @"user_id":userid,
                                 @"avatar", @{@"type":@"avatar", @"image_url":avatarUrl}
                                 };
    
    [Intercom updateUserWithAttributes:attributes];

Since this has been deprecated, I was expecting to achieve the same using:

    ICMUserAttributes *attrs = [[ICMUserAttributes alloc] init];
    attrs.name = name;
    attrs.userId = userid;
    attrs.customAttributes = @{@"avatar", @{@"type":@"avatar", @"image_url":avatarUrl}}
    
    [Intercom updateUser:attrs];

But this lead to the log error message: ERROR - Each value in 'customAttributes' must be of type NSString, NSNumber or NSNull

Is there any other way to update the user avatar image or is this no longer possible?

## Version info
  - Intercom for iOS version: 3.2.0
  - iOS version: Any

## Expected behavior
Update avatar

## Actual behavior
Log message error

## Steps to reproduce
Not applicable

## Logs
[Intercom] ERROR - Each value in 'customAttributes' must be of type NSString, NSNumber or NSNull

**Comment by DaleCantwell** [comment]
Hi @vitormf, thanks for getting in touch.
The ability to set a user avatar in Intercom was not fully supported. While it technically worked that could change at any moment which would break that functionality. When we added ICMUserAttributes we wanted to only provide methods that we had a strong contract between the mobile client and our API.
We aren't currently working on setting user avatars so I don't think we will be adding this feature for some time. I'm going to bring this feature request to the team to see if we can this on our roadmap though.
