### ISSUE TITLE
iOS Framework versions since 3.2.2 compiled without full bitcode support

### ISSUE THREAD

**Issue by pocketsevens** [intercom/intercom-ios#260]
Intercom iOS framework is installed through Carthage. When using the latest version (3.2.4), the app will build for simulator and local devices fine, but during an Archive (for distribution to App Store) the build fails with a linker error:

`ld: bitcode bundle could not be generated because '<path to code>/Carthage/Build/iOS/Intercom.framework/Intercom' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

Indicating that the pre-built framework installed by Carthage was not built with full bitcode support. Forcing an install of version 3.2.1 works fine.

## Version info
  - Intercom for iOS version: 3.2.2 - 3.2.4
  - iOS version: 10.0

## Expected behavior
Archive build should succeed.

## Actual behavior
Archive build fails with linker error message: `bitcode bundle could not be generated because '<path to code>/Carthage/Build/iOS/Intercom.framework/Intercom' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

## Steps to reproduce
 1. Install intercom-ios framework through Carthage
 2. In Xcode, Product > Archive
 3. See error message as above

## Logs
[Archive HourStack_2017-05-24T12-01-41.pdf](https://github.com/intercom/intercom-ios/files/1026618/Archive.HourStack_2017-05-24T12-01-41.pdf)

**Comment by jtreanor** [comment]
Hi @pocketsevens,

Thanks for reporting this. 3.2.2 was the first version to be built with Xcode 8.3.x. I'll keep you updated as we look into this.

James

**Comment by jtreanor** [comment]
@pocketsevens Can you confirm that you are using the latest version of Xcode (8.3.1) to build the archive?

**Comment by pocketsevens** [comment]
@jtreanor I am using Xcode 8.3.2.

**Comment by jtreanor** [comment]
Thanks @pocketsevens. Apologies for the typo above. 8.3.2 is the correct version.

I'll look into this and get back to you.

**Comment by jtreanor** [comment]
This has now been fixed in [3.2.5](https://github.com/intercom/intercom-ios/releases/tag/3.2.5). Thanks again for reporting this.

**Comment by pocketsevens** [comment]
Confirmed fixed. Thank you for the speedy turnaround!
