### ISSUE TITLE
PodIntercom_IntercomConversationCollectionViewController  index beyond bounds

### ISSUE THREAD

**Issue by samratshekhar** [intercom/intercom-ios#266]
Hi, 

We received the following crash report in our production app: 

Fatal Exception: NSRangeException
0  CoreFoundation                 0x1918cefe0 __exceptionPreprocess
1  libobjc.A.dylib                0x190330538 objc_exception_throw
2  CoreFoundation                 0x1917ad200 -[__NSArrayM removeObjectAtIndex:]
3  qplum                          0x100271ce0 -[PodIntercom_IntercomConversationCollectionViewController collectionView:cellForItemAtIndexPath:]
4  UIKit                          0x1982fa318 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:]
5  UIKit                          0x197a607ac -[UICollectionView _updateVisibleCellsNow:]
6  UIKit                          0x197a5b3d4 -[UICollectionView layoutSubviews]
7  UIKit                          0x1979fd07c -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
8  QuartzCore                     0x194bed274 -[CALayer layoutSublayers]
9  QuartzCore                     0x194be1de8 CA::Layer::layout_if_needed(CA::Transaction*)
10 UIKit                          0x197a11814 -[UIView(Hierarchy) layoutBelowIfNeeded]
11 UIKit                          0x19830e960 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:]
12 UIKit                          0x19830e84c -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:]
13 UIKit                          0x19830e7d0 -[UICollectionView _performBatchUpdates:completion:invalidationContext:]
14 UIKit                          0x197bd648c -[UICollectionView performBatchUpdates:completion:]
15 qplum                          0x10026d7dc -[PodIntercom_IntercomConversationCollectionViewController performBatchUpdates:completion:]
16 qplum                          0x10026fc60 -[PodIntercom_IntercomConversationCollectionViewController removeConversationPart:]
17 qplum                          0x1001eb4a0 -[ICMConversationViewController removeAllTypingParts:]
18 Foundation                     0x1923c3770 __NSFireTimer
19 CoreFoundation                 0x19187daa4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
20 CoreFoundation                 0x19187d7a8 __CFRunLoopDoTimer
21 CoreFoundation                 0x19187d068 __CFRunLoopDoTimers
22 CoreFoundation                 0x19187ac8c __CFRunLoopRun
23 CoreFoundation                 0x1917aada4 CFRunLoopRunSpecific
24 GraphicsServices               0x193214074 GSEventRunModal
25 UIKit                          0x197a65058 UIApplicationMain
26 qplum                          0x1000f71f8 main (main.m:16)
27 libdyld.dylib                  0x1907b959c start

Intercom pod version - 3.0.18
iOS version - 10.3.2

Any help is much appreciated!

**Comment by skylerwshaw** [comment]
@samratshekhar Thank you for the report here. We're digging into potential causes and will update this thread once we have some more information. Do you have device info, frequency per user, and quantity of users affected?

**Comment by jtreanor** [comment]
This is the same issue as https://github.com/intercom/intercom-ios/issues/265. I am closing this so we can track it in one place.
