### ISSUE TITLE
-[ICMWindow setFullscreen:] crash

### ISSUE THREAD

**Issue by rokgregoric** [intercom/intercom-ios#267]
## Version info
  - Intercom for iOS version: 3.2.4
  - iOS version: 10 & 9

## Logs
[issue_100_crash_8173d771e3d64a518e35b8f1f5195be7_f0449c82505511e791dd56847afe9799_0_v2.txt](https://github.com/intercom/intercom-ios/files/1072864/issue_100_crash_8173d771e3d64a518e35b8f1f5195be7_f0449c82505511e791dd56847afe9799_0_v2.txt)

The app is crashing when calling `UIViewController.switchRoot(to : UIViewController)`. Here is the code:
```swift
extension UIViewController {
    static func switchRoot(to vc: UIViewController) {
        let window = UIApplication.shared.keyWindow
        // always dismiss all child controllers otherwise they are retained by the view hierarchy
        window?.rootViewController?.dismiss(animated: false)

        window?.rootViewController = vc
    }
}
```

I think that `UIApplication.shared.keyWindow` should always be my app's window (if Intercom UI is not on screen of course).

**Comment by rokgregoric** [comment]
I am unable to replicate this issue .. but I am seeing this crashing a lot:
<img width="997" alt="screenshot 2017-06-13 23 02 46" src="https://user-images.githubusercontent.com/168918/27104493-c9848b24-508c-11e7-9e89-17280ed37ed3.png">

**Comment by jtreanor** [comment]
Hi @rokgregoric,

Thanks for sending this in. It looks like you may be inadvertently setting the `rootViewController` on Intercom's window and subsequently causing undefined behaviour. Intercom's window is the key window when the Messenger is open.

Changing your snippet to this should help avoid the issue:

```
extension UIViewController {
    static func switchRoot(to vc: UIViewController) {
        let window = self.view.window
        // always dismiss all child controllers otherwise they are retained by the view hierarchy
        window?.rootViewController?.dismiss(animated: false)

        window?.rootViewController = vc
    }
}
```

This ensures the code will apply only to your app's primary window.

**Comment by rokgregoric** [comment]
No .. that's no what I need .. and intercom is not opened when I call `switchRoot`:
```swift
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Intercom
        IntercomManager.shared.start()

        DispatchQueue.main.async() {
            UIViewController.switchRoot(to: <#some vc#>)
        }
        return true
    }
```

**Comment by jtreanor** [comment]
@rokgregoric Would you mind sharing a link to the full Crashlytics crash report? If you would prefer not to post it here, feel free to send it in through the Messenger on [intercom.com](https://intercom.com).

**Comment by rokgregoric** [comment]
Its attached in the issue.

**Comment by jtreanor** [comment]
I have looked a little closer at the crash report and it looks like `rootViewController` is being set on Intercom's window. Here is the key portion of the crash report:

```
Fatal Exception: ICMWindowException
0  CoreFoundation                 0x19099afe0 __exceptionPreprocess
1  libobjc.A.dylib                0x18f3fc538 objc_exception_throw
2  MyApp                             0x10027c148 -[ICMWindow setFullscreen:]
3  MyApp                             0x100170ed4 specialized static UIViewController.switchRoot(to : UIViewController) -> () (UIViewControllerExtensions.swift:38)
4  MyApp                             0x1000b0d5c specialized static MainScreenSelector.showLaunchScreen() -> () (MainScreenSelector.swift)
```

The exception that was thrown was `ICMWindowException`. This only exists in one place. Here is the code:

```
- (void)setRootViewController:(ICMRootViewController *)rootViewController {
    @throw [NSException exceptionWithName:@"ICMWindowException"
                                   reason:@"Tried to set rootViewController on Intercom's window. You probably meant to do this on your app's window. Try using UIApplication.shared.delegate?.window or [UIApplication sharedApplication].delegate.window instead."
                                 userInfo:nil];
}
```

An exception is thrown here (and the crash) because setting the `rootViewController` unintentionally will cause many things to break, both in Intercom, and in the host app.

I understand from your previous reply that you don't believe Intercom is on screen when `MainScreenSelector.showLaunchScreen()` is called. This assumption is not necessarily a safe one. For example, if the user has just received an Intercom message, the window will be on screen and the wrong window will be modified.

I hope this makes sense. Let me know if I can clarify any details.

Cheers,
James

**Comment by rokgregoric** [comment]
ok .. it's a bit weird .. cause it happens even before 
```swift
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
```
returns .. but anyway .. now that I understand where's the problem .. I can try to fix it in my code.

Thanks for the help!

**Comment by iShavgula-TacTill** [comment]
@rokgregoric how did it go ? Did you manage to resolve the crash ? I'm having the same issue.

Thanks,
George
