### ISSUE TITLE
Localization strings aren't correctly appear from bundle

### ISSUE THREAD

**Issue by HaspinderSingh** [intercom/intercom-ios#269]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.2.6
  - iOS version: 10.3

## Expected behavior
When calling Intercom.setLauncherVisible(true) the messenger should appear correctly.

## Actual behavior
You can get correct from screenshot . 
After Intercom.setLauncherVisible(true) is called, the messenger appears but strings aren't show according to locale, disturb UI and with 'placeholder' text (like 'navbar.title.conversations'). 

## Steps to reproduce
 1. Install Intercom with Cocoapods through terminal to xcode 
 2. Open messager

## Logs
No Logs
![simulator screen shot 16-jun-2017 11 12 45 pm](https://user-images.githubusercontent.com/29488837/27239534-f7f811d8-52ee-11e7-92f9-4bcfe3fd4027.png)

**Comment by jtreanor** [comment]
Hi @HaspinderSingh,

It looks like the strings bundle is not loading correctly in your app. What version of CocoaPods are you using?

Running these commands may help:
```
pod deintegrate
pod install
```

**Comment by HaspinderSingh** [comment]
I tried both following commands, but nothing is useful.

pod deintegrate
pod install

I am using 1.2.1 version of cocoaPods, actually I install intercom with one more project and it work perfectly with that but I have this problem with one specified project and it is very frustrating. Please help

**Comment by jtreanor** [comment]
@HaspinderSingh Do you have any custom code in your app for loading localization strings? Since images are loading correctly, it looks like bundles are loaded but the strings are not read.

What language is this device using?

It may also be helpful to share your Podfile for this app.

**Comment by HaspinderSingh** [comment]
Hey @jtreanor, Project using localization and for load strings I'm using SwiftGen (https://github.com/SwiftGen/SwiftGen) that creates enum from localization strings file. But I think it should not affect the intercom. 

Currently app language is English ("en"). I am going to share podfile with you.Please check and let me know if you need something more.
Podfile link 
[https://www.dropbox.com/s/pdia5m9x3s8fk2j/Podfile?dl=0](https://www.dropbox.com/s/pdia5m9x3s8fk2j/Podfile?dl=0)

**Comment by jtreanor** [comment]
Thanks @HaspinderSingh. I don't see any obvious issues with either of those.

We have seen this issue before with apps that swizzled `NSBundle`. It is unlikely that you are doing this, but its worth checking.

**Comment by DaleCantwell** [comment]
@HaspinderSingh I haven't been able to reproduce this issue locally. James suggested checking if you swizzle NSBundle in your app, was that the case?
I'm going to close out this issue for now but write back if you are still encountering it or have any additional information that we could use to try reproduce this locally.
Thanks,
Dale
