### ISSUE TITLE
Updating 'signedUpAt' creates custom attribute instead of updating 'Signed Up'

### ISSUE THREAD

**Issue by adambolcsfoldi** [intercom/intercom-ios#270]
## Version info
  - Intercom for iOS version: 3.2.6
  - iOS version: 10.3 (Simulator)

## Expected behavior

Calling `[Intercom updateUser:userAttributes]` where `userAttributes.signedUpAt` has been set to a valid `NSDate`,  should update the **SIGNED UP** date of the corresponding user.

## Actual behavior

Calling `[Intercom updateUser:userAttributes]` where `userAttributes.signedUpAt` has been set to a valid `NSDate` instead updates  a custom **SIGNED_UP_AT** attribute.

## Steps to reproduce

```
      ICMUserAttributes *userAttributes = [ICMUserAttributes new];
       userAttributes.signedUpAt = [NSDate new];
      [Intercom updateUser:userAttributes];
```

## Logs

The `userAttributes` object passed

```
(lldb) po userAttributes.attributes
{
    "signed_up_at" = "1437318870.988";
}
```

The attribute discrepancy. I'm intending to update the top attribute, instead the bottom one is created.

![screen shot 2017-06-23 at 11 58 46](https://user-images.githubusercontent.com/8832515/27477514-ceb05d3a-580c-11e7-9102-f4f7a52a53f8.png)

**Comment by bboyle18** [comment]
Hi @adambolcsfoldi 👋 
Thanks for getting in touch and highlighting this issue. 
You are correct in your observation. Its an issue with our API and we are working to resolve it. 
I'll post an update here when its fixed.

Cheers

Brian

**Comment by bblackbelt** [comment]
@bboyle18, FYI - the same applies to Android. Could you give us an ETA of the fix ?
thanks

**Comment by bboyle18** [comment]
Hi @bblackbelt 👋 
We're working on a fix at the moment.

Brian

**Comment by bboyle18** [comment]
Hi @adambolcsfoldi  and @bblackbelt 

This is now fixed in our API so should be working on iOS and Android.
Thanks again for reporting this.
Cheers

Brian

**Comment by bblackbelt** [comment]
@bboyle18 thanks for letting us know.
Best
