### ISSUE TITLE
PodIntercom_IntercomConversationCollectionViewController collectionView:cellForItemAtIndexPath:

### ISSUE THREAD

**Issue by cayde-6** [intercom/intercom-ios#274]
Hello. We received the following crash report in our production app.

Device info:
OS Version: 10.3.2
Device: iPhone 6s Plus
RAM Free: 7%
Disk Free: 2.7%

1 user, 1 device, 1 count

Crash info:
Fatal Exception: NSRangeException
0  CoreFoundation                 0x189402fe0 __exceptionPreprocess
1  libobjc.A.dylib                    0x187e64538 objc_exception_throw
2  CoreFoundation                0x1892e1200 -[__NSArrayM removeObjectAtIndex:]
3  "%appname%"                       0x100319890 -[PodIntercom_IntercomConversationCollectionViewController collectionView:cellForItemAtIndexPath:]
4  UIKit                          0x18fe2e318 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:]
5  UIKit                          0x18f5947ac -[UICollectionView _updateVisibleCellsNow:]
6  UIKit                          0x18f58f3d4 -[UICollectionView layoutSubviews]
7  UIKit                          0x18f53107c -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
8  QuartzCore                     0x18c721274 -[CALayer layoutSublayers]
9  QuartzCore                     0x18c715de8 CA::Layer::layout_if_needed(CA::Transaction*)
10 UIKit                          0x18f545814 -[UIView(Hierarchy) layoutBelowIfNeeded]
11 UIKit                          0x18fe42960 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:]
12 UIKit                          0x18fe4284c -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:]
13 UIKit                          0x18fe427d0 -[UICollectionView _performBatchUpdates:completion:invalidationContext:]
14 UIKit                          0x18f70a48c -[UICollectionView performBatchUpdates:completion:]
15 "%appname%"              0x10031531c -[PodIntercom_IntercomConversationCollectionViewController performBatchUpdates:completion:]
16 "%appname%" 0x100317810 -[PodIntercom_IntercomConversationCollectionViewController removeConversationPart:]
17  "%appname%" 0x1002be998 -[ICMNativeConversationContentViewController removeAllTypingParts:]
18 Foundation                     0x189ef7770 __NSFireTimer
19 CoreFoundation                 0x1893b1aa4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
20 CoreFoundation                 0x1893b17a8 __CFRunLoopDoTimer
21 CoreFoundation                 0x1893b1068 __CFRunLoopDoTimers
22 CoreFoundation                 0x1893aec8c __CFRunLoopRun
23 CoreFoundation                 0x1892deda4 CFRunLoopRunSpecific
24 GraphicsServices               0x18ad48074 GSEventRunModal
25 UIKit                          0x18f599058 UIApplicationMain
26 "%appname%" 0x10002aee8 main (main.m:59)
27 libdyld.dylib                  0x1882ed59c start

**Comment by jtreanor** [comment]
Hi @cayde-6,

Thanks for reporting this. The crash is already being tracked in https://github.com/intercom/intercom-ios/issues/265 so I will close this issue.
We have done quite a bit of work to track this down and believe we have made progress in 3.2.7.

Cheers,
James
