### ISSUE TITLE
On logout anonymous user have all the events from the logged in user

### ISSUE THREAD

**Issue by salah-ghanim** [intercom/intercom-ios#276]
## Version info
  - Intercom for iOS version: 3.2.8
  - iOS version: 10.3.2

## Expected behavior
Anonymous user shouldn't have anything attached to him from the previous user's behaviour
## Actual behavior
Anonymous user have all events for the previously logged in user.
## Steps to reproduce
 1. login with a user
 2. log some events
 3. log out
 4. register an anonymous

OBS: the new anonymous user in intercom dashboard have the same events the user did before him.

**Comment by bboyle18** [comment]
Hi @salah-ghanim 

Thanks for reporting this. We'll investigate this and get back to you.

Cheers

Brian

**Comment by jtreanor** [comment]
This has been fixed in [3.2.9](https://github.com/intercom/intercom-ios/releases/tag/3.2.9). Thanks again for reporting this @salah-ghanim 😄
