### ISSUE TITLE
setUserHash: doesn't replace old hmac for the respective user. Calling reset doesn't delete cached hmac's

### ISSUE THREAD

**Issue by potecuta** [intercom/intercom-ios#279]
When the hmac for a user is changed, calling setUserHash: or setHmac:ForUser: doesn't replace the old value for a user. If a hmac is registered for a new user, then it works.

The tests I've done: 
1) I first register a user with the wrong hmac and the registering fails as expected. Then I register the correct hmac for the same user, but the request still fails. 
2) I also did the other way around. Registered the correct hmac for a user and the request works, then registered the dummy hmac for the same user, and instead of failing, the request still used the first hmac and succeeded.

Also calling reset does nothing regarding this.

##Version  - Intercom for iOS version: 3.2.0 and 3.2.8
                   - iOS version: 10.2, 20.3.2

## Expected behavior
When calling setUserHash: the old hmac for the respective user should be replaced

## Actual behavior
The hmac doesn't get replaced

## Steps to reproduce
 1.  Fresh Install
 2. Call setUserHash: with a dummy hmac
 3. Register User (the request fails)
 4. Restart application or logout user and call reset (it doesn't really matter)
 5. Call setUserHash: with correct hmac -> The request still fails

I can also offer through a private channel a video demonstrating the steps and how to reproduce

**Comment by bboyle18** [comment]
Hi @potecuta 👋 

It would be great if you could contact us via Intercom so that you can send us a video of you reproducing this. If you could also send logs showing the request failure that would be great too.
Please reference this issue when you chatting with our support engineers.

Cheers

Brian

**Comment by potecuta** [comment]
Well I already talked via Intercom and sent the video. I talked with Kevin but I didn't receive a response since Thursday and since this is affecting a build in production I tried contacting the developers directly through github. You can find the conversation by my email: tudor.carare@gmail.com

**Comment by bboyle18** [comment]
Thanks @potecuta and apologies for the delay.
I'll get @skylerwshaw to contact you this morning.

Brian

**Comment by potecuta** [comment]
I also think this is related to this issue: https://github.com/intercom/intercom-ios/issues/276.

Thanks a lot for the quick response :D

**Comment by jtreanor** [comment]
This has been fixed in [3.2.10](https://github.com/intercom/intercom-ios/releases/tag/3.2.10).
