### ISSUE TITLE
Text container does not resizing for pre-filled text

### ISSUE THREAD

**Issue by siberianisaev** [intercom/intercom-ios#281]
## Version info
  - Intercom (3.2.9)
  - all iOS versions

## Expected behavior

SDK should resize text container height when pre-filled message opened.

## Actual behavior

When user write message the text container height is increasing up to some max height.
But for pre-filled message, text container height is minimal on message opening. 
Need to press "return" key to force it resizing.

## Steps to reproduce
 1. Intercom.presentMessageComposer(withInitialMessage: "1\n2\n3\n4\n5\n6")

**Comment by bboyle18** [comment]
Hi @siberianisaev 👋 

Thanks for highlighting this issue. We are aware of it and plan to implement a fix in a future release.

Cheers

Brian

**Comment by jtreanor** [comment]
This has been fixed in 4.0.3. Thanks again for reporting it 😄
