### ISSUE TITLE
-[ICMChatHeadViewController titleTextForMessageFromAdmin:inConversation:] crash

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-ios#283]
# Date: 2017-07-12T15:05:00Z
# OS Version: 10.3.2 (14F89)
# Device: iPhone 6

#0. Crashed: com.twitter.crashlytics.ios.exception
0  PrintOSMobile                  0x1001b1388 CLSProcessRecordAllThreads + 4297085832
1  PrintOSMobile                  0x1001b1388 CLSProcessRecordAllThreads + 4297085832
2  PrintOSMobile                  0x1001b17a8 CLSProcessRecordAllThreads + 4297086888
3  PrintOSMobile                  0x1001a245c CLSHandler + 4297024604
4  PrintOSMobile                  0x1001afaa0 __CLSExceptionRecord_block_invoke + 4297079456
5  libdispatch.dylib              0x181ca69a0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x181cb3ee0 _dispatch_barrier_sync_f_invoke + 84
7  PrintOSMobile                  0x1001af54c CLSExceptionRecord + 4297078092
8  PrintOSMobile                  0x1001af388 CLSExceptionRecordNSException + 4297077640
9  PrintOSMobile                  0x1001aefe8 CLSTerminateHandler() + 4297076712
10 libc++abi.dylib                0x18183f5d4 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x18183eef8 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 134
12 libobjc.A.dylib                0x18185066c _objc_exception_destructor(void*) + 362
13 CoreFoundation                 0x182cd59b4 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 364
14 CoreFoundation                 0x182cd5824 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 64
15 PrintOSMobile                  0x1002a5fc0 -[ICMChatHeadViewController titleTextForMessageFromAdmin:inConversation:] + 4298088384
16 PrintOSMobile                  0x1002a53f0 -[ICMChatHeadViewController viewDidLoad] + 4298085360
17 UIKit                          0x188f1fec0 -[UIViewController loadViewIfRequired] + 1036
18 UIKit                          0x188f1fa9c -[UIViewController view] + 28
19 PrintOSMobile                  0x1002d35e8 -[ICMInAppsViewController updateSnippetsInApp:] + 4298274280
20 PrintOSMobile                  0x1002d32ac __55-[ICMInAppsViewController setConversations:completion:]_block_invoke + 4298273452
21 libdispatch.dylib              0x181ca69e0 _dispatch_call_block_and_release + 24
22 libdispatch.dylib              0x181ca69a0 _dispatch_client_callout + 16
23 libdispatch.dylib              0x181cab5e8 _dispatch_main_queue_callback_4CF + 996
24 CoreFoundation                 0x182d9d0c8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
25 CoreFoundation                 0x182d9ace4 __CFRunLoopRun + 1572
26 CoreFoundation                 0x182ccada4 CFRunLoopRunSpecific + 424
27 GraphicsServices               0x184734074 GSEventRunModal + 100
28 UIKit                          0x188f85058 UIApplicationMain + 208
29 PrintOSMobile                  0x100160da0 main (main.m:14)
30 libdyld.dylib                  0x181cd959c start + 4

--

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x182deefe0 __exceptionPreprocess
1  libobjc.A.dylib                0x181850538 objc_exception_throw
2  CoreFoundation                 0x182cd59b4 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
3  CoreFoundation                 0x182cd5824 +[NSDictionary dictionaryWithObjects:forKeys:count:]
4  PrintOSMobile                  0x1002a5fc0 -[ICMChatHeadViewController titleTextForMessageFromAdmin:inConversation:]
5  PrintOSMobile                  0x1002a53f0 -[ICMChatHeadViewController viewDidLoad]
6  UIKit                          0x188f1fec0 -[UIViewController loadViewIfRequired]
7  UIKit                          0x188f1fa9c -[UIViewController view]
8  PrintOSMobile                  0x1002d35e8 -[ICMInAppsViewController updateSnippetsInApp:]
9  PrintOSMobile                  0x1002d32ac __55-[ICMInAppsViewController setConversations:completion:]_block_invoke
10 libdispatch.dylib              0x181ca69e0 _dispatch_call_block_and_release
11 libdispatch.dylib              0x181ca69a0 _dispatch_client_callout
12 libdispatch.dylib              0x181cab5e8 _dispatch_main_queue_callback_4CF
13 CoreFoundation                 0x182d9d0c8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
14 CoreFoundation                 0x182d9ace4 __CFRunLoopRun
15 CoreFoundation                 0x182ccada4 CFRunLoopRunSpecific
16 GraphicsServices               0x184734074 GSEventRunModal
17 UIKit                          0x188f85058 UIApplicationMain
18 PrintOSMobile                  0x100160da0 main (main.m:14)
19 libdyld.dylib                  0x181cd959c start

#0. Crashed: com.twitter.crashlytics.ios.exception
0  PrintOSMobile                  0x1001b1388 CLSProcessRecordAllThreads + 4297085832
1  PrintOSMobile                  0x1001b1388 CLSProcessRecordAllThreads + 4297085832
2  PrintOSMobile                  0x1001b17a8 CLSProcessRecordAllThreads + 4297086888
3  PrintOSMobile                  0x1001a245c CLSHandler + 4297024604
4  PrintOSMobile                  0x1001afaa0 __CLSExceptionRecord_block_invoke + 4297079456
5  libdispatch.dylib              0x181ca69a0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x181cb3ee0 _dispatch_barrier_sync_f_invoke + 84
7  PrintOSMobile                  0x1001af54c CLSExceptionRecord + 4297078092
8  PrintOSMobile                  0x1001af388 CLSExceptionRecordNSException + 4297077640
9  PrintOSMobile                  0x1001aefe8 CLSTerminateHandler() + 4297076712
10 libc++abi.dylib                0x18183f5d4 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x18183eef8 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 134
12 libobjc.A.dylib                0x18185066c _objc_exception_destructor(void*) + 362
13 CoreFoundation                 0x182cd59b4 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 364
14 CoreFoundation                 0x182cd5824 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 64
15 PrintOSMobile                  0x1002a5fc0 -[ICMChatHeadViewController titleTextForMessageFromAdmin:inConversation:] + 4298088384
16 PrintOSMobile                  0x1002a53f0 -[ICMChatHeadViewController viewDidLoad] + 4298085360
17 UIKit                          0x188f1fec0 -[UIViewController loadViewIfRequired] + 1036
18 UIKit                          0x188f1fa9c -[UIViewController view] + 28
19 PrintOSMobile                  0x1002d35e8 -[ICMInAppsViewController updateSnippetsInApp:] + 4298274280
20 PrintOSMobile                  0x1002d32ac __55-[ICMInAppsViewController setConversations:completion:]_block_invoke + 4298273452
21 libdispatch.dylib              0x181ca69e0 _dispatch_call_block_and_release + 24
22 libdispatch.dylib              0x181ca69a0 _dispatch_client_callout + 16
23 libdispatch.dylib              0x181cab5e8 _dispatch_main_queue_callback_4CF + 996
24 CoreFoundation                 0x182d9d0c8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
25 CoreFoundation                 0x182d9ace4 __CFRunLoopRun + 1572
26 CoreFoundation                 0x182ccada4 CFRunLoopRunSpecific + 424
27 GraphicsServices               0x184734074 GSEventRunModal + 100
28 UIKit                          0x188f85058 UIApplicationMain + 208
29 PrintOSMobile                  0x100160da0 main (main.m:14)
30 libdyld.dylib                  0x181cd959c start + 4

#1. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x181dcb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x181dcb09c mach_msg + 72
2  CoreFoundation                 0x182d9ce90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x182d9aae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x182ccada4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1837e4d74 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x183805b44 -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                          0x18990f6a8 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x1838e22d8 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x181eb168c _pthread_body + 240
10 libsystem_pthread.dylib        0x181eb159c _pthread_body + 282
11 libsystem_pthread.dylib        0x181eaecb4 thread_start + 4

#2. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x181dcb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x181dcb09c mach_msg + 72
2  PrintOSMobile                  0x10019d4a8 CLSMachExceptionServer + 4297004200
3  libsystem_pthread.dylib        0x181eb168c _pthread_body + 240
4  libsystem_pthread.dylib        0x181eb159c _pthread_body + 282
5  libsystem_pthread.dylib        0x181eaecb4 thread_start + 4

#3. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x181dcb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x181dcb09c mach_msg + 72
2  CoreFoundation                 0x182d9ce90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x182d9aae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x182ccada4 CFRunLoopRunSpecific + 424
5  CFNetwork                      0x1834d6df4 +[NSURLConnection(Loader) _resourceLoadLoop:] + 404
6  Foundation                     0x1838e22d8 __NSThread__start__ + 996
7  libsystem_pthread.dylib        0x181eb168c _pthread_body + 240
8  libsystem_pthread.dylib        0x181eb159c _pthread_body + 282
9  libsystem_pthread.dylib        0x181eaecb4 thread_start + 4

#4. GAIThread
0  libsystem_kernel.dylib         0x181dcb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x181dcb09c mach_msg + 72
2  CoreFoundation                 0x182d9ce90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x182d9aae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x182ccada4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1837e4d74 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1838396c4 -[NSRunLoop(NSRunLoop) run] + 88
7  PrintOSMobile                  0x10017dc3c +[GAI threadMain:] + 4296875068
8  Foundation                     0x1838e22d8 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x181eb168c _pthread_body + 240
10 libsystem_pthread.dylib        0x181eb159c _pthread_body + 282
11 libsystem_pthread.dylib        0x181eaecb4 thread_start + 4

#5. Thread
0  libsystem_kernel.dylib         0x181dcb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x181dcb09c mach_msg + 72
2  CoreFoundation                 0x182d9ce90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x182d9aae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x182ccada4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1837e4d74 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x183805b44 -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  PrintOSMobile                  0x10039ce30 -[UVWatchDog watchDogThreadMethod] + 4299099696
8  Foundation                     0x1838e22d8 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x181eb168c _pthread_body + 240
10 libsystem_pthread.dylib        0x181eb159c _pthread_body + 282
11 libsystem_pthread.dylib        0x181eaecb4 thread_start + 4

#6. com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x181dcb224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x181dcb09c mach_msg + 72
2  CoreFoundation                 0x182d9ce90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x182d9aae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x182ccada4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1837e4d74 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  PrintOSMobile                  0x10035ca3c -[PodIntercom__SRRunLoopThread main] + 4298836540
7  Foundation                     0x1838e22d8 __NSThread__start__ + 996
8  libsystem_pthread.dylib        0x181eb168c _pthread_body + 240
9  libsystem_pthread.dylib        0x181eb159c _pthread_body + 282
10 libsystem_pthread.dylib        0x181eaecb4 thread_start + 4

#7. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x181de923c __select + 8
1  CoreFoundation                 0x182da3cb0 __CFSocketManager + 632
2  libsystem_pthread.dylib        0x181eb168c _pthread_body + 240
3  libsystem_pthread.dylib        0x181eb159c _pthread_body + 282
4  libsystem_pthread.dylib        0x181eaecb4 thread_start + 4

#8. Thread
0  libsystem_pthread.dylib        0x181eaeca8 start_wqthread + 126

#9. Thread
0  libsystem_kernel.dylib         0x181de9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x181eaf1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x181eaecac start_wqthread + 4

#10. Thread
0  libsystem_kernel.dylib         0x181de9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x181eaf1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x181eaecac start_wqthread + 4

#11. Thread
0  libsystem_kernel.dylib         0x181de9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x181eaf1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x181eaecac start_wqthread + 4

#12. Thread
0  libsystem_kernel.dylib         0x181de9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x181eaefd0 _pthread_wqthread + 792
2  libsystem_pthread.dylib        0x181eaecac start_wqthread + 4

#13. Thread
0  libsystem_pthread.dylib        0x181eaeca8 start_wqthread + 126

**Comment by bboyle18** [comment]
Hi @osama-taha 👋 

Can you please provide us with the following additional info:
1. How frequently is this happening?
2. Is it restricted to one device and one OS version?

This info will help us track down the issue.

Cheers

Brian

**Comment by DaleCantwell** [comment]
Hi @osama-taha 
Following up on Brian's message. It looks like your app is using 3.0.11 of the iOS SDK. It looks like this issue was addressed in [3.0.21](https://github.com/intercom/intercom-ios/blob/master/CHANGELOG.md#3021-2016-12-06)

Updating to the newest release [3.2.9](https://github.com/intercom/intercom-ios/releases/tag/3.2.9) should solve this.

**Comment by osama-taha** [comment]
Thanks!!!
