### ISSUE TITLE
Xcode 9 Resources missing

### ISSUE THREAD

**Issue by ivanbruel** [intercom/intercom-ios#284]
Seems like using intercom over Xcode 9 breaks the framework from loading any sort of resources, strings and assets.

## Version info
  - Intercom for iOS version: 3.2.8
  - iOS version: iOS 11b3 and iOS 10.3
  - Xcode version: Xcode 9 beta 2

## Expected behavior
![img_5277](https://user-images.githubusercontent.com/4968178/28364858-2fefd6ae-6c7e-11e7-9a40-7a2bd5eed195.PNG)
![img_5278](https://user-images.githubusercontent.com/4968178/28364860-320bf986-6c7e-11e7-9f85-3575813cf408.PNG)

## Actual behavior
![img_76515703365a-2](https://user-images.githubusercontent.com/4968178/28364952-8a2e08f2-6c7e-11e7-9de1-cd06831fe7e6.jpeg)
![img_76515703365a-1](https://user-images.githubusercontent.com/4968178/28364579-f23ddb7c-6c7c-11e7-9fd2-f71780e99ef9.jpeg)

## Steps to reproduce
 1.  Open the chat UI

**Comment by bboyle18** [comment]
Hi @ivanbruel 
Thanks for getting in touch. Xcode 9 is still in beta so there may be some issues with it at the moment. We will have these fixed for the first version.

In the meantime, can you tell us what you are using to install Intercom? Is it Cocoapods, Manual or Carthage?

Thanks

Brian

**Comment by ivanbruel** [comment]
Installed through Cocoapods.

As for Xcode, it seems to be an issue with loading anything from your bundle resources.

**Comment by bboyle18** [comment]
Thanks, what version of cocoapods are you using?
You are correct about the resources not loading from the bundle. Cocoapods usually configures this automatically but there must be some changes in XCode 9.

**Comment by ivanbruel** [comment]
I'm currently using Cocoapods `1.3.0.beta.2`.

**Comment by bboyle18** [comment]
Thanks for sending on this info.
Not sure if theres anything we can do since this is most likely a cocoapods/Xcode issue that exists in the betas. You might have to wait for a bug fix on their side before this is resolved.
As a result, I'm going to close this issue.

Thanks for reporting 👍

**Comment by bboyle18** [comment]
Re-opening to track they issue

**Comment by bboyle18** [comment]
Hi @ivanbruel 👋 
We've just release version [4.0.0](https://github.com/intercom/intercom-ios/releases/tag/4.0.0) of our Messenger SDK. This provides support for Xcode 9 and iOS 11. 
Can you download this and also make sure you are up to date with the latest version of Cocoapods?
Please let us know if this fixes it, otherwise its probably an issue with Cocoapods.

Cheers

Brian

**Comment by ivanbruel** [comment]
Hey there @bboyle18, something might be wrong with the Cocoapods integration. It's no longer creating an importable `Intercom` framework.

<img width="1327" alt="screen shot 2017-08-28 at 15 49 41" src="https://user-images.githubusercontent.com/4968178/29778819-8c53f35e-8c08-11e7-867b-7729e8dba9ed.png">

**Comment by bboyle18** [comment]
Thanks @ivanbruel 👍 
Working on a fix at the moment. 

Brian

**Comment by bboyle18** [comment]
@ivanbruel We just release [4.0.1](https://github.com/intercom/intercom-ios/releases/tag/4.0.1) that fixes the Cocoapods issue above.
Cheers

Brian

**Comment by igor-makarov** [comment]
Is this related to [CP#7209](https://github.com/CocoaPods/CocoaPods/pull/7209)?

**Comment by jtreanor** [comment]
@igor-makarov No, it was not related to that issue.
