### ISSUE TITLE
Device language not being sent with updated user attributes

### ISSUE THREAD

**Issue by adambolcsfoldi** [intercom/intercom-ios#290]
## Version info
  - Intercom for iOS version: 3.2.6
  - iOS version: Lots

## Expected behavior

For Intercom to automatically send device language along with user attributes, i.e. when calling ` [Intercom updateUser:userAttributes]`.

## Actual behavior

All iOS users' `Browser Language` is set to `unknown`, even after having sent user attributes.

## Steps to reproduce

 1. Register a user.
 2. Send some updated user attributes with `[Intercom updateUser:userAttributes]`
 3. Filter Intercom users by having only iOS sessions.
 4. Confirm that iOS-only users lack a defined `Browser Language` value, despite having other custom attributes.

**Comment by skylerwshaw** [comment]
@adambolcsfoldi `Browser Language` is an attribute unique to web traffic. There is no standard attribute tracked for iOS or Android mobile device languages, though you can send this as a [custom attribute](https://developers.intercom.com/docs/ios-configuration#section-update-a-user) if desired.

If your objective is to have the Intercom UI to appear in a particular language, you can pass the attribute `language_override` with the two letter language code desired (e.g. `language_override: "fr"`). This will result in the Intercom UI appearing in the specified language for that user on the next load of the messenger.
Reference: https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/localize-intercom-to-work-with-multiple-languages

**Comment by adambolcsfoldi** [comment]
Our aim is to segment users based on language. The reason I expected this to be possible automatically, also with users who only use native mobile apps, is that according to previous communication with Intercom support we were told that
> we [Intercom] pull Browser Language from every request the user sends in (either from the JavaScript on a website/app or from the device's data if we're working with a native mobile app
> ...
> Here's the log for that session giving us the "de" locale:
> 
>  [2017-07-24T12:01:06] {"method":"POST","path":"/mobile/users","action":"update","status":200,"params":{"user_attributes":{"signed_up_at":1500895284},"new_session":true,"user":{"email":"fanmiles86@gmx.de","type":"user","user_id":"Fanmiles86"},"device_data":{"browser":"Intercom-Android-SDK","platform":"D6603","language":"Deutsch","device_id":"...","application":"com.fanmiles.androidapp","platform_version":"6.0.1","version":"2.3"\}\}} 

Now the example payload above is obviously for Android, but it was our understanding that it is also done on iOS.

**Comment by skylerwshaw** [comment]
@adambolcsfoldi `Browser Language` is a web-only attribute, as your app isn't a browser. Currently the best way to convey this language is to send it as a custom attribute. We're investigating exposing the language as a default attribute (e.g. Android's `Locale.getDefault().getDisplayLanguage()`).

**Comment by bsmith42** [comment]
There really needs to be a standard list of metrics given the type of platform.  Sure we can set a custom metric but these are common and are typically in other platforms by default.
