### ISSUE TITLE
How does URI in push notification work?

### ISSUE THREAD

**Issue by iBAP** [intercom/intercom-ios#291]
Where do we get the uri? I tried everywhere in app delegate but found none.

**Comment by ronocod** [comment]
Hi, can you tell us exactly what you're trying to do?

**Comment by DaleCantwell** [comment]
Have you registered a URI scheme in your info.plist?

Go into your app's info.plst file and add a row to this and call it URL types. You can then add URL Schemes and Identifiers eg.

<img width="528" alt="screen shot 2017-08-22 at 14 04 01" src="https://user-images.githubusercontent.com/2615468/29566758-d1c5830a-8742-11e7-99a2-beefb12e4139.png">

Do you already have a setup like this and it's not directing you to the correct screen in your app when you tap on an Intercom push message?
