### ISSUE TITLE
-[PodIntercom_IntercomConversationCollectionViewController dealloc] crash

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-ios#293]
## Version info
  - Intercom for iOS version: 3.2.11
  - iOS version: 10.3.3

## Expected behavior
No crash
## Actual behavior
crash
## Steps to reproduce
 No reproducible

## Logs

Bundle Identifier: com.hp.printosforpsp
Date: 2017-08-15T10:10:00Z
OS Version: 10.3.3 (14G60)
Device: iPhone 6s
RAM Free: 8.3%
Disk Free: 10.9%

#0. Crashed: com.twitter.crashlytics.ios.exception
0  PrintOSMobile                  0x10019e068 CLSProcessRecordAllThreads + 4296237160
1  PrintOSMobile                  0x10019e068 CLSProcessRecordAllThreads + 4296237160
2  PrintOSMobile                  0x10019e488 CLSProcessRecordAllThreads + 4296238216
3  PrintOSMobile                  0x10018f13c CLSHandler + 4296175932
4  PrintOSMobile                  0x10019c780 __CLSExceptionRecord_block_invoke + 4296230784
5  libdispatch.dylib              0x185c629a0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x185c6fee0 _dispatch_barrier_sync_f_invoke + 84
7  PrintOSMobile                  0x10019c22c CLSExceptionRecord + 4296229420
8  PrintOSMobile                  0x10019c068 CLSExceptionRecordNSException + 4296228968
9  PrintOSMobile                  0x10019bcc8 CLSTerminateHandler() + 4296228040
10 libc++abi.dylib                0x1857fb5d4 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x1857faef8 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 134
12 libobjc.A.dylib                0x18580c66c _objc_exception_destructor(void*) + 362
13 CoreFoundation                 0x186daaeb4 +[NSException raise:format:] + 102
14 Foundation                     0x187843760 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112
15 UIKit                          0x18d05e2c0 -[UICollectionView dealloc] + 628
16 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
17 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
18 libobjc.A.dylib                0x185818398 object_dispose + 28
19 UIKit                          0x18d27f008 -[UIResponder dealloc] + 156
20 UIKit                          0x18d05de88 -[UIViewController dealloc] + 1776
21 PrintOSMobile                  0x100334c50 -[PodIntercom_IntercomConversationCollectionViewController dealloc] + 4297903184
22 libobjc.A.dylib                0x18582a134 (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 836
23 UIKit                          0x18d05de68 -[UIViewController dealloc] + 1744
24 UIKit                          0x18d0689d8 -[UINavigationController dealloc] + 488
25 UIKit                          0x18d778d78 -[UIPopoverController .cxx_destruct] + 408
26 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
27 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
28 libobjc.A.dylib                0x185818398 object_dispose + 28
29 UIKit                          0x18d121c9c -[UIPopoverController dealloc] + 600
30 UIKit                          0x18d56bd20 -[UISplitViewControllerClassicImpl .cxx_destruct] + 316
31 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
32 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
33 libobjc.A.dylib                0x185818398 object_dispose + 28
34 UIKit                          0x18d5599a0 -[UISplitViewControllerClassicImpl dealloc] + 324
35 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
36 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
37 libobjc.A.dylib                0x185818398 object_dispose + 28
38 UIKit                          0x18d27f008 -[UIResponder dealloc] + 156
39 UIKit                          0x18d05de88 -[UIViewController dealloc] + 1776
40 UIKit                          0x18d2324f8 -[UIPresentationController .cxx_destruct] + 312
41 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
42 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
43 libobjc.A.dylib                0x185818398 object_dispose + 28
44 UIKit                          0x18d22dee0 -[UIPresentationController dealloc] + 64
45 UIKit                          0x18d22dbe0 __destroy_helper_block_.437 + 24
46 libsystem_blocks.dylib         0x185cb7a68 _Block_release + 160
47 UIKit                          0x18d95e704 -[_UIViewControllerTransitionContext .cxx_destruct] + 116
48 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
49 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
50 libobjc.A.dylib                0x185818398 object_dispose + 28
51 UIKit                          0x18d00288c -[_UIViewControllerTransitionContext dealloc] + 64
52 UIKit                          0x18d00283c -[_UIViewControllerOneToOneTransitionContext dealloc] + 88
53 UIKit                          0x18d29a814 -[_UIViewControllerKeyboardAnimationStyle dealloc] + 68
54 UIKit                          0x18d8bc86c -[UIInputViewPlacementTransition dealloc] + 160
55 UIKit                          0x18d8c2800 __destroy_helper_block_.931 + 28
56 libsystem_blocks.dylib         0x185cb7a68 _Block_release + 160
57 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
58 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
59 libobjc.A.dylib                0x185818398 object_dispose + 28
60 CoreFoundation                 0x186c920a8 -[__NSDictionaryI dealloc] + 136
61 libobjc.A.dylib                0x18582a134 (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 836
62 CoreFoundation                 0x186c86b28 _CFAutoreleasePoolPop + 28
63 CoreFoundation                 0x186d56cec __CFRunLoopRun + 1580
64 CoreFoundation                 0x186c86da4 CFRunLoopRunSpecific + 424
65 GraphicsServices               0x1886f1074 GSEventRunModal + 100
66 UIKit                          0x18cf41c9c UIApplicationMain + 208
67 PrintOSMobile                  0x10014cdf0 main (main.m:14)
68 libdyld.dylib                  0x185c9559c start + 4

--

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x186daafe0 __exceptionPreprocess
1  libobjc.A.dylib                0x18580c538 objc_exception_throw
2  CoreFoundation                 0x186daaeb4 +[NSException raise:format:]
3  Foundation                     0x187843760 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKit                          0x18d05e2c0 -[UICollectionView dealloc]
5  libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*)
6  libobjc.A.dylib                0x185818334 objc_destructInstance
7  libobjc.A.dylib                0x185818398 object_dispose
8  UIKit                          0x18d27f008 -[UIResponder dealloc]
9  UIKit                          0x18d05de88 -[UIViewController dealloc]
10 PrintOSMobile                  0x100334c50 -[PodIntercom_IntercomConversationCollectionViewController dealloc]
11 libobjc.A.dylib                0x18582a134 (anonymous namespace)::AutoreleasePoolPage::pop(void*)
12 UIKit                          0x18d05de68 -[UIViewController dealloc]
13 UIKit                          0x18d0689d8 -[UINavigationController dealloc]
14 UIKit                          0x18d778d78 -[UIPopoverController .cxx_destruct]
15 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*)
16 libobjc.A.dylib                0x185818334 objc_destructInstance
17 libobjc.A.dylib                0x185818398 object_dispose
18 UIKit                          0x18d121c9c -[UIPopoverController dealloc]
19 UIKit                          0x18d56bd20 -[UISplitViewControllerClassicImpl .cxx_destruct]
20 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*)
21 libobjc.A.dylib                0x185818334 objc_destructInstance
22 libobjc.A.dylib                0x185818398 object_dispose
23 UIKit                          0x18d5599a0 -[UISplitViewControllerClassicImpl dealloc]
24 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*)
25 libobjc.A.dylib                0x185818334 objc_destructInstance
26 libobjc.A.dylib                0x185818398 object_dispose
27 UIKit                          0x18d27f008 -[UIResponder dealloc]
28 UIKit                          0x18d05de88 -[UIViewController dealloc]
29 UIKit                          0x18d2324f8 -[UIPresentationController .cxx_destruct]
30 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*)
31 libobjc.A.dylib                0x185818334 objc_destructInstance
32 libobjc.A.dylib                0x185818398 object_dispose
33 UIKit                          0x18d22dee0 -[UIPresentationController dealloc]
34 UIKit                          0x18d22dbe0 __destroy_helper_block_.437
35 libsystem_blocks.dylib         0x185cb7a68 _Block_release
36 UIKit                          0x18d95e704 -[_UIViewControllerTransitionContext .cxx_destruct]
37 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*)
38 libobjc.A.dylib                0x185818334 objc_destructInstance
39 libobjc.A.dylib                0x185818398 object_dispose
40 UIKit                          0x18d00288c -[_UIViewControllerTransitionContext dealloc]
41 UIKit                          0x18d00283c -[_UIViewControllerOneToOneTransitionContext dealloc]
42 UIKit                          0x18d29a814 -[_UIViewControllerKeyboardAnimationStyle dealloc]
43 UIKit                          0x18d8bc86c -[UIInputViewPlacementTransition dealloc]
44 UIKit                          0x18d8c2800 __destroy_helper_block_.931
45 libsystem_blocks.dylib         0x185cb7a68 _Block_release
46 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*)
47 libobjc.A.dylib                0x185818334 objc_destructInstance
48 libobjc.A.dylib                0x185818398 object_dispose
49 CoreFoundation                 0x186c920a8 -[__NSDictionaryI dealloc]
50 libobjc.A.dylib                0x18582a134 (anonymous namespace)::AutoreleasePoolPage::pop(void*)
51 CoreFoundation                 0x186c86b28 _CFAutoreleasePoolPop
52 CoreFoundation                 0x186d56cec __CFRunLoopRun
53 CoreFoundation                 0x186c86da4 CFRunLoopRunSpecific
54 GraphicsServices               0x1886f1074 GSEventRunModal
55 UIKit                          0x18cf41c9c UIApplicationMain
56 PrintOSMobile                  0x10014cdf0 main (main.m:14)
57 libdyld.dylib                  0x185c9559c start

#0. Crashed: com.twitter.crashlytics.ios.exception
0  PrintOSMobile                  0x10019e068 CLSProcessRecordAllThreads + 4296237160
1  PrintOSMobile                  0x10019e068 CLSProcessRecordAllThreads + 4296237160
2  PrintOSMobile                  0x10019e488 CLSProcessRecordAllThreads + 4296238216
3  PrintOSMobile                  0x10018f13c CLSHandler + 4296175932
4  PrintOSMobile                  0x10019c780 __CLSExceptionRecord_block_invoke + 4296230784
5  libdispatch.dylib              0x185c629a0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x185c6fee0 _dispatch_barrier_sync_f_invoke + 84
7  PrintOSMobile                  0x10019c22c CLSExceptionRecord + 4296229420
8  PrintOSMobile                  0x10019c068 CLSExceptionRecordNSException + 4296228968
9  PrintOSMobile                  0x10019bcc8 CLSTerminateHandler() + 4296228040
10 libc++abi.dylib                0x1857fb5d4 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x1857faef8 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 134
12 libobjc.A.dylib                0x18580c66c _objc_exception_destructor(void*) + 362
13 CoreFoundation                 0x186daaeb4 +[NSException raise:format:] + 102
14 Foundation                     0x187843760 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112
15 UIKit                          0x18d05e2c0 -[UICollectionView dealloc] + 628
16 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
17 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
18 libobjc.A.dylib                0x185818398 object_dispose + 28
19 UIKit                          0x18d27f008 -[UIResponder dealloc] + 156
20 UIKit                          0x18d05de88 -[UIViewController dealloc] + 1776
21 PrintOSMobile                  0x100334c50 -[PodIntercom_IntercomConversationCollectionViewController dealloc] + 4297903184
22 libobjc.A.dylib                0x18582a134 (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 836
23 UIKit                          0x18d05de68 -[UIViewController dealloc] + 1744
24 UIKit                          0x18d0689d8 -[UINavigationController dealloc] + 488
25 UIKit                          0x18d778d78 -[UIPopoverController .cxx_destruct] + 408
26 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
27 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
28 libobjc.A.dylib                0x185818398 object_dispose + 28
29 UIKit                          0x18d121c9c -[UIPopoverController dealloc] + 600
30 UIKit                          0x18d56bd20 -[UISplitViewControllerClassicImpl .cxx_destruct] + 316
31 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
32 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
33 libobjc.A.dylib                0x185818398 object_dispose + 28
34 UIKit                          0x18d5599a0 -[UISplitViewControllerClassicImpl dealloc] + 324
35 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
36 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
37 libobjc.A.dylib                0x185818398 object_dispose + 28
38 UIKit                          0x18d27f008 -[UIResponder dealloc] + 156
39 UIKit                          0x18d05de88 -[UIViewController dealloc] + 1776
40 UIKit                          0x18d2324f8 -[UIPresentationController .cxx_destruct] + 312
41 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
42 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
43 libobjc.A.dylib                0x185818398 object_dispose + 28
44 UIKit                          0x18d22dee0 -[UIPresentationController dealloc] + 64
45 UIKit                          0x18d22dbe0 __destroy_helper_block_.437 + 24
46 libsystem_blocks.dylib         0x185cb7a68 _Block_release + 160
47 UIKit                          0x18d95e704 -[_UIViewControllerTransitionContext .cxx_destruct] + 116
48 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
49 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
50 libobjc.A.dylib                0x185818398 object_dispose + 28
51 UIKit                          0x18d00288c -[_UIViewControllerTransitionContext dealloc] + 64
52 UIKit                          0x18d00283c -[_UIViewControllerOneToOneTransitionContext dealloc] + 88
53 UIKit                          0x18d29a814 -[_UIViewControllerKeyboardAnimationStyle dealloc] + 68
54 UIKit                          0x18d8bc86c -[UIInputViewPlacementTransition dealloc] + 160
55 UIKit                          0x18d8c2800 __destroy_helper_block_.931 + 28
56 libsystem_blocks.dylib         0x185cb7a68 _Block_release + 160
57 libobjc.A.dylib                0x18580af00 object_cxxDestructFromClass(objc_object*, objc_class*) + 148
58 libobjc.A.dylib                0x185818334 objc_destructInstance + 92
59 libobjc.A.dylib                0x185818398 object_dispose + 28
60 CoreFoundation                 0x186c920a8 -[__NSDictionaryI dealloc] + 136
61 libobjc.A.dylib                0x18582a134 (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 836
62 CoreFoundation                 0x186c86b28 _CFAutoreleasePoolPop + 28
63 CoreFoundation                 0x186d56cec __CFRunLoopRun + 1580
64 CoreFoundation                 0x186c86da4 CFRunLoopRunSpecific + 424
65 GraphicsServices               0x1886f1074 GSEventRunModal + 100
66 UIKit                          0x18cf41c9c UIApplicationMain + 208
67 PrintOSMobile                  0x10014cdf0 main (main.m:14)
68 libdyld.dylib                  0x185c9559c start + 4

#1. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x185d87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185d8709c mach_msg + 72
2  CoreFoundation                 0x186d58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186d56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x186c86da4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1877a1db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1877c2b84 -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                          0x18d8cb830 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x18789f318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x185e6d68c _pthread_body + 240
10 libsystem_pthread.dylib        0x185e6d59c _pthread_body + 282
11 libsystem_pthread.dylib        0x185e6acb4 thread_start + 4

#2. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x185d87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185d8709c mach_msg + 72
2  PrintOSMobile                  0x10018a188 CLSMachExceptionServer + 4296155528
3  libsystem_pthread.dylib        0x185e6d68c _pthread_body + 240
4  libsystem_pthread.dylib        0x185e6d59c _pthread_body + 282
5  libsystem_pthread.dylib        0x185e6acb4 thread_start + 4

#3. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x185d87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185d8709c mach_msg + 72
2  CoreFoundation                 0x186d58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186d56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x186c86da4 CFRunLoopRunSpecific + 424
5  CFNetwork                      0x187493df4 +[NSURLConnection(Loader) _resourceLoadLoop:] + 404
6  Foundation                     0x18789f318 __NSThread__start__ + 996
7  libsystem_pthread.dylib        0x185e6d68c _pthread_body + 240
8  libsystem_pthread.dylib        0x185e6d59c _pthread_body + 282
9  libsystem_pthread.dylib        0x185e6acb4 thread_start + 4

#4. GAIThread
0  libsystem_kernel.dylib         0x185d87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185d8709c mach_msg + 72
2  CoreFoundation                 0x186d58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186d56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x186c86da4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1877a1db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1877f6704 -[NSRunLoop(NSRunLoop) run] + 88
7  PrintOSMobile                  0x10016a91c +[GAI threadMain:] + 4296026396
8  Foundation                     0x18789f318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x185e6d68c _pthread_body + 240
10 libsystem_pthread.dylib        0x185e6d59c _pthread_body + 282
11 libsystem_pthread.dylib        0x185e6acb4 thread_start + 4

#5. Thread
0  libsystem_kernel.dylib         0x185da4e1c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x185e6c814 _pthread_cond_wait + 640
2  libc++.1.dylib                 0x185795ac8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
3  JavaScriptCore                 0x18b63af08 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 112
4  JavaScriptCore                 0x18b63ae7c bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 168
5  JavaScriptCore                 0x18b63ad5c std::__1::__shared_ptr_emplace<std::__1::mutex, std::__1::allocator<std::__1::mutex> >::~__shared_ptr_emplace() + 34
6  JavaScriptCore                 0x18b63b00c void* std::__1::__thread_proxy<std::__1::tuple<void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 92
7  libsystem_pthread.dylib        0x185e6d68c _pthread_body + 240
8  libsystem_pthread.dylib        0x185e6d59c _pthread_body + 282
9  libsystem_pthread.dylib        0x185e6acb4 thread_start + 4

#6. WebThread
0  libsystem_kernel.dylib         0x185d87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185d8709c mach_msg + 72
2  CoreFoundation                 0x186d58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186d56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x186c86da4 CFRunLoopRunSpecific + 424
5  WebCore                        0x18b958d3c RunWebThread(void*) + 456
6  libsystem_pthread.dylib        0x185e6d68c _pthread_body + 240
7  libsystem_pthread.dylib        0x185e6d59c _pthread_body + 282
8  libsystem_pthread.dylib        0x185e6acb4 thread_start + 4

#7. com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x185d87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185d8709c mach_msg + 72
2  CoreFoundation                 0x186d58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186d56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x186c86da4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1877a1db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  PrintOSMobile                  0x10037f5e8 -[PodIntercom__SRRunLoopThread main] + 4298208744
7  Foundation                     0x18789f318 __NSThread__start__ + 996
8  libsystem_pthread.dylib        0x185e6d68c _pthread_body + 240
9  libsystem_pthread.dylib        0x185e6d59c _pthread_body + 282
10 libsystem_pthread.dylib        0x185e6acb4 thread_start + 4

#8. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x185da523c __select + 8
1  CoreFoundation                 0x186d5fcb0 __CFSocketManager + 632
2  libsystem_pthread.dylib        0x185e6d68c _pthread_body + 240
3  libsystem_pthread.dylib        0x185e6d59c _pthread_body + 282
4  libsystem_pthread.dylib        0x185e6acb4 thread_start + 4

#9. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#10. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#11. Thread
0  libsystem_kernel.dylib         0x185d87224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x185d8709c mach_msg + 72
2  CoreFoundation                 0x186d58e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186d56ae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x186c86da4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1877a1db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1877c2b84 -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  PrintOSMobile                  0x1003bf9dc -[UVWatchDog watchDogThreadMethod] + 4298471900
8  Foundation                     0x18789f318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x185e6d68c _pthread_body + 240
10 libsystem_pthread.dylib        0x185e6d59c _pthread_body + 282
11 libsystem_pthread.dylib        0x185e6acb4 thread_start + 4

#12. Thread
0  libsystem_kernel.dylib         0x185da5314 __semwait_signal + 8
1  libsystem_c.dylib              0x185cc48b0 nanosleep + 212
2  Foundation                     0x18789e5d0 +[NSThread sleepForTimeInterval:] + 136
3  PrintOSMobile                  0x100382424 -[UVVideoRecorder processQueue] + 4298220580
4  Foundation                     0x18789f318 __NSThread__start__ + 996
5  libsystem_pthread.dylib        0x185e6d68c _pthread_body + 240
6  libsystem_pthread.dylib        0x185e6d59c _pthread_body + 282
7  libsystem_pthread.dylib        0x185e6acb4 thread_start + 4

#13. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#14. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#15. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#16. Thread
0  libsystem_kernel.dylib         0x185d87278 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x185c756b4 _os_semaphore_timedwait + 92
2  libdispatch.dylib              0x185c74c5c _dispatch_semaphore_wait_slow + 72
3  libdispatch.dylib              0x185c73f48 _dispatch_worker_thread + 268
4  libsystem_pthread.dylib        0x185e6d68c _pthread_body + 240
5  libsystem_pthread.dylib        0x185e6d59c _pthread_body + 282
6  libsystem_pthread.dylib        0x185e6acb4 thread_start + 4

#17. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#18. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#19. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#20. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#21. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#22. Thread
0  libsystem_pthread.dylib        0x185e6aca8 start_wqthread + 126

#23. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#24. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#25. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#26. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#27. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6b1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

#28. Thread
0  libsystem_kernel.dylib         0x185da5a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185e6afd0 _pthread_wqthread + 792
2  libsystem_pthread.dylib        0x185e6acac start_wqthread + 4

**Comment by jtreanor** [comment]
Hi @osama-taha,

Can you verify that this crash occurred in a version of your app running 3.2.11 of the Intercom Messenger?

This looks very like a crash that we fixed in [3.2.10](https://github.com/intercom/intercom-ios/releases/tag/3.2.10).

James

**Comment by osama-taha** [comment]
yes it's 3.2.9 not 3.2.11
I will close the ticket.
