### ISSUE TITLE
-[UIImage(ICMImageUtils) icm_resizeImageToSize:] crash

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-ios#295]
## Version info
  - Intercom for iOS version: 3.2.9
  - iOS version: 10.3.1

## Expected behavior
No crash
## Actual behavior
crash
## Steps to reproduce
 No reproducible

## Logs

Bundle Identifier: com.hp.printosforpsp
OS Version: 10.3.1 (14G60)
Device: iPhone 6s

#0. Crashed: com.apple.main-thread
0  libsystem_platform.dylib       0x185a54dcc _platform_memmove + 108
1  CoreGraphics                   0x187ec3cc4 CGDataProviderCreateWithCopyOfData + 212
2  CoreGraphics                   0x187ec3cc4 CGDataProviderCreateWithCopyOfData + 212
3  CoreGraphics                   0x1880d5b88 CGBitmapContextCreateImage + 88
4  PrintOSMobile                  0x100321204 -[UIImage(ICMImageUtils) icm_resizeImageToSize:] + 4298035716
5  PrintOSMobile                  0x1002f9cc4 __51-[ICMReactionsViewController displayOption:inView:]_block_invoke_2 + 4297874628
6  libdispatch.dylib              0x1858529e0 _dispatch_call_block_and_release + 24
7  libdispatch.dylib              0x1858529a0 _dispatch_client_callout + 16
8  libdispatch.dylib              0x1858575e8 _dispatch_main_queue_callback_4CF + 996
9  CoreFoundation                 0x1869490c0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
10 CoreFoundation                 0x186946cdc __CFRunLoopRun + 1572
11 CoreFoundation                 0x186876d94 CFRunLoopRunSpecific + 424
12 GraphicsServices               0x1882e0074 GSEventRunModal + 100
13 UIKit                          0x18cb2f130 UIApplicationMain + 208
14 PrintOSMobile                  0x100158df0 main (main.m:14)
15 libdyld.dylib                  0x18588559c start + 4

--

#0. Crashed: com.apple.main-thread
0  libsystem_platform.dylib       0x185a54dcc _platform_memmove + 108
1  CoreGraphics                   0x187ec3cc4 CGDataProviderCreateWithCopyOfData + 212
2  CoreGraphics                   0x187ec3cc4 CGDataProviderCreateWithCopyOfData + 212
3  CoreGraphics                   0x1880d5b88 CGBitmapContextCreateImage + 88
4  PrintOSMobile                  0x100321204 -[UIImage(ICMImageUtils) icm_resizeImageToSize:] + 4298035716
5  PrintOSMobile                  0x1002f9cc4 __51-[ICMReactionsViewController displayOption:inView:]_block_invoke_2 + 4297874628
6  libdispatch.dylib              0x1858529e0 _dispatch_call_block_and_release + 24
7  libdispatch.dylib              0x1858529a0 _dispatch_client_callout + 16
8  libdispatch.dylib              0x1858575e8 _dispatch_main_queue_callback_4CF + 996
9  CoreFoundation                 0x1869490c0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
10 CoreFoundation                 0x186946cdc __CFRunLoopRun + 1572
11 CoreFoundation                 0x186876d94 CFRunLoopRunSpecific + 424
12 GraphicsServices               0x1882e0074 GSEventRunModal + 100
13 UIKit                          0x18cb2f130 UIApplicationMain + 208
14 PrintOSMobile                  0x100158df0 main (main.m:14)
15 libdyld.dylib                  0x18588559c start + 4

#1. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x185977224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18597709c mach_msg + 72
2  CoreFoundation                 0x186948e88 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186946adc __CFRunLoopRun + 1060
4  CoreFoundation                 0x186876d94 CFRunLoopRunSpecific + 424
5  Foundation                     0x187390d64 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1873b1b34 -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                          0x18d4b95f8 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x18748e2c8 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x185a5d75c _pthread_body + 240
10 libsystem_pthread.dylib        0x185a5d66c _pthread_body + 282
11 libsystem_pthread.dylib        0x185a5ad84 thread_start + 4

#2. com.twitter.crashlytics.ios.MachExceptionServer
0  PrintOSMobile                  0x1001aa068 CLSProcessRecordAllThreads + 4296499304
1  PrintOSMobile                  0x1001aa068 CLSProcessRecordAllThreads + 4296499304
2  PrintOSMobile                  0x1001aa488 CLSProcessRecordAllThreads + 4296500360
3  PrintOSMobile                  0x10019b13c CLSHandler + 4296438076
4  PrintOSMobile                  0x10019647c CLSMachExceptionServer + 4296418428
5  libsystem_pthread.dylib        0x185a5d75c _pthread_body + 240
6  libsystem_pthread.dylib        0x185a5d66c _pthread_body + 282
7  libsystem_pthread.dylib        0x185a5ad84 thread_start + 4

#3. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x185977224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18597709c mach_msg + 72
2  CoreFoundation                 0x186948e88 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186946adc __CFRunLoopRun + 1060
4  CoreFoundation                 0x186876d94 CFRunLoopRunSpecific + 424
5  CFNetwork                      0x187082ca4 +[NSURLConnection(Loader) _resourceLoadLoop:] + 404
6  Foundation                     0x18748e2c8 __NSThread__start__ + 996
7  libsystem_pthread.dylib        0x185a5d75c _pthread_body + 240
8  libsystem_pthread.dylib        0x185a5d66c _pthread_body + 282
9  libsystem_pthread.dylib        0x185a5ad84 thread_start + 4

#4. GAIThread
0  libsystem_kernel.dylib         0x185977224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18597709c mach_msg + 72
2  CoreFoundation                 0x186948e88 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186946adc __CFRunLoopRun + 1060
4  CoreFoundation                 0x186876d94 CFRunLoopRunSpecific + 424
5  Foundation                     0x187390d64 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1873e56b4 -[NSRunLoop(NSRunLoop) run] + 88
7  PrintOSMobile                  0x10017691c +[GAI threadMain:] + 4296288540
8  Foundation                     0x18748e2c8 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x185a5d75c _pthread_body + 240
10 libsystem_pthread.dylib        0x185a5d66c _pthread_body + 282
11 libsystem_pthread.dylib        0x185a5ad84 thread_start + 4

#5. Thread
0  libsystem_kernel.dylib         0x185994e1c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x185a5c8e4 _pthread_cond_wait + 640
2  libc++.1.dylib                 0x185385ac8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
3  JavaScriptCore                 0x18b227c98 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 112
4  JavaScriptCore                 0x18b227c0c bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 168
5  JavaScriptCore                 0x18b227aec std::__1::__shared_ptr_emplace<std::__1::mutex, std::__1::allocator<std::__1::mutex> >::~__shared_ptr_emplace() + 34
6  JavaScriptCore                 0x18b227d9c void* std::__1::__thread_proxy<std::__1::tuple<void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 92
7  libsystem_pthread.dylib        0x185a5d75c _pthread_body + 240
8  libsystem_pthread.dylib        0x185a5d66c _pthread_body + 282
9  libsystem_pthread.dylib        0x185a5ad84 thread_start + 4

#6. WebThread
0  libsystem_kernel.dylib         0x185977224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18597709c mach_msg + 72
2  CoreFoundation                 0x186948e88 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186946adc __CFRunLoopRun + 1060
4  CoreFoundation                 0x186876d94 CFRunLoopRunSpecific + 424
5  WebCore                        0x18b546b5c RunWebThread(void*) + 456
6  libsystem_pthread.dylib        0x185a5d75c _pthread_body + 240
7  libsystem_pthread.dylib        0x185a5d66c _pthread_body + 282
8  libsystem_pthread.dylib        0x185a5ad84 thread_start + 4

#7. com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x185977224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18597709c mach_msg + 72
2  CoreFoundation                 0x186948e88 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186946adc __CFRunLoopRun + 1060
4  CoreFoundation                 0x186876d94 CFRunLoopRunSpecific + 424
5  Foundation                     0x187390d64 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  PrintOSMobile                  0x10038b5e8 -[PodIntercom__SRRunLoopThread main] + 4298470888
7  Foundation                     0x18748e2c8 __NSThread__start__ + 996
8  libsystem_pthread.dylib        0x185a5d75c _pthread_body + 240
9  libsystem_pthread.dylib        0x185a5d66c _pthread_body + 282
10 libsystem_pthread.dylib        0x185a5ad84 thread_start + 4

#8. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x18599523c __select + 8
1  CoreFoundation                 0x18694fca8 __CFSocketManager + 632
2  libsystem_pthread.dylib        0x185a5d75c _pthread_body + 240
3  libsystem_pthread.dylib        0x185a5d66c _pthread_body + 282
4  libsystem_pthread.dylib        0x185a5ad84 thread_start + 4

#9. com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x185977224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18597709c mach_msg + 72
2  CoreFoundation                 0x186948e88 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x186946adc __CFRunLoopRun + 1060
4  CoreFoundation                 0x186876d94 CFRunLoopRunSpecific + 424
5  CoreFoundation                 0x1868c39a0 CFRunLoopRun + 112
6  CoreMotion                     0x18d9ce03c (null) + 203104
7  libsystem_pthread.dylib        0x185a5d75c _pthread_body + 240
8  libsystem_pthread.dylib        0x185a5d66c _pthread_body + 282
9  libsystem_pthread.dylib        0x185a5ad84 thread_start + 4

#10. Thread
0  libsystem_kernel.dylib         0x185995a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185a5b0a0 _pthread_wqthread + 792
2  libsystem_pthread.dylib        0x185a5ad7c start_wqthread + 4

#11. Thread
0  libsystem_kernel.dylib         0x185995a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185a5b274 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185a5ad7c start_wqthread + 4

#12. Thread
0  libsystem_kernel.dylib         0x185995a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185a5b274 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185a5ad7c start_wqthread + 4

#13. Thread
0  libsystem_kernel.dylib         0x185995a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185a5b274 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185a5ad7c start_wqthread + 4

#14. Thread
0  libsystem_kernel.dylib         0x185995a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185a5b274 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185a5ad7c start_wqthread + 4

#15. Thread
0  libsystem_kernel.dylib         0x185995a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185a5b0a0 _pthread_wqthread + 792
2  libsystem_pthread.dylib        0x185a5ad7c start_wqthread + 4

#16. Thread
0  libsystem_kernel.dylib         0x185995a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185a5b274 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185a5ad7c start_wqthread + 4

#17. com.google.fira.worker
0  libsystem_kernel.dylib         0x1859794dc fsync + 8
1  libsqlite3.dylib               0x186ef704c (null) + 58940
2  libsqlite3.dylib               0x186f01e38 (null) + 2364
3  libsqlite3.dylib               0x186ef6908 (null) + 57080
4  libsqlite3.dylib               0x186ee35a0 (null) + 21252
5  libsqlite3.dylib               0x186eb2d68 (null) + 3468
6  libsqlite3.dylib               0x186edc5f4 (null) + 59172
7  libsqlite3.dylib               0x186ece0e0 sqlite3_step + 528
8  libsqlite3.dylib               0x186e9a974 sqlite3_exec + 468
9  PrintOSMobile                  0x1001dba68 -[FIRASqliteStore endTransaction] + 4296702568
10 PrintOSMobile                  0x1001db8f8 -[FIRASqliteStore performTransaction:] + 4296702200
11 PrintOSMobile                  0x1001f62b8 -[FIRAMeasurement logEventOnWorkerQueue:] + 4296811192
12 PrintOSMobile                  0x100204298 __52-[FIRAScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 4296868504
13 libdispatch.dylib              0x1858529e0 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x1858529a0 _dispatch_client_callout + 16
15 libdispatch.dylib              0x185860ad4 _dispatch_queue_serial_drain + 928
16 libdispatch.dylib              0x1858562cc _dispatch_queue_invoke + 884
17 libdispatch.dylib              0x185862a50 _dispatch_root_queue_drain + 540
18 libdispatch.dylib              0x1858627d0 _dispatch_worker_thread3 + 124
19 libsystem_pthread.dylib        0x185a5b1d0 _pthread_wqthread + 1096
20 libsystem_pthread.dylib        0x185a5ad7c start_wqthread + 4

#18. Thread
0  libsystem_kernel.dylib         0x185995a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x185a5b274 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x185a5ad7c start_wqthread + 4

#19. com.pinterest.PINDiskCache Asynchronous Queue
0  libsystem_kernel.dylib         0x185978ca4 write + 8
1  CoreFoundation                 0x1868f1b38 fileWrite + 32
2  CoreFoundation                 0x18688fa58 CFWriteStreamWrite + 448
3  CoreFoundation                 0x18688f83c writeBytes + 236
4  CoreFoundation                 0x18688f09c _appendObject + 1320
5  CoreFoundation                 0x18690f3bc __CFBinaryPlistWriteOrPresize + 536
6  Foundation                     0x1873ef70c -[NSKeyedArchiver finishEncoding] + 588
7  Foundation                     0x187458048 +[NSKeyedArchiver archiveRootObject:toFile:] + 236
8  PrintOSMobile                  0x10036e270 -[PodIntercom_PINDiskCache setObject:forKey:fileURL:] + 4298351216
9  PrintOSMobile                  0x10036cf10 __51-[PodIntercom_PINDiskCache setObject:forKey:block:]_block_invoke + 4298346256
10 libdispatch.dylib              0x1858529e0 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x1858529a0 _dispatch_client_callout + 16
12 libdispatch.dylib              0x18585f604 _dispatch_continuation_pop + 448
13 libdispatch.dylib              0x18585f338 _dispatch_async_redirect_invoke + 608
14 libdispatch.dylib              0x185862a50 _dispatch_root_queue_drain + 540
15 libdispatch.dylib              0x1858627d0 _dispatch_worker_thread3 + 124
16 libsystem_pthread.dylib        0x185a5b1d0 _pthread_wqthread + 1096
17 libsystem_pthread.dylib        0x185a5ad7c start_wqthread + 4

**Comment by bboyle18** [comment]
Hi @osama-taha 👋 
Thanks for reporting this and apologies for the delayed reply.

Just wondering if this has happened for you again since you reported the issue?
Its the first instance of this that we have seen so would be keen to get to the bottom of it if its a recurring issue.

Thanks

Brian

**Comment by osama-taha** [comment]
It's just happened again on 3.2.12

**Comment by bboyle18** [comment]
Thanks @osama-taha 
We are looking into this issue this week.
Brian

**Comment by bboyle18** [comment]
Hi @osama-taha 

Unfortunately we are unable to recreate this issue. 
If you can provide us with steps to consistently recreate the issue or if the rate of occurrence increases, we are happy to reopen it.

Cheers

Brian
