### ISSUE TITLE
TextField doesn't appear when keyboard appears  trying to write a message

### ISSUE THREAD

**Issue by OscarMugica** [intercom/intercom-ios#296]
Hello! I installed Intercom and when I try to send a message the textfield hides after keyboard appears.

## Version info
  - Intercom for iOS version: 3.2.12
  - iOS version: 10.3.2

## Expected behavior
Show textfield after keyboard appears
## Actual behavior
The message textfield doesn't show after keyboard is showing
## Steps to reproduce
 1. Open app
 2. Go to Intercom Messenger
 3. Write new message

## Logs
![captura de pantalla 2017-08-21 a la s 4 51 59 p m](https://user-images.githubusercontent.com/12464196/29539808-2037904e-8691-11e7-9f2a-90e057c1896b.png)
![captura de pantalla 2017-08-21 a la s 4 52 08 p m](https://user-images.githubusercontent.com/12464196/29539809-204df9ce-8691-11e7-8e8f-c3c97d7c41ab.png)

**Comment by bboyle18** [comment]
Hi @OscarMugica 👋 

Thanks for getting in touch.
Can you please provide me with a list of the 3rd party libs that you are using in your app?
This issue is usually caused by one of those libs interfering with the composer. 
Once I see your list of 3rd party libs, I should be able to help you work around this issue.

Cheers

Brian

**Comment by OscarMugica** [comment]
Thanks! But I don't remember added a new 3rd party libs after install Interco. Before I update the pods intercom started with the issue.

Check these are the Pods that I'm using. 
Thanks!

![captura de pantalla 2017-08-22 a la s 9 40 00 a m](https://user-images.githubusercontent.com/12464196/29571229-48d5e590-871e-11e7-8847-876eefa9fe7d.png)

**Comment by bboyle18** [comment]
Thanks for sending on the list.
In order to track down the issue, would you be able to temporarily remove `PullToRefresher` from your app to see if this resolves the issue? Its the only 3rd party lib that _could_ be affecting the composer. If it is, we will see if there is a way to work around it.

Thanks

Brian

**Comment by OscarMugica** [comment]
Sorry but it did not work for me :(
In fact I just created  a new project with the same pods and Intercom works perfectly.
I don't really know what could cause this issue...

My current project without Pulltorefreseher
![21040489_10210043738946350_719210214_n](https://user-images.githubusercontent.com/12464196/29576324-0784958c-872d-11e7-969c-d3a06a423cd3.jpg)

My new test project with all pods I sent before
![21015503_10210043738866348_1390641259_n](https://user-images.githubusercontent.com/12464196/29576360-22f12178-872d-11e7-896d-d1f0d9d3ebd5.jpg)

**Comment by bboyle18** [comment]
Ok, if you are able to create a new project with these pods and Intercom works perfectly, then the problem probably lies within your own code somewhere.
Is there anywhere in your code where you are performing swizzling or modifying the `firstResponder`?

Thanks

Brian

**Comment by OscarMugica** [comment]
Hi! I checked about swizzling or modifying the firstResponder, but I found nothing about it... But when I call  "Intercom.presentMessenger()" I got a log in console with a message about constraints, could this cause the issue?

Thanks

Oscar

**Comment by bboyle18** [comment]
Can you provide us with that console output please?

**Comment by bboyle18** [comment]
Hi @OscarMugica 👋 
Would you be able to provide us with the console output you are seeing when you call `Intercom.presentMessenger()`?
It should show us exactly whats going on and help us fix this issue for you.

Thanks

Brian

**Comment by OscarMugica** [comment]
Hi! Sorry! I was working in another project. 
So, this is the console output:

[MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
 [MC] Reading from public effective user settings.

Thanks

Oscar

**Comment by bboyle18** [comment]
Hi @OscarMugica 
In your previous comment, you mentioned ` I got a log in console with a message about constraints`
The log above doesn't show any constraint errors.

Can you provide the log you were referencing?

Thanks

Brian

**Comment by OscarMugica** [comment]
Hi! I solved this error. The problem was in my storyboard. Now the only console output appears when the keyboard is shown while try to write message in intercom.

This message appears jus when keyboard is shown:
[MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
[MC] Reading from public effective user settings.


Thanks

Oscar

**Comment by bboyle18** [comment]
Thats great to hear 🎉 
The console log above is just iOS system logging.

Glad you got sorted.

Brian
