### ISSUE TITLE
Request failed: unauthorized (401)

### ISSUE THREAD

**Issue by mostafamobiquity** [intercom/intercom-ios#297]
## Version info
  - Intercom for iOS version: 10
  - iOS version: 3.2.9

## Expected behavior

Register User

## Actual behavior

Returns this error:
 [Intercom] ERROR - Tried to log an event but there was a network error (401) - Request failed: unauthorized (401)
## Steps to reproduce
 1. Just open the app, in app delegate is sets API Key
 2. then when registering user "using both email & id" it produces the error above

## Logs
2017-08-22 15:22:05.056 MyOrder Go[52431:3197124] [Intercom] ERROR - Tried to log an event but there was a network error (401) - Request failed: unauthorized (401)
[Intercom] ERROR - Tried to update user but there was a network error (401) - Request failed: unauthorized (401)

**Comment by bboyle18** [comment]
Hi @mostafamobiquity 👋 

This error is usually as a result of setting an incorrect `APP_ID` or `API_KEY`. You'll need to confirm that these are correct.
This could also be called by turning on `Identity Verification` but not setting a secure hash in your code.

Let me know if that helps

Brian

**Comment by mostafamobiquity** [comment]
Yeah apparently its Identity Verification. Can you please explain how by turning it off Its not secure? I mean can you provide me a user scenario?

Thank you 🙂

**Comment by bboyle18** [comment]
Heres a link to our docs about setting up Identity Verification on iOS.
https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enable-identity-verification-in-intercom-for-ios

A simple explanation is that Identity Verification keeps all communication between you and your customers secure and stops anyone impersonating a customer or yourself. It verifies that all data passing between your app and Intercom is from a trusted source and hasn't been interfered with.

Hope this helps.

Brian
