### ISSUE TITLE
Duplicate symbol

### ISSUE THREAD

**Issue by cayde-6** [intercom/intercom-ios#301]
Hello, I get warnings like "duplicate symbol" in v4.0.0 when linking project
<img width="1040" alt="2017-08-28 14 04 03" src="https://user-images.githubusercontent.com/28859816/29771565-29a134a2-8bfd-11e7-8575-e9604a342b47.png">

**Comment by bboyle18** [comment]
Hi @cayde-6 
Are you using dynamic of static frameworks with cocoapods? i.e. Does you `Podfile` contain `use_frameworks!`

Thanks

Brian

**Comment by cayde-6** [comment]
@bboyle18, Podfile not contain use_frameworks!

**Comment by bboyle18** [comment]
Ok, thanks for that info. 👍 
We're looking into this issue and will get back to you once we've figured out whats wrong.
Thanks
Brian

**Comment by bboyle18** [comment]
This is now fixed in [Release 4.0.1](https://github.com/intercom/intercom-ios/releases/tag/4.0.1).
Thanks for report this @cayde-6 
Brian

**Comment by cayde-6** [comment]
Thanks so much for the quick fix 👍🏻
Maxim
