### ISSUE TITLE
NSNotification.Name.IntercomUnreadConversationCountDidChange for Swift 2.2

### ISSUE THREAD

**Issue by nharbo** [intercom/intercom-ios#302]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.2.7
  - iOS version: 10 (but Swift version 2.2)

## Expected behavior
I want to use this, as mentioned in your documentation:
NotificationCenter.default.addObserver(self, 
                                       selector: #selector(YourClassName.updateUnreadCount(_:)), 
                                           name: NSNotification.Name.IntercomUnreadConversationCountDidChange, 
                                         object: nil)

But - I cant use NSNotification.Name in Swift 2.2 - what can I put as name for my NSNotification instead?

I tried like this:
NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(ProfileVC.updateUnreadCount(_:)), name: "IntercomUnreadConversationCountDidChange", object: nil)

But thats not firing the notification when a new message is received :) 

Whats my options?

**Comment by nharbo** [comment]
Okay, actually it works with this:
NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(ProfileVC.updateUnreadCount(_:)), name: "IntercomUnreadConversationCountDidChange", object: nil)

It just shows, that the notification is not fired, when the Intercom.setInAppMessagesVisible(false) is set.. I see that another user had this problem as well - are there any chances for a fix? :)

**Comment by bboyle18** [comment]
Hi @nharbo 
We're working on a fix for https://github.com/intercom/intercom-ios/issues/298 at the moment. If you have some code you could share with us that re-creates this, we would appreciate it, as we can't re-create the issue.
I'm going to close this issue as you've resolved it yourself. You can keep an eye on https://github.com/intercom/intercom-ios/issues/298 for a fix.
Thanks

Brian
