### ISSUE TITLE
Intercom 4.0.0: Invalid CFBundleSupportedPlatforms value

### ISSUE THREAD

**Issue by siberianisaev** [intercom/intercom-ios#304]
## Version info
  - Intercom for iOS version: 4.0.0
  - iOS version: all

## Steps to reproduce
 1. upload app version with Intercom 4.0.0 to iTC

## Logs

From the Application loader:
`ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/MyApp.app/IntercomTranslations.bundle' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."`

**Comment by bboyle18** [comment]
Hi @siberianisaev 👋 
We just release [version 4.0.1](https://github.com/intercom/intercom-ios/releases/tag/4.0.1) to address some issues we had.
Can you please try updating to this version and let me know how you get on?
Thanks

Brian

**Comment by bboyle18** [comment]
I can confirm that the `info.plist` contains the correct value of `iPhoneOS` for `CFBundleSupportedPlatforms` in release 4.0.1.

**Comment by siberianisaev** [comment]
@bboyle18 thanks

**Comment by dredful** [comment]
Hello @bboyle18,

Unfrotunately we are trying to submit to Apple today and we are still getting this error today for iOS version 4.0.1 using PODs

Using Intercom (4.0.1)

ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/Rever.app/IntercomTranslations.bundle' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
