### ISSUE TITLE
No known class method for selector 'setHMAC:data:'

### ISSUE THREAD

**Issue by pandeiro** [intercom/intercom-ios#305]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 4.0.1
  - iOS version: 10

## Expected behavior

With version 3.2.11, I was able to build my project (which uses Intercom) in Xcode.

## Actual behavior

With 4.0.1 I am not.

## Steps to reproduce
 1. Open the project in Xcode
 2. Notice buildtime error ARC Semantic Issue
 3. See error in IntercomWrapper.m

## Logs

This is the error produced at buildtime:

```
No known class method for selector 'setHMAC:data:'
```

This is the part of the code Xcode highlights:

```
// Available as NativeModules.IntercomWrapper.setHMAC
RCT_EXPORT_METHOD(setHMAC:(NSString*)hmac data:(NSString*)data callback:(RCTResponseSenderBlock)callback) {
    [Intercom setHMAC:hmac data:data];
    callback(@[[NSNull null]]);
};
```

**Comment by bboyle18** [comment]
Hi @pandeiro 👋 
`[Intercom setHMAC:data:]` was deprecated in [Release 3.2.0](https://github.com/intercom/intercom-ios/releases/tag/3.2.0). We removed this deprecated method in [Release 4.0.0](https://github.com/intercom/intercom-ios/releases/tag/4.0.0).

You'll need to update your code to use `[Intercom setUserHash:]`. Here are our docs for how to use the new API. https://developers.intercom.com/docs/ios-identity-verification

Let me know if you need anything else.

Brian

**Comment by pandeiro** [comment]
Thanks @bboyle18 !
