### ISSUE TITLE
Intercom 4.0.1: Invalid CFBundleSupportedPlatforms value

### ISSUE THREAD

**Issue by dredful** [intercom/intercom-ios#306]
Hello @bboyle18,

Unfortunately we are trying to submit to Apple today and we are still getting this Invalid CFBundleSupportedPlatforms error for iOS version 4.0.1 using PODs

Using Intercom (4.0.1)

ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/My.app/IntercomTranslations.bundle' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

<img width="573" alt="screen shot 2017-08-29 at 11 35 57 am" src="https://user-images.githubusercontent.com/337795/29835163-5e5a2918-8cae-11e7-8ab3-b765fc4a1241.png">

**Comment by bboyle18** [comment]
Hi @dredful 👋 
Would you be able to share the contents of your Podfile with me please and can you confirm that you are definitely on release 4.0.1?
I've checked the contents of the `Info.plist` within the framework and can confirm that it is not using `iPhoneSimulator` as a value for `CFBundleSupportedPlatforms`. See the attached image.

We did have a problem with this in release 4.0.0 so I would ensure that you are on 4.0.1. 
You can also validate the `Info.plist` yourself by examining `Intercom.framework/Resources/IntercomTranslations.bundle`.

Cheers
Brian

<img width="539" alt="screen shot 2017-08-29 at 19 14 19" src="https://user-images.githubusercontent.com/3185423/29836914-8f2622be-8cee-11e7-99cc-6136d9152058.png">

**Comment by dredful** [comment]
Bizarre because the info.plist in the Intercom.framework/Resources/IntercomTranslations.bundle matches yours.

<img width="714" alt="screen shot 2017-08-29 at 2 14 45 pm" src="https://user-images.githubusercontent.com/337795/29842037-d63cb0c0-8cc4-11e7-8686-c33ca1457b03.png">

**Comment by dredful** [comment]
For now I have rolled our Intercom POD back to 3.2.12 and we were able to submit to Apple.

Installing Intercom 3.2.12 (was 4.0.1)

**Comment by bboyle18** [comment]
That is strange. The only thing I can think of that there is cache holding on to the old info.plist 4.0.0. 
Can you confirm that you had the 4.0.0 version installed earlier?

**Comment by bboyle18** [comment]
Hi @dredful 👋 
Would you be able to confirm that you previously had version 4.0.0 of the Intercom SDK installed?
It will help us a lot to know this.

Thanks!

Brian

**Comment by dredful** [comment]
Yes, we did previously have version 4.0.0 of the Intercom SDK installed.

**Comment by bboyle18** [comment]
Thanks for letting me know @dredful 
Have you tried installing 4.0.1 since then?
If not, would you be able to try it? I think this is probably a caching issue with Cocoapods, so you'd need to de-integrate the Intercom pod and then add it back in again.

Thanks

Brian

**Comment by dredful** [comment]
@bboyle18 

Today I removed Intercom from our pod file, ran a pod update, then returned Intercom to our pod file and then ran a pod update.

I am glad to report that Apple accepted the upload to the App Store without any errors.

Thanks!

**Comment by bboyle18** [comment]
🎉 That's great to hear!
Appreciate you getting back to us with this info. 
Brian
