### ISSUE TITLE
presentMessenger() doesn't work without setLauncherVisible(true)

### ISSUE THREAD

**Issue by krzysztofbielecki** [intercom/intercom-ios#309]
## Version info
  - Intercom for iOS version: 4.0.1 (with binding to Xamarin)
  - iOS version: 10.3

## Expected behavior
presentMessenger() opens Messenger.

## Actual behavior
When I call setLauncherVisible(true); and then presentMessenger() messenger opens. But without calling setLauncherVisible(true) before that method it doesn't work. I'm not sure if the problem is in the binding that I have done or in the original library, but it is strange for me that when I call setLauncherVisible before, everything is working but without that, it doesn't. 

## Steps to reproduce
 1. SetApiKey(INTERCOM_API_KEY, INTERCOM_APP_ID);
 2. RegisterUserWithUserId(id);
 3. PresentMessenger()

## Logs

**Comment by bboyle18** [comment]
Hi @krzysztofbielecki 👋 

What you described works as expected using the native iOS SDK.
You mentioned that you are using 
`Intercom for iOS version: 4.0.1 (with binding to Xamarin)`
We don't provide any official support for a Xamarin binding. Can you please tell us what exactly you are using for this? I suspect the issue lies with this and not with our SDK.

Cheers

Brian

**Comment by krzysztofbielecki** [comment]
Hi @bboyle18 

Unfortunately, I know that you don't have official support for Xamarin. I'm using Objective Sharpie to create such binding libraries as it is described in [here](https://developer.xamarin.com/guides/ios/advanced_topics/binding_objective-c/)  the project I've created is similar to this [one ](https://github.com/iccthedral/IntercomSDK.iOS) . My company is considering to use Intercom and now I'm trying to create such binding libraries to use it. 
Never the less for me it is quite strange that after calling setLauncherVisible(true) every thing is working and without that, it doesn't. I'm not changing the implementation of the methods, all I do is creating the interface to call your library from Xamarin. Maybe there is something in "setLauncherVisible" that PresentMessenger depends on.

Cheers

Krzysztof

**Comment by bboyle18** [comment]
The method `presentMessenger` has no dependency on `setLauncherVisible`. You can test this out in our own [sample app here](https://github.com/intercom/intercom-ios/tree/master/Examples).
The problem probably lies somewhere in your binding code.
You many want to have a look at this other Xamarin library for Intercom as it might be of some help.

https://github.com/lipka/intercom-ios-xamarin

Cheers
Brian
