### ISSUE TITLE
README.md 4.x upgrade link redirects

### ISSUE THREAD

**Issue by shawnwall** [intercom/intercom-ios#311]
The current README.md links to an upgrade guide for 4.x which simply ends up redirecting to:

https://docs.intercom.com/install-on-your-product-or-site/quick-install/install-and-configure-intercom-on-your-mobile-app

Does an actual upgrade guide exist?

**Comment by bboyle18** [comment]
Hi @shawnwall 👋 
Thanks for highlighting this issue with the link. We'll get that sorted.
What version are you upgrading from? There aren't actually any API changes apart from removing previously deprecated methods.

Let me know if theres anything we can help you with.

Brian

**Comment by shawnwall** [comment]
I'll just be moving up from latest 3.x and wondered if there were any breaking changes. Thanks!

**Comment by skylerwshaw** [comment]
@shawnwall we removed some already deprecated methods but there are no breaking changes between `3.x` and `4.x`. 😄
