### ISSUE TITLE
Tried to update user but there was a network error (401)

### ISSUE THREAD

**Issue by newPrimitives** [intercom/intercom-ios#313]
## Version info
  - Intercom for iOS version: 3.2.12
  - iOS version: 10.3.1 (14E8301) Simulator 

## Expected behavior
Taping on Intercom chat button should open a screen and show chats between the support and that particular user. Or in case the user doesn't have any chat history, an empty screen. 

## Actual behavior
Screen shows "Something went wrong - Could not load your conversations". Message in the console shows `Tried to update user but there was a network error (401) - Request failed: unauthorized (401)`. Initialization of intercom is done in AppDelegate with the following code: `Intercom.setApiKey('key', 'app_id')` and `Intercom.setLauncherVisible(true)`. User is identified after login, with `Intercom.registerUser(withUserId: user.uid)`. This happens on every app launch. 

## Steps to reproduce
 1. Open app 
 2. Click on message bubble 
 3. Error shows 

## Logs
2017-09-13 16:46:25.771 AppName[28151:1245975] [Intercom] ERROR - Tried to update user but there was a network error (401) - Request failed: unauthorized (401)

**Comment by bboyle18** [comment]
Hi @newPrimitives 👋 

We usually see this error for customers who have Identify Verification turned on on their account, but they haven't provided a valid hash.
Is this something that you might have done? Here are some docs on Identity Verfification https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enable-identity-verification-in-intercom-for-ios

Brian

**Comment by bboyle18** [comment]
HI @newPrimitives 
Did you manage to solve this problem?
Please let us know so we can close this issue.

Thanks

Brian

**Comment by newPrimitives** [comment]
@bboyle18 Just looking into it, I'll edit this answer once I figure it out.
