### ISSUE TITLE
Failed UI for back and exit buttons (no navigation bar) on iPhone 6s with iOS 11.0.3

### ISSUE THREAD

**Issue by svrzii** [intercom/intercom-ios#324]
## Version info
  - Intercom for iOS version: 4.1.2
  - iOS version: 11.0.3

## Expected behavior

Normal UI of Intercom with the navigation bar. The back & exit buttons should be clickable and at the right positions with the navigation bar.

[Simulator iPhone 7 - iOS 10.3](https://user-images.githubusercontent.com/11535008/31654167-6ffca8a6-b325-11e7-82ba-84fab0ed363a.png)

## Actual behavior

The back & exit buttons of Intercom are not on the right positions. This is a screenshot from my device running iOS 11.0.3. It looks like there is no navigation bar on my example. I tested it on a iPhone 7 simulator running iOS 10.3 and it works fine there.
 
[iPhone 6s - iOS 11.0.3](https://user-images.githubusercontent.com/11535008/31654533-a5f81944-b326-11e7-84e1-2c318991bf40.PNG)

## Steps to reproduce
 1. Build application in XCode 8.3.3
 2. Run it on a device with the new iOS 11.0.3
 3. Open Intercom messenger (Intercom.presentMessageComposer())

_
P.S.: We did not yet update to the new Swift 4 & XCode 9.

**Comment by bboyle18** [comment]
Hi @svrzii 👋 

Thanks for getting in touch. This is definitely something we have not seen before.
Can you tell me if you are able to recreate this consistently....or did it only happen once?

Thanks

Brian

**Comment by svrzii** [comment]
Hi @bboyle18 

yes this happens every time I open Intercom on my phone and it's the same on my colleagues iPhone 7. Before the upgrade to the new iOS it worked like it should. The user with that kind of Intercom cannot close it anymore. (the "half" buttons are not clickable).

**Comment by bboyle18** [comment]
Thanks for confirming this.
Would you be able to test this out with our Example app please? https://github.com/intercom/intercom-ios/tree/master/Examples
This will help us to pinpoint the problem. I've tried to recreate the issue myself but I can't.

Is your app in the AppStore where I can download and test it?
Or do you have a sample github project you can provide me with to help recreate it?

Thanks

Brian

**Comment by svrzii** [comment]
and @bboyle18 maybe just for your info, the Intrix application on the App store has Intercom 4.0.3, it was not updated there yet. But the issue is the same on both 4.0.3 and 4.1.2

**Comment by bboyle18** [comment]
@svrzii 👍  Thanks for this. We'll take a look

**Comment by bboyle18** [comment]
@svrzii I was able to recreate this issue with your app.
We need to investigate this further and we're going to need get account details from you.
I can't do this on public GitHub so I'm going to reach out to you via Intercom and we can discuss it further there.

Brian

**Comment by svrzii** [comment]
@bboyle18 I do not have access to Intercom conversations, but just start to contact my colleagues over Intercom & they will give you my contact email over there.

**Comment by bboyle18** [comment]
I can send you an email via intercom. I have you as matej dot svrznjak at intera dot si.
Is this correct?

**Comment by svrzii** [comment]
Yea, thats me :)

**Comment by svrzii** [comment]
Ok I found the problem. This is the code that created the issue on iOS 11:
`#import "UINavigationBar+CustomHeight.h"`
`#import "objc/runtime.h"`
`static char const *const heightKey = "Height";`

`@implementation UINavigationBar (CustomHeight)`
`- (void)setCustomHeight:(CGFloat)height`
`{`
`    objc_setAssociatedObject(self, heightKey, @(height), OBJC_ASSOCIATION_RETAIN_NONATOMIC);`
`}`

`- (NSNumber *)height`
`{`
   ` return objc_getAssociatedObject(self, heightKey);`
`}`

`- (CGSize)sizeThatFits:(CGSize)size`
`{`
    `CGSize newSize;`
`    if (self.height) {`
`        newSize = CGSizeMake(self.superview.bounds.size.width, [self.height floatValue]);`
`    } else {`
`        newSize = [super sizeThatFits:size];`
`    }`
`    return newSize;`
`}`

All categories are loaded into the runtime of the app. This means that since the host app defined sizeThatFits: in a category, it is also defined for Intercom.This is why all categories should be prefixed e.g. PREFIX_sizeThatFits:  so that they don't impact anything else within the app.

Thanks @bboyle18 for all your support.

**Comment by Jauzee** [comment]
I have a similar issue. Temporary downgraded to `4.0.3` since it works fine.

![intercom](https://user-images.githubusercontent.com/7991920/31995838-c3c25610-b98e-11e7-8e40-03ea2ef63674.png)

**Comment by bboyle18** [comment]
Hi @Jauzee 👋 
Can you tell me how you have integrated the SDK please? It looks like the Intercom bundle that contains images and strings has not been loaded.
Can you also please tell me if you are swizzling your app in any way or if you have any 3rd party libs that might be doing this?

Thanks

Brian

**Comment by Jauzee** [comment]
Hi @bboyle18 

I have integrated `Intercom` using Cocoapods. I'm not swizzling any method, but need to make sure about the third-party libraries.

Please note that I'm just set my Podfile to use `~> 4.0.0` and now it works great, but with `~> 4.0` it behaves as on the screenshot.

**Comment by Jauzee** [comment]
@bboyle18 just faced the bug again (on `4.0.3`). I'll check the Pods and will notify you here the result.

**Comment by Jauzee** [comment]
The issue I faced was fixed by _clean build folder_. Now it works even with `4.1.2`.

Thanks @bboyle18
