### ISSUE TITLE
Messages disappear after tapping "Send" and are not sent to the server

### ISSUE THREAD

**Issue by crontab** [intercom/intercom-ios#329]
This is a new problem in 4.1.3. Opening a messenger and sending a message generally works, however, if you deuathenticate and authenticate the user again, message sending fails in a very strange way: the message disappears from the messenger view immediately after tapping "Send", and it never reaches the server.

I tested this by changing only the Intercom version and nothing else, it definitely fails only on 4.1.3

## Version info
  - Intercom for iOS version: 4.1.3
  - iOS version: iOS 11.0.3

## Expected behavior

Sending a message has worked beforel 4.1.3.

## Actual behavior

... but doesn't work after the app deauthenticates and then authenticates the user again.

## Steps to reproduce
 1. Deauthenticate the user (`[Intercom logout]; [Intercom registerUnidentifiedUser];`)
 2. Authenticate user (`[Intercom registerUserWithUserId:userId]`)
 3. Open the messenger (`[Intercom presentMessageComposer]`) and try to send a message

## Logs

Nothing relevant in the logs unfortunately.

**Comment by jtreanor** [comment]
Thanks for reporting this @crontab.

We'll look into this and update you once we know more.

**Comment by jtreanor** [comment]
We have identified a bug in the Intercom backend that was causing this.

The issue has now been fixed. Thanks for reporting @crontab!
