### ISSUE TITLE
Intercom conversations don't trigger bubble overlay

### ISSUE THREAD

**Issue by MattesGroeger** [intercom/intercom-ios#330]
## Version info
  - Intercom for iOS version: 3.1.2
  - iOS version: 10.3.3

## Expected behavior
When opening the App from a push notification (triggered by a conversation) the speech bubble should show up on the bottom with the full text. The user should be able to open the full conversation from there.

## Actual behavior
The speech bubble doesn't show up when opening from the push notification. It however shows up if the app is launched later (not via the push notification).

## Steps to reproduce
 1. Set `IntercomAutoIntegratePushNotifications` to `false`
 2. Implement the delegate method `func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable:Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void)` according to the documentation
 3. Make sure the app is running in the background
 4. Start a conversation with the user via Intercom
 5. Open the app from the push notification
 6. Delegate method will be called but the speech bubble doesn't show up

## Logs
No logs.

If I send a manual message via Intercom Engage it works properly (via push notification). It seems to be an issue with Intercom direct conversations only.

**Comment by jtreanor** [comment]
Hi @MattesGroeger 👋 

Thanks for sending this in. 3.1.2 is quite an old version. Can you try using the latest (4.1.3) to see if it resolves your issue?

James

**Comment by MattesGroeger** [comment]
Ok, tested against version `3.2.12` and it works. Thanks!

**Comment by jtreanor** [comment]
@MattesGroeger Glad you got it sorted. I still suggest updating to the latest version when you get a chance.
