### ISSUE TITLE
_IntercomUnreadConversationCountDidChangeNotification

### ISSUE THREAD

**Issue by donovantc** [intercom/intercom-ios#331]
## Version info
  - Intercom for iOS version: 4.1.3
  - iOS version: 11.0

## Expected behavior
It builds successfully

## Actual behavior
I am getting the following error when I try build my project, after having included the intercom framework in the embedded frameworks and linked the binary, within my project  

```
Undefined symbols for architecture x86_64:
  "_IntercomUnreadConversationCountDidChangeNotification", referenced from:
      ___48-[IntercomEventEmitter handleUpdateUnreadCount:]_block_invoke in libRNIntercom.a(IntercomEventEmitter.o)
      -[IntercomEventEmitter constantsToExport] in libRNIntercom.a(IntercomEventEmitter.o)
      -[IntercomEventEmitter supportedEvents] in libRNIntercom.a(IntercomEventEmitter.o)
      -[IntercomEventEmitter startObserving] in libRNIntercom.a(IntercomEventEmitter.o)
  "_OBJC_CLASS_$_ICMCompany", referenced from:
      objc-class-ref in libRNIntercom.a(IntercomUserAttributesBuilder.o)
  "_OBJC_CLASS_$_ICMUserAttributes", referenced from:
      objc-class-ref in libRNIntercom.a(IntercomUserAttributesBuilder.o)
  "_OBJC_CLASS_$_Intercom", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libRNIntercom.a(IntercomEventEmitter.o)
      objc-class-ref in libRNIntercom.a(IntercomWrapper.o)
     (maybe you meant: _OBJC_CLASS_$_IntercomUserAttributesBuilder, _OBJC_CLASS_$_IntercomWrapper , _OBJC_CLASS_$_IntercomEventEmitter )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps to reproduce
 1. Install via carthage (also tried via manual install)
 2. Add to the Embeded Framework
 3. Link Binary
4. Try and build project

I have tried a couple of clean installations of this but I cannot seem to solve this issue. Any help would be appreciated. Thanks.

**Comment by bboyle18** [comment]
Hi @donovantc 👋 
It looks like you might have https://github.com/tinycreative/react-native-intercom installed on your app instead of the official SDK.
The classes referenced in the stacktrace do not belong to the official Intercom iOS SDK.

Brian

**Comment by donovantc** [comment]
Hi @bboyle18,

That's true. I was struggling to get that setup and somewhere along the line I was just using the official Intercom iOS SDK, when actually I need to work with the react-native-intercom. You set me back on the right track and now I have sorted it out :) Thanks!
