### ISSUE TITLE
ERROR - Tried to log an event but there was a network error (422) - Request failed: client error (422).

### ISSUE THREAD

**Issue by erdem-inan** [intercom/intercom-ios#333]
## Version info
  - Intercom for iOS version: 4.1.3
  - iOS version: iOS 11.0.3

## Expected behavior

When using Intercom.logEvent(withName: "Test Event"), we should see the event associated to the user logged in Intercom

## Actual behavior

Nothing is happing in the Intercom console, no event is shown for the user and we get this error in the Xcode Console :

[Intercom] ERROR - Tried to log an event but there was a network error (422) - Request failed: client error (422).

Note: Same behaviour is happening with this method Intercom.logEvent(withName: "Test Event", metaData: metaData)

## Steps to reproduce
 1.  Authenticate user to Intercom via this method: Intercom.registerUser(withEmail: "...")
 2. Intercom.logEvent(withName: "Test Event")
 3. Here we get the error in the console. 

## Logs

[Intercom] ERROR - Tried to log an event but there was a network error (422) - Request failed: client error (422).

**Comment by skylerwshaw** [comment]
Hi @erdem-inan, this sounds like an issue specific to your integration and not an Intercom SDK bug. Can you please open a conversation with the Intercom support team by doing one of the following?:
* Start a conversation using the Intercom in-app messenger while logged into the Intercom dashboard
* Email team@intercom.io 

In your request please mention my name and include the actual "Test Event" for which you received a 422 error. I'm looking for logs and not seeing that you've sent `"Test Event"` in the past few hours. We'll want to find the exact request to debug this.

Thank you!

**Comment by erdem-inan** [comment]
Hy @skylerwshaw ,

Actually i tried sending log wit the name "Sync error". 
I place "Test event" in this issue because I did not think that it would be relevant for you. 
My mistake.

**Comment by skylerwshaw** [comment]
The error is being caused by your Intercom app having more than 200 active event names. It appears that many of your 200 unique events are being consumed by events of the name format: `preload document:` + `36 character UUID`. It seems that you should use a name of `preload document` and have the UUID contained in the metadata.

**Comment by erdem-inan** [comment]
Ok thanks you for the information ! I Will check that !

**Comment by erdem-inan** [comment]
I checked in the console of the app (Settings -> App Settings -> Event), I don't see the event "preload document: UUID"....
I only see "Preload picture: UUID" which is already in archived status. It was an event we created 3 years ago.

**Comment by skylerwshaw** [comment]
@erdem-inan You don't see the events because you're in a different Intercom app than the one you're using with your iOS app. The one using the `"Sync error"` you reference above is not the same Intercom app for which you're looking at the settings page.

**Comment by xfernandez** [comment]
I am performing the same issue here: Tried to log an event but there was a network error

How can you help?

**Comment by skylerwshaw** [comment]
@xfernandez Please start a conversation with the Intercom support team from your Intercom dashboard, or email team@intercom.io if you're unable to have a live chat. Feel free to mention my name, Skyler.

Most of the time 422 errors are due to sending invalid data such as invalid types (do not send arrays or hashes as event metadata) or you have strings greater than 255 characters.

**Comment by xfernandez** [comment]
@skylerwshaw excuse me. I talked with intercom support and we solved the issue. As you said, first of all was because the 255 characters, and then was because the metadata format. It seems that it's a unique level and I can do complex multilevel json format. But it's ok
