### ISSUE TITLE
"Previous Conversations" table view is obscured by navigation bar

### ISSUE THREAD

**Issue by feosuna1** [intercom/intercom-ios#334]
## Version info
  - Intercom for iOS version: 4.1.3
  - iOS version: 11.0

## Expected behavior

The previous conversations `UITableView` should appear below the `UINavigationBar`.

## Actual behavior

The previous conversations `UITableView` is aligned to the top of the `UINavigationBar` causing the top row to be obscured.

## Steps to reproduce
 1. Open "Previous" conversations

## Logs

None

Here's a Reveal screenshot of what I'm seeing:

![screen shot 2017-11-07 at 1 20 12 pm](https://user-images.githubusercontent.com/12620/32510524-e34ea5f8-c3be-11e7-86db-1a9a611f8a4b.png)

**Comment by bboyle18** [comment]
Hi @feosuna1 👋

Are you doing any swindling of uitableview or modifying the content insets of table views in your app?

Cheers

Brian

**Comment by feosuna1** [comment]
Hi @bboyle18,

Thanks for the quick response and pointing me towards content insets.  While I am not adjusting the insets myself, I do have the following code that I recently added:

```
[UIScrollView appearance].contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
```

Commenting this line out causes the the "Previous Conversations" `UITableView` to behave correctly.  I'll go back to the drawing board to fix the original problem, but in the mean time I will close this issue out.

Thanks!

**Comment by getaaron** [comment]
@feosuna1 Seems like you should be able to set `contentInsetAdjustmentBehavior` to whatever you want on the appearance proxy, and intercom should explicitly set it to whatever they need it to be on their table view

**Comment by jtreanor** [comment]
@getaaron Yes, we will do this in the next release.

However, its worth noting that `contentInsetAdjustmentBehavior` is not marked with `UI_APPEARANCE_SELECTOR` and is therefore not officially supported to set via the appearance proxy.
