### ISSUE TITLE
Fatal Exception: NSRangeException

### ISSUE THREAD

**Issue by cayde-6** [intercom/intercom-ios#336]
Hi, guys :)
## Version info
Intercom version: 4.1.3 or 4.1.2
OS Version: 11.0.3 (15A432)
Device: iPhone 7 Plus
RAM Free: 12.6%
Disk Free: 1.2%

## Logs
Fatal Exception: NSRangeException
*** -[__NSArrayM objectAtIndexedSubscript:]: index 9223372036854775807 beyond bounds [0 .. 2]

0  CoreFoundation                 0x182d77d38 __exceptionPreprocess
1  libobjc.A.dylib                0x18228c528 objc_exception_throw
2  CoreFoundation                 0x182d10c44 _CFArgv
3  CoreFoundation                 0x182cfde54 -[__NSArrayM removeAllObjects]
4  <AppName>                      0x1013828a4 -[ICMReactionsViewController didPan:]
5  UIKit                          0x18c814f78 -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:]
6  UIKit                          0x18c8194dc _UIGestureRecognizerSendTargetActions
7  UIKit                          0x18c303dc8 _UIGestureRecognizerSendActions
8  UIKit                          0x18c1b8748 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:]
9  UIKit                          0x18c8033fc _UIGestureEnvironmentUpdate
10 UIKit                          0x18c802f88 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:]
11 UIKit                          0x18c8020e4 -[UIGestureEnvironment _updateGesturesForEvent:window:]
12 UIKit                          0x18c1b6a54 -[UIWindow sendEvent:]
13 UIKit                          0x18c188078 -[UIApplication sendEvent:]
14 UIKit                          0x18cac7f98 __dispatchPreprocessedEventFromEventQueue
15 UIKit                          0x18caca408 __handleEventQueueInternal
16 UIKit                          0x18cac3574 __handleHIDEventFetcherDrain
17 CoreFoundation                 0x182d20358 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
18 CoreFoundation                 0x182d202d8 __CFRunLoopDoSource0
19 CoreFoundation                 0x182d1fb60 __CFRunLoopDoSources0
20 CoreFoundation                 0x182d1d738 __CFRunLoopRun
21 CoreFoundation                 0x182c3e2d8 CFRunLoopRunSpecific
22 GraphicsServices               0x184acff84 GSEventRunModal
23 UIKit                          0x18c1eb880 UIApplicationMain
24 <AppName>                      0x10100df3c main (main.m:67)
25 libdyld.dylib                  0x18276256c start

**Comment by bboyle18** [comment]
Hi @cayde-6 

Thanks for reporting this. Is it reproducible or did it only happen once?

Thanks

Brian

**Comment by cayde-6** [comment]
@bboyle18 , it happened on a production with one user. Information from Fabric.

**Comment by bboyle18** [comment]
Hi @cayde-6 

We have been unable to re-create this, so I'm going to close the issue.
Feel free to re-open if it happens again.

Thanks

Brian
