### ISSUE TITLE
[ICMHTTPBridge submitMetrics] crash

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-ios#340]
# Platform: ios
# OS Version: 11.2.0 (15C5107a)
# Crashlytics: http://crashes.to/s/07ef68bd36a
# intercom version: 4.1.3

Fatal Exception: NSGenericException
0  CoreFoundation                 0x182d02364 __exceptionPreprocess
1  libobjc.A.dylib                0x181f48528 objc_exception_throw
2  CoreFoundation                 0x182d019f0 -[__NSSingleObjectEnumerator initWithObject:]
3  Foundation                     0x1836da410 -[NSSet(NSKeyValueCoding) valueForKey:]
4  PrintOSMobile                  0x100b4bbdc +[ICMHTTPBridge submitMetrics]
5  CoreFoundation                 0x182c9433c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
6  CoreFoundation                 0x182c938dc _CFXRegistrationPost
7  CoreFoundation                 0x182c93640 ___CFXNotificationPost_block_invoke
8  CoreFoundation                 0x182d11024 -[_CFXNotificationRegistrar find:object:observer:enumerator:]
9  CoreFoundation                 0x182bc9f60 _CFXNotificationPost
10 Foundation                     0x183619348 -[NSNotificationCenter postNotificationName:object:userInfo:]
11 UIKit                          0x18c46ec70 __47-[UIApplication _applicationDidEnterBackground]_block_invoke
12 UIKit                          0x18c57ace8 +[UIViewController _performWithoutDeferringTransitions:]
13 UIKit                          0x18c46eac8 -[UIApplication _applicationDidEnterBackground]
14 UIKit                          0x18c7062f0 -[__UICanvasLifecycleMonitor_Compatability deactivateEventsOnly:withContext:forceExit:completion:]
15 UIKit                          0x18ce8a878 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke
16 UIKit                          0x18ce8a6a4 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]
17 UIKit                          0x18cbf830c __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke
18 UIKit                          0x18cd9140c _performActionsWithDelayForTransitionContext
19 UIKit                          0x18cbf81bc -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]
20 UIKit                          0x18c9dc870 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:]
21 UIKit                          0x18c87e3b8 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:]
22 FrontBoardServices             0x1853e6ca4 __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.362
23 libdispatch.dylib              0x18267ea14 _dispatch_client_callout
24 libdispatch.dylib              0x182686200 _dispatch_block_invoke_direct$VARIANT$mp
25 FrontBoardServices             0x18541a7f8 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
26 FrontBoardServices             0x18541a49c -[FBSSerialQueue _performNext]
27 FrontBoardServices             0x18541aa38 -[FBSSerialQueue _performNextFromRunLoopSource]
28 CoreFoundation                 0x182caa97c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
29 CoreFoundation                 0x182caa8fc __CFRunLoopDoSource0
30 CoreFoundation                 0x182caa184 __CFRunLoopDoSources0
31 CoreFoundation                 0x182ca7d5c __CFRunLoopRun
32 CoreFoundation                 0x182bc7e58 CFRunLoopRunSpecific
33 GraphicsServices               0x184a94f84 GSEventRunModal
34 UIKit                          0x18c2687bc UIApplicationMain
35 PrintOSMobile                  0x1009a012c main (main.m:14)
36 libdyld.dylib                  0x1826e456c start

#0. Crashed: com.twitter.crashlytics.ios.exception
0  PrintOSMobile                  0x1009fa124 CLSProcessRecordAllThreads + 4335542564
1  PrintOSMobile                  0x1009fa124 CLSProcessRecordAllThreads + 4335542564
2  PrintOSMobile                  0x1009fa544 CLSProcessRecordAllThreads + 4335543620
3  PrintOSMobile                  0x1009eb1f8 CLSHandler + 4335481336
4  PrintOSMobile                  0x1009f883c __CLSExceptionRecord_block_invoke + 4335536188
5  libdispatch.dylib              0x18267ea14 _dispatch_client_callout + 16
6  libdispatch.dylib              0x182687618 _dispatch_queue_barrier_sync_invoke_and_complete + 56
7  PrintOSMobile                  0x1009f82e8 CLSExceptionRecord + 4335534824
8  PrintOSMobile                  0x1009f8124 CLSExceptionRecordNSException + 4335534372
9  PrintOSMobile                  0x1009f7d84 CLSTerminateHandler() + 4335533444
10 libc++abi.dylib                0x181f3854c std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x181f385b8 std::terminate() + 60
12 libobjc.A.dylib                0x181f4876c _destroyAltHandlerList + 10
13 libdispatch.dylib              0x18267ea28 _dispatch_client_callout + 36
14 libdispatch.dylib              0x182686200 _dispatch_block_invoke_direct$VARIANT$mp + 288
15 FrontBoardServices             0x18541a7f8 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
16 FrontBoardServices             0x18541a49c -[FBSSerialQueue _performNext] + 404
17 FrontBoardServices             0x18541aa38 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
18 CoreFoundation                 0x182caa97c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
19 CoreFoundation                 0x182caa8fc __CFRunLoopDoSource0 + 88
20 CoreFoundation                 0x182caa184 __CFRunLoopDoSources0 + 204
21 CoreFoundation                 0x182ca7d5c __CFRunLoopRun + 1048
22 CoreFoundation                 0x182bc7e58 CFRunLoopRunSpecific + 436
23 GraphicsServices               0x184a94f84 GSEventRunModal + 100
24 UIKit                          0x18c2687bc UIApplicationMain + 236
25 PrintOSMobile                  0x1009a012c main (main.m:14)
26 libdyld.dylib                  0x1826e456c start + 4

#1. Appsee
0  libsystem_kernel.dylib         0x18281460c __semwait_signal + 8
1  libsystem_c.dylib              0x18272cf70 nanosleep + 212
2  Foundation                     0x1837202a8 +[NSThread sleepForTimeInterval:] + 136
3  PrintOSMobile                  0x100bf7a40 -[UVVideoRecorder finishRecording:] + 4337629760
4  PrintOSMobile                  0x100c31be8 __27-[UVManager finishSession:]_block_invoke + 4337867752
5  PrintOSMobile                  0x100c3ad14 __45-[UVDispatcher runInBackground:continueInBg:]_block_invoke.13 + 4337904916
6  libdispatch.dylib              0x18267ea54 _dispatch_call_block_and_release + 24
7  libdispatch.dylib              0x18267ea14 _dispatch_client_callout + 16
8  libdispatch.dylib              0x18268896c _dispatch_queue_serial_drain$VARIANT$mp + 528
9  libdispatch.dylib              0x1826892fc _dispatch_queue_invoke$VARIANT$mp + 340
10 libdispatch.dylib              0x182689d20 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 404
11 libdispatch.dylib              0x18269203c _dispatch_workloop_worker_thread$VARIANT$mp + 644
12 libsystem_pthread.dylib        0x182926f1c _pthread_wqthread + 932
13 libsystem_pthread.dylib        0x182926b6c start_wqthread + 4

#2. com.pinterest.PINDiskCache Asynchronous Queue
0  libsystem_kernel.dylib         0x1827f35a4 semaphore_wait_trap + 8
1  libdispatch.dylib              0x182680f04 _dispatch_sema4_wait$VARIANT$mp + 24
2  libdispatch.dylib              0x1826818b4 _dispatch_semaphore_wait_slow + 140
3  PrintOSMobile                  0x100bd5da4 __44-[Intercom_PINDiskCache objectForKey:block:]_block_invoke + 4337491364
4  libdispatch.dylib              0x18267ea54 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x18267ea14 _dispatch_client_callout + 16
6  libdispatch.dylib              0x182686f08 _dispatch_continuation_pop$VARIANT$mp + 428
7  libdispatch.dylib              0x18268580c _dispatch_async_redirect_invoke$VARIANT$mp + 604
8  libdispatch.dylib              0x18268bcf4 _dispatch_root_queue_drain + 600
9  libdispatch.dylib              0x18268ba38 _dispatch_worker_thread3 + 120
10 libsystem_pthread.dylib        0x18292706c _pthread_wqthread + 1268
11 libsystem_pthread.dylib        0x182926b6c start_wqthread + 4

#3. Thread
0  libsystem_kernel.dylib         0x182814d80 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x182927080 _pthread_wqthread + 1288
2  libsystem_pthread.dylib        0x182926b6c start_wqthread + 4

#4. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1827f3568 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1827f33e0 mach_msg + 72
2  CoreFoundation                 0x182caa308 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x182ca7ed4 __CFRunLoopRun + 1424
4  CoreFoundation                 0x182bc7e58 CFRunLoopRunSpecific + 436
5  Foundation                     0x18361f594 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x18363e9ac -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                          0x18cdd27e8 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x1837210f4 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x1829282b4 _pthread_body + 308
10 libsystem_pthread.dylib        0x182928180 _pthread_body + 310
11 libsystem_pthread.dylib        0x182926b74 thread_start + 4

#5. Thread
0  libsystem_kernel.dylib         0x182814d80 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x182927080 _pthread_wqthread + 1288
2  libsystem_pthread.dylib        0x182926b6c start_wqthread + 4

#6. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x1827f3568 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1827f33e0 mach_msg + 72
2  PrintOSMobile                  0x1009e6244 CLSMachExceptionServer + 4335460932
3  libsystem_pthread.dylib        0x1829282b4 _pthread_body + 308
4  libsystem_pthread.dylib        0x182928180 _pthread_body + 310
5  libsystem_pthread.dylib        0x182926b74 thread_start + 4

#7. com.google.fira.worker
0  libsystem_kernel.dylib         0x1827f5818 lstat + 8
1  Foundation                     0x18362e0e4 _NSFileExistsAtPath + 200
2  Foundation                     0x18362dfec -[NSFileManager fileExistsAtPath:] + 120
3  PrintOSMobile                  0x100a9f164 -[FIRInstanceIDBackupExcludedPlist contentAsDictionary] + 4336218468
4  PrintOSMobile                  0x100aa4580 -[FIRInstanceIDKeyPairStore validCachedKeyPairWithSubtype:error:] + 4336240000
5  PrintOSMobile                  0x100aa3fac -[FIRInstanceIDKeyPairStore loadKeyPairWithError:] + 4336238508
6  PrintOSMobile                  0x100aa3d30 -[FIRInstanceIDKeyPairStore appIdentityWithError:] + 4336237872
7  PrintOSMobile                  0x100a97ea4 -[FIRInstanceID(Private) appInstanceID:] + 4336189092
8  PrintOSMobile                  0x100a49100 -[FIRAIdentity firebaseInstanceID] + 4335866112
9  PrintOSMobile                  0x100a52fd0 -[FIRAMeasurement createRawEventMetadataWithUserAttributes:] + 4335906768
10 PrintOSMobile                  0x100a509e8 __43-[FIRAMeasurement writeEventOnWorkerQueue:]_block_invoke.1010 + 4335897064
11 PrintOSMobile                  0x100a33714 -[FIRASqliteStore performTransaction:] + 4335777556
12 PrintOSMobile                  0x100a4fa1c -[FIRAMeasurement writeEventOnWorkerQueue:] + 4335893020
13 PrintOSMobile                  0x100a4f320 -[FIRAMeasurement handleEventOnWorkerQueue:] + 4335891232
14 PrintOSMobile                  0x100a5f520 __52-[FIRAScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 4335957280
15 libdispatch.dylib              0x18267ea54 _dispatch_call_block_and_release + 24
16 libdispatch.dylib              0x18267ea14 _dispatch_client_callout + 16
17 libdispatch.dylib              0x18268896c _dispatch_queue_serial_drain$VARIANT$mp + 528
18 libdispatch.dylib              0x1826892fc _dispatch_queue_invoke$VARIANT$mp + 340
19 libdispatch.dylib              0x182689d20 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 404
20 libdispatch.dylib              0x18269203c _dispatch_workloop_worker_thread$VARIANT$mp + 644
21 libsystem_pthread.dylib        0x182926f1c _pthread_wqthread + 932
22 libsystem_pthread.dylib        0x182926b6c start_wqthread + 4

#8. com.pinterest.PINDiskCache Asynchronous Queue
0  libsystem_kernel.dylib         0x1827f3580 semaphore_signal_trap + 8
1  libdispatch.dylib              0x182680e4c _dispatch_sema4_signal$VARIANT$mp + 28
2  libdispatch.dylib              0x1826817cc _dispatch_semaphore_signal_slow$VARIANT$mp + 48
3  PrintOSMobile                  0x100bd5dcc __44-[Intercom_PINDiskCache objectForKey:block:]_block_invoke + 4337491404
4  libdispatch.dylib              0x18267ea54 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x18267ea14 _dispatch_client_callout + 16
6  libdispatch.dylib              0x182686f08 _dispatch_continuation_pop$VARIANT$mp + 428
7  libdispatch.dylib              0x18268580c _dispatch_async_redirect_invoke$VARIANT$mp + 604
8  libdispatch.dylib              0x18268bcf4 _dispatch_root_queue_drain + 600
9  libdispatch.dylib              0x18268ba38 _dispatch_worker_thread3 + 120
10 libsystem_pthread.dylib        0x18292706c _pthread_wqthread + 1268
11 libsystem_pthread.dylib        0x182926b6c start_wqthread + 4

#9. io.branch.sdk.network.queue (QOS: USER_INTERACTIVE)
0  libsystem_kernel.dylib         0x182814be0 __ulock_wait + 8
1  libdispatch.dylib              0x1826810f0 _dispatch_ulock_wait + 48
2  libdispatch.dylib              0x182681248 _dispatch_thread_event_wait_slow$VARIANT$mp + 36
3  libdispatch.dylib              0x18268cb64 _dispatch_sync_wait + 448
4  Branch                         0x100fe12c0 BNCPerformBlockOnMainThreadSync + 76
5  Branch                         0x100fe13f8 -[Branch processRequest:response:error:] + 244
6  Branch                         0x100fe1f7c __30-[Branch processNextQueueItem]_block_invoke_2 + 60
7  Branch                         0x100fd1898 __75-[BNCServerInterface genericHTTPRequest:retryNumber:callback:retryHandler:]_block_invoke + 1044
8  Branch                         0x100fcc60c __36-[BNCNetworkService startOperation:]_block_invoke + 620
9  CFNetwork                      0x18328ca8c __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 32
10 CFNetwork                      0x1832a53e0 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 152
11 Foundation                     0x1836fbba0 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
12 Foundation                     0x18363b894 -[NSBlockOperation main] + 72
13 Foundation                     0x18362b4c4 -[__NSOperationInternal _start:] + 848
14 libdispatch.dylib              0x18267ea14 _dispatch_client_callout + 16
15 libdispatch.dylib              0x182686200 _dispatch_block_invoke_direct$VARIANT$mp + 288
16 libdispatch.dylib              0x18267ea14 _dispatch_client_callout + 16
17 libdispatch.dylib              0x182686200 _dispatch_block_invoke_direct$VARIANT$mp + 288
18 libdispatch.dylib              0x1826860ac dispatch_block_perform$VARIANT$mp + 104
19 Foundation                     0x1836fd878 __NSOQSchedule_f + 376
20 libdispatch.dylib              0x18267ea14 _dispatch_client_callout + 16
21 libdispatch.dylib              0x182686f08 _dispatch_continuation_pop$VARIANT$mp + 428
22 libdispatch.dylib              0x18268580c _dispatch_async_redirect_invoke$VARIANT$mp + 604
23 libdispatch.dylib              0x18268bcf4 _dispatch_root_queue_drain + 600
24 libdispatch.dylib              0x18268ba38 _dispatch_worker_thread3 + 120
25 libsystem_pthread.dylib        0x18292706c _pthread_wqthread + 1268
26 libsystem_pthread.dylib        0x182926b6c start_wqthread + 4

#10. Thread
0  libsystem_pthread.dylib        0x182926b68 start_wqthread + 122

#11. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1827f3568 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1827f33e0 mach_msg + 72
2  CoreFoundation                 0x182caa308 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x182ca7ed4 __CFRunLoopRun + 1424
4  CoreFoundation                 0x182bc7e58 CFRunLoopRunSpecific + 436
5  CFNetwork                      0x1834b6718 -[__CoreSchedulingSetRunnable runForever] + 780
6  Foundation                     0x1837210f4 __NSThread__start__ + 996
7  libsystem_pthread.dylib        0x1829282b4 _pthread_body + 308
8  libsystem_pthread.dylib        0x182928180 _pthread_body + 310
9  libsystem_pthread.dylib        0x182926b74 thread_start + 4

#12. GAIThread
0  libsystem_kernel.dylib         0x1827f3568 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1827f33e0 mach_msg + 72
2  CoreFoundation                 0x182caa308 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x182ca7ed4 __CFRunLoopRun + 1424
4  CoreFoundation                 0x182bc7e58 CFRunLoopRunSpecific + 436
5  Foundation                     0x18361f594 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x18367156c -[NSRunLoop(NSRunLoop) run] + 88
7  PrintOSMobile                  0x1009c69d8 +[GAI threadMain:] + 4335331800
8  Foundation                     0x1837210f4 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x1829282b4 _pthread_body + 308
10 libsystem_pthread.dylib        0x182928180 _pthread_body + 310
11 libsystem_pthread.dylib        0x182926b74 thread_start + 4

#13. Thread
0  libsystem_pthread.dylib        0x182926b68 start_wqthread + 122

#14. com.pinterest.PINDiskCache Asynchronous Queue
0  libsystem_kernel.dylib         0x1827f35a4 semaphore_wait_trap + 8
1  libdispatch.dylib              0x182680f04 _dispatch_sema4_wait$VARIANT$mp + 24
2  libdispatch.dylib              0x1826818b4 _dispatch_semaphore_wait_slow + 140
3  PrintOSMobile                  0x100bd5da4 __44-[Intercom_PINDiskCache objectForKey:block:]_block_invoke + 4337491364
4  libdispatch.dylib              0x18267ea54 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x18267ea14 _dispatch_client_callout + 16
6  libdispatch.dylib              0x182686f08 _dispatch_continuation_pop$VARIANT$mp + 428
7  libdispatch.dylib              0x18268580c _dispatch_async_redirect_invoke$VARIANT$mp + 604
8  libdispatch.dylib              0x18268bcf4 _dispatch_root_queue_drain + 600
9  libdispatch.dylib              0x18268ba38 _dispatch_worker_thread3 + 120
10 libsystem_pthread.dylib        0x18292706c _pthread_wqthread + 1268
11 libsystem_pthread.dylib        0x182926b6c start_wqthread + 4

#15. Thread
0  libsystem_pthread.dylib        0x182926b68 start_wqthread + 122

#16. Thread
0  libsystem_kernel.dylib         0x1827f35bc semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x182681000 _dispatch_sema4_timedwait$VARIANT$mp + 84
2  libdispatch.dylib              0x182681870 _dispatch_semaphore_wait_slow + 72
3  libdispatch.dylib              0x18268d1d8 _dispatch_worker_thread + 256
4  libsystem_pthread.dylib        0x1829282b4 _pthread_body + 308
5  libsystem_pthread.dylib        0x182928180 _pthread_body + 310
6  libsystem_pthread.dylib        0x182926b74 thread_start + 4

#17. com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x1827f3568 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1827f33e0 mach_msg + 72
2  CoreFoundation                 0x182caa308 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x182ca7ed4 __CFRunLoopRun + 1424
4  CoreFoundation                 0x182bc7e58 CFRunLoopRunSpecific + 436
5  Foundation                     0x18361f594 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  PrintOSMobile                  0x100bf43cc -[Intercom__SRRunLoopThread main] + 4337615820
7  Foundation                     0x1837210f4 __NSThread__start__ + 996
8  libsystem_pthread.dylib        0x1829282b4 _pthread_body + 308
9  libsystem_pthread.dylib        0x182928180 _pthread_body + 310
10 libsystem_pthread.dylib        0x182926b74 thread_start + 4

#18. Thread
0  libsystem_pthread.dylib        0x182926b68 start_wqthread + 122

#19. Thread
0  libsystem_pthread.dylib        0x182926b68 start_wqthread + 122

#20. com.apple.NSURLSession-work
0  CFNetwork                      0x1833e2624 URLConnectionClient_Classic::_delegate_didReceiveDataArray() + 6
1  CFNetwork                      0x1833df0ec URLConnectionClient::_loaderClientEvent_DidReceiveData(__CFArray const*) + 332
2  CFNetwork                      0x1833e94b0 invocation function for block in URLConnectionLoader::protocolDidLoadData(__CFData const*, long long) + 44
3  CFNetwork                      0x183321cf4 invocation function for block in ClassicURLConnection::withLoaderClientAsync(void (LoaderClientInterface*) block_pointer) + 28
4  CFNetwork                      0x1833dcd54 invocation function for block in URLConnectionInstanceData::withWorkQueueAsync(void () block_pointer) const + 28
5  libdispatch.dylib              0x18267ea54 _dispatch_call_block_and_release + 24
6  libdispatch.dylib              0x18267ea14 _dispatch_client_callout + 16
7  libdispatch.dylib              0x18268896c _dispatch_queue_serial_drain$VARIANT$mp + 528
8  libdispatch.dylib              0x1826892fc _dispatch_queue_invoke$VARIANT$mp + 340
9  libdispatch.dylib              0x182689d20 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 404
10 libdispatch.dylib              0x18269203c _dispatch_workloop_worker_thread$VARIANT$mp + 644
11 libsystem_pthread.dylib        0x182926f1c _pthread_wqthread + 932
12 libsystem_pthread.dylib        0x182926b6c start_wqthread + 4

#21. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x182814534 __select + 8
1  CoreFoundation                 0x182cb2840 __CFSocketManager + 644
2  libsystem_pthread.dylib        0x1829282b4 _pthread_body + 308
3  libsystem_pthread.dylib        0x182928180 _pthread_body + 310
4  libsystem_pthread.dylib        0x182926b74 thread_start + 4

**Comment by jtreanor** [comment]
Hi @osama-taha,

Do you have any more details about this crash? Has it occurred more than once?

Unfortunately the crash is not very descriptive so it is difficult to understand what is happening here.

**Comment by bboyle18** [comment]
Fixed in [Release 4.1.5](https://github.com/intercom/intercom-ios/releases/tag/4.1.5)
Thanks for reporting.
