### ISSUE TITLE
App is killed by system because Intercom background task is not finished

### ISSUE THREAD

**Issue by ddeneka-ynd** [intercom/intercom-ios#341]
## Version info
  - Intercom for iOS version: 3.2.12
  - iOS version: 11.1

## Expected behavior
  - Intercom ends its own background tasks so app is not killed by system

## Actual behavior
  - App is killed by system when entering background
## Steps to reproduce
 1. Intercom is initialized in appDidFinishLaunching
 2. Start app
 3. Switch between background&foreground multiple times
 4. App is killed by system due unfinished Background Tasks

## Logs
Nov 24 18:44:50 iPhone-7-Plus assertiond[2254] <Notice>: [MyApp:45983] Forcing crash report with description: MyApp:45983 has active assertions beyond permitted time: 
<BKProcessAssertion: 0x100ecbce0; "io.intercom.ios.nexus" (finishTask:180s); id:\M-b\M^@\M-&0A9C0B87C5AA> (owner: MyApp:45983), <BKProcessAssertion: 0x100e61830; "io.intercom.ios.nexus" (finishTask:180s); id:\M-b\M^@\M-&B315D2FE5AEC> (owner: MyApp:45983), <BKProcessAssertion: 0x100dee9f0; "io.intercom.ios.nexus" (finishTask:180s); id:\M-b\M^@\M-&462B715638AA> (owner: MyApp:45983), <BKProcessAssertion: 0x100ea0690; "io.intercom.ios.nexus" (finishTask:180s); id:\M-b\M^@\M-&C82EC347E1F5> (owner: MyApp:45983)

**Comment by bboyle18** [comment]
Thanks for reporting this @ddeneka-ynd 👍 
We'll look into why this might be happening.

Brian

**Comment by bboyle18** [comment]
Hi @ddeneka-ynd 👋 
Would you have the original logs for this issue?
It will help give a more complete picture of what exactly is happening.

Thanks

Brian

**Comment by bboyle18** [comment]
Hi @ddeneka-ynd 
 
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Brian
