### ISSUE TITLE
Ability to move the default messenger launcher anywhere in the app

### ISSUE THREAD

**Issue by iad24** [intercom/intercom-ios#342]
## Version info
  - Intercom for iOS version: 4.1.3
  - iOS version: ios11

## Expected behavior
Can programmatically (or better for user to move it in the screen) the messenger launcher anywhere in the screen
## Actual behaviour
Its always in the bottom right of the screen
Right now its blocking the default tab bar

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs

![unadjustednonraw_thumb_11](https://user-images.githubusercontent.com/15226261/33305128-84276b66-d447-11e7-9002-60ceb6e21db4.jpg)

**Comment by DaleCantwell** [comment]
Hi @iad24,
Thanks for getting in touch, we already a method that should help handle this:

```ObjC
/*!
 This method allows you to set a fixed bottom padding for in app messages and the launcher.
 It is useful if your app has a tab bar or similar UI at the bottom of your window.

 @param bottomPadding The size of the bottom padding in points.
 */
+ (void)setBottomPadding:(CGFloat)bottomPadding;
```

Calling `setBottomPadding` will allow you to move the launcher and any in-app messages above your tab bar.

Let us know if you run into any issues.
