### ISSUE TITLE
application:openURL:options: not called unless application:didReceiveRemoteNotification:fetchCompletionHandler: is implemented

### ISSUE THREAD

**Issue by adambolcsfoldi** [intercom/intercom-ios#343]
## Version info
  - Intercom for iOS version: 4.1.3
  - iOS version: 10.3.1

## Expected behaviour

`application:openURL:options:` will be called with the push notification URI if `IntercomAutoIntegratePushNotifications` is not set to `NO` in the app's `Info.plist`

## Actual behavior

`application:didReceiveRemoteNotification:fetchCompletionHandler:` needs to be implemented in order for `application:openURL:options:` to be called.

## Steps to reproduce
 1. Don't implement `application:didReceiveRemoteNotification:fetchCompletionHandler:` in your app delegate.
 2. Send push message to app with `iOS URI`.
 3. Observe `application:openURL:options:` not being called.

**Comment by bboyle18** [comment]
Thanks for reporting this @adambolcsfoldi 👍 
We'll look investigate and get back to you if we have any questions.

Brian

**Comment by bboyle18** [comment]
Hi @adambolcsfoldi 👋 
I'm looking into this at the moment and I just need a little more info from you.
- Are you sending an intercom push notification with a URI or one of your own push notifications?
- Would you be able to share the JSON payload of the push notification in question as it will help a lot in re-creating this issue.

Thanks

Brian

**Comment by adambolcsfoldi** [comment]
@bboyle18 

We're sending a push notification with the `iOS URI` set to a link to our website but with the protocol `fanmiles://` instead of `https://`. 
E.g. 
`fanmiles://www.fanmiles.com/us/en/earns/5a324fcb4e236506924c5e3f/Connect-and-follow-ESL-Gaming.html`

**Comment by bboyle18** [comment]
Thanks @adambolcsfoldi 
And should your app handle opening this in a webview when it sees `fanmiles://` as the prefix?
If you were to put simple `https://google.com` in there what happens?

Thanks

Brian

**Comment by adambolcsfoldi** [comment]
We handle the `fanmiles://` natively in the app, redirecting to the corresponding content.

With the fix at the top, `application:openURL:options:` gets called for `fanmiles://` URIs but not `https://`.
Without the fix it doesn't get called for either.

**Comment by bboyle18** [comment]
Thanks @adambolcsfoldi 
What fix are you referring to?

**Comment by bboyle18** [comment]
Thanks for clarifying. 👍

**Comment by bboyle18** [comment]
Hi @adambolcsfoldi 
 
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Brian
