### ISSUE TITLE
Retrieve set user attributes

### ISSUE THREAD

**Issue by mhemmings** [intercom/intercom-ios#344]
Would be amazing, especially for debugging, if there was a method to get back the currently set user attributes (`ICMUserAttributes`)

**Comment by bboyle18** [comment]
Hi @mhemmings 👋 

Thanks for taking the time to send in this feature request. 👍 
Can I ask specifically what the use case for this is? This will help us better understand the problem.

Thanks

Brian

**Comment by mhemmings** [comment]
Hey!
tldr the use case we have today is due to an old issue, we have a small number of users who are set to the wrong id.
On app launch we'd like to check the ids are set correctly, and if not do a logout and reregister. I've spoken to support in the past and you were understandably not wanting us simply do a reset on _every_ user app launch, but just on the small percentage of broken users.

**Comment by bboyle18** [comment]
That makes sense. You should be able to do that already.
e.g.
```
ICMUserAttributes *update = [ICMUserAttributes new];
update.name = @"Brian";
update.phone = @"0874182987";
NSLog(@"user_attributes : %@", update.attributes);
```
The `attributes` property on `ICMUserAttributes` will give you a dictionary of the currently set user attributes.

Hope this helps

Brian

**Comment by bboyle18** [comment]
Hi @mhemmings 
Can you let me know if this works for you, so that I can close the issue?
Thanks

Brian

**Comment by mhemmings** [comment]
I think we've managed to work things out, happy to close

**Comment by jtreanor** [comment]
Hi @bboyle18 @mhemmings 👋 

I think there might be a slight misunderstanding here. There is currently no way to retrieve the currently set attributes. Checking the `ICMUserAttributes` object will only provide the properties you have just set.

We'll consider this as a feature request though!

**Comment by mhemmings** [comment]
Yeah there was some confusion, but I was too polite to mention and I think we actually sorted it another way!
Saying that, yes it would be good to get the attributes back out to see what the current session is using, so consider my +1 for that 😄
