### ISSUE TITLE
Booleans not getting set correctly

### ISSUE THREAD

**Issue by mhemmings** [intercom/intercom-ios#345]
## Version info
  - Intercom for iOS version: 4.1.3
  - iOS version: 11.1.2

## Expected behavior

Setting custom user attributes and event metadata to booleans (using `@TRUE`/`@FALSE`) should show as booleans inside Intercom

## Actual behavior

Setting custom user attributes and event metadata to booleans (using `@TRUE`/`@FALSE`) shows as `1` and `0` inside Intercom.
H**owever, this is only for new properties. When we use a property that has been defined this way in old SDK versions (2.x), Intercom correctly sets it to `true` or `false`**

## Steps to reproduce
Set a new attribute to `@TRUE`. It appears as `1` in Intercom.
Set an attribute that is already defined for other users correctly as booleans (from older SDK versions) to `@TRUE`. It appears as `true` in Intercom as expected.

## Logs

**Comment by bboyle18** [comment]
Thanks for reporting this @mhemmings 
We'll investigate and get back to you here.
Brian

**Comment by jtreanor** [comment]
Hi @mhemmings,

The problem here is that you are using `@TRUE` instead of `@YES`. `YES` and `NO` are the correct boolean values to be used in Objective C. `NSJSONSerialisation` will only correctly serialise these, which is why you are seeing this problem.

I'm unsure why using `@TRUE` could have been working previously.
Let me know if you have any questions.

James

**Comment by jtreanor** [comment]
Just adding a little more detail here. The following code:
```
NSData *jsonData = [NSJSONSerialization dataWithJSONObject:@{@"@TRUE": @TRUE, @"@YES": @YES} options:0 error:nil];
NSLog(@"%@", [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding]);
```

Outputs this:
```
{"@TRUE":1,"@YES":true}
```

Hopefully this helps clear up the difference between `@YES` and `@TRUE`.
