### ISSUE TITLE
Expand image in article

### ISSUE THREAD

**Issue by iad24** [intercom/intercom-ios#347]
## Version info
  - Intercom for iOS version: 4.1.3
  - iOS version: ios11

## Expected behavior
When reads an article and the image embedded is too small. 
User should be able to click on the image to expand it

## Actual behavior
Clicking on the image does nothing

## Steps to reproduce
 1. Let admin send the user with image in it
 2. User cannot read the text in the image because its too small
 3. 

## Logs

**Comment by bboyle18** [comment]
Hi @iad24 👋 
Thanks for this feedback. We'll take this onboard as a feature request 👍 

Cheers

Brian
