### ISSUE TITLE
Can't copy text in chat

### ISSUE THREAD

**Issue by Bjornftw** [intercom/intercom-ios#349]
## Version info
  - Intercom for iOS version: 4.1.4
  - iOS version: 11.2

## Expected behavior
Copy text in a chat. Sometimes users need to copy a long URL/String. 

## Actual behavior
Users can't copy text that I've (team) already sent. 

## Steps to reproduce
 1. Start an Intercom chat
 2. Try to copy an answer from the team.

**Comment by bboyle18** [comment]
Hi @Bjornftw 👋 
Thanks for getting in touch. 
Copying the content of a message is a feature that we don't currently support.
We're constantly looking for user feedback on our messenger so we will take this on board as a feature request.

Thanks

Brian
