### ISSUE TITLE
Cocoapods install taking forever

### ISSUE THREAD

**Issue by jpike88** [intercom/intercom-ios#351]
This is my terminal right now and I simply can't install it...

![screen shot 2017-12-17 at 9 48 55 pm](https://user-images.githubusercontent.com/9585787/34080645-22bc3b04-e374-11e7-97e7-81388f73d4d7.png)

**Comment by jpike88** [comment]
https://github.com/intercom/intercom-ios/issues/351

**Comment by bboyle18** [comment]
Hi @jpike88 👋 

Thanks for getting in touch.
I've tested out a pod install for Intercom just now and I had no problems. Our binary file has also remained constant for the last while at ~22MB. 
The only thing I can think of is that there was an issue with GitHub at the time you were running pod install that affected the time it took to download the binary.

I'm going to close the issue but if you consistently have this issue just let me know.

Brian
