### ISSUE TITLE
Crash in [Intercom_IntercomConversationCollectionViewController collectionView:cellForItemAtIndexPath:]

### ISSUE THREAD

**Issue by crontab** [intercom/intercom-ios#353]
## Version info
  - Intercom for iOS version: 4.1.4
  - iOS version: all 9, 10 and 11 versions

## Steps to reproduce
We couldn't reproduce it but we get crash reports occurring approximately in 1 out 1000 sessions.

## Logs

```
Fatal Exception: NSRangeException*** -[__NSArrayM objectAtIndexedSubscript:]: index 13 beyond bounds [0 .. 12]
Fatal Exception: NSRangeException
0  CoreFoundation                 0x181e7e364 __exceptionPreprocess
1  libobjc.A.dylib                0x1810c4528 objc_exception_throw
2  CoreFoundation                 0x181e16e9c _CFArgv
3  CoreFoundation                 0x181e03fd8 -[__NSArrayM removeAllObjects]
4  Cuvva                          0x104f5eec8 -[Intercom_IntercomConversationCollectionViewController collectionView:cellForItemAtIndexPath:]
5  UIKit                          0x18bde8854 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:]
6  UIKit                          0x18b3bf124 -[UICollectionView _updateVisibleCellsNow:]
7  UIKit                          0x18b3b9de0 -[UICollectionView layoutSubviews]
8  UIKit                          0x18b35cf00 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
9  QuartzCore                     0x185ec1998 -[CALayer layoutSublayers]
10 QuartzCore                     0x185ec5b20 CA::Layer::layout_if_needed(CA::Transaction*)
11 UIKit                          0x18b371ccc -[UIView(Hierarchy) layoutBelowIfNeeded]
12 UIKit                          0x18bdff4b8 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:]
13 UIKit                          0x18bdff3a0 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:]
14 UIKit                          0x18bdff324 -[UICollectionView _performBatchUpdates:completion:invalidationContext:]
15 UIKit                          0x18b51b2b0 -[UICollectionView performBatchUpdates:completion:]
16 Cuvva                          0x104f5afa8 -[Intercom_IntercomConversationCollectionViewController performBatchUpdates:completion:]
17 Cuvva                          0x104f5ca70 -[Intercom_IntercomConversationCollectionViewController setConversationParts:completion:]
18 Cuvva                          0x104f5cf8c -[Intercom_IntercomConversationCollectionViewController removeConversationPart:]
19 Cuvva                          0x1050119d0 -[ICMNativeConversationContentViewController removeAllTypingParts:]
20 Foundation                     0x18287c5b8 __NSFireTimer
21 CoreFoundation                 0x181e26fc0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
22 CoreFoundation                 0x181e26ce4 __CFRunLoopDoTimer
23 CoreFoundation                 0x181e264e4 __CFRunLoopDoTimers
24 CoreFoundation                 0x181e240cc __CFRunLoopRun
25 CoreFoundation                 0x181d43e58 CFRunLoopRunSpecific
26 GraphicsServices               0x183bf0f84 GSEventRunModal
27 UIKit                          0x18b3c367c UIApplicationMain
28 Cuvva                          0x104d212dc main (main.m:16)
29 libdyld.dylib                  0x18186056c start
```

Because the crash happens in `[__NSArrayM removeAllObjects]` which is supposed to remove all objects but fails at specifying the correct range, this looks like a multithreading issue to me, i.e. one of the elements is removed after removeAllObjects calls the underlying method. But I may be wrong in this assumption of course.

**Comment by bboyle18** [comment]
Hi @crontab 👋 

Thanks for reporting this.
Would it be possible to share a link to the crash in crashlytics?
You assumption about the cause of the crash is probably correct, we are already tracking a similar bug internally. As I'm sure you can appreciate, its very difficult to re-create and therefore fix.

I'll take another pass at it though and update you here if I find anything.

Cheers

Brian

**Comment by crontab** [comment]
Hi @bboyle18 

I don't think I can publicly share a link to a Crashlytics page (unless there is a way I'm not aware of). I just checked the other threads in the report, none of them are in the Intercom framework. Other than that it's iOS versions breakdown which is pretty much all versions we currently support. Let me know if you need any other information from the crash reports.

Cheers,

Hovik

**Comment by bboyle18** [comment]
There should be a shareable link you can send. See the attached screenshot

![cl-2](https://user-images.githubusercontent.com/3185423/34211714-dd5cc1ee-e591-11e7-9e25-1396b81bf0fe.png)

**Comment by crontab** [comment]
@bboyle18 oops, missed it somehow :)

http://crashes.to/s/2f3c7e42641

**Comment by siberianisaev** [comment]
same issue http://crashes.to/s/35224d6bcbe Intercom (4.1.9)

**Comment by bboyle18** [comment]
Hi @crontab @siberianisaev  
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Brian
