### ISSUE TITLE
Intercom.presentMessenger doesn't display messenger if called to soon with come other Intercom calls

### ISSUE THREAD

**Issue by biboran** [intercom/intercom-ios#354]
## Version info
  - Intercom for iOS version:  4.1.5
  - iOS version: 10 - 11.2

## Expected behavior
Calling `Intercom.presentMessenger` should present messenger regardless of other Intercom calls

## Actual behavior
Calling `Intercom.setApiKey` or `Intercom.registerUser` immediately followed by `Intercom.presentMessenger` most of the time doesn't display messenger if `Intercom.registerUser` was called in the previous runs. Also no errors are displayed. 

So it works as expected the first time but after that messenger will not present unless an artificial delay is added. I suspect there is a race condition and it might be dependent on internet connection speed.

## Steps to reproduce
 1. Make a new project with Intercom pod
 2. Run project a couple or times with:

```swift
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        Intercom.setApiKey("YOURKEY", forAppId: "YOURAPPID")
        Intercom.presentMessenger()
        
    }
```

or

```swift
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        Intercom.setApiKey("YOURKEY", forAppId: "YOURAPPID")
        
        Timer.scheduledTimer(
            withTimeInterval: 5,
            repeats: false,
            block: { _ in
                Intercom.registerUser(withUserId: "YOURUSERID")
                Intercom.presentMessenger()
        })
        
    }
```

note that this code presents messenger: 

```swift
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        Intercom.setApiKey("YOURKEY", forAppId: "YOURAPPID")
        
        Timer.scheduledTimer(
            withTimeInterval: 5,
            repeats: false,
            block: { _ in
                Intercom.presentMessenger()
        })
        
    }
```

**Comment by bboyle18** [comment]
Hi @biboran 👋 

Thanks for getting in touch.
When you say `"doesn't display messenger"` do you mean that the messenger window does not appear at all, or the window appears but the user's conversations etc do not display in the messenger?

Thanks

Brian

**Comment by biboran** [comment]
Hi @bboyle18 

Thanks for a quick response! 

Window doesn't appear

**Comment by bboyle18** [comment]
I've managed to re-create this and it is indeed a bug.
However, I think you should be able to work around this. The approach you are using of initialising Intercom, registering a user and presenting the messenger all within `viewDidAppear` is not what we would recommend.
Would you be able to explain your specific use case for doing this? I should be able to help you get this working if I can better understand how you want to launch Intercom in your app.

Thanks

Brian

**Comment by biboran** [comment]
I am not actually doing it in `viewDidAppear`. Since Intercom charges on registration we register user when he taps the support button and then present the messenger. It looks as follows:

Tap -> Get user id from API -> Intercom.registerUser -> Intercom.presentMessenger

**Comment by bboyle18** [comment]
Hi @biboran 
Would you be able to share a sample project of this?
To help understand exactly how you are registering and opening the messenger an exact example would be great.

Thanks

Brian

**Comment by biboran** [comment]
Lets say I have a `Transition` interface:

```swift
protocol Transition {

    func perform(on viewController: UIViewController)

}
```

and a particular implementation `TransitionToIntercom`:

```swift
class TransitionToIntercom: Transition {

    private let profileForm: ProfileForm //This object contains user information 
    init(profileForm: ProfileForm) {
        self.profileForm = profileForm
    }

   func perform(on viewController: UIViewController) {
        Intercom.registerUser(withUserId: profileForm.identification.id)
        let attributes = ICMUserAttributes()
        attributes.phone = profileForm.phone.number
        attributes.name = profileForm.name
        attributes.email = profileForm.email
        Intercom.updateUser(attributes)
        Intercom.presentMessenger()
    }

}
```

now through some push interface that is linked to the button and a call to API I receive `TransitionToIntercom`:

```swift
transitionsSubject.subscribe(onNext: { [unowned self] transition in
            transition.perform(on: self)
        })
```

**Comment by bboyle18** [comment]
Hi @biboran 
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Brian
