### ISSUE TITLE
Prod .pem file not working for manual push notification

### ISSUE THREAD

**Issue by mutablestudio** [intercom/intercom-ios#356]
## Version info
  - Intercom for iOS version: 4.7.1
  - iOS version: 11.2.1

## Expected behavior
receive push notification from manual message

## Actual behavior
no push notification received

## Steps to reproduce
 1. In test app settings, upload the apple prod .pem cert
 2. Select user with notification enabled
 3. Install app with ad-hoc provisioning
 4. Send iOS push notification to selected user from manual message in Dashboard 

## Logs
--

I'm not having any luck sending a manual test message in our test sandbox to a device for a registered user who has notifications enabled. I am the user with the device and I verified the device token was sent to Intercom. When I send a manual message to the user using the Push Notification option the notification never shows up. I can successfully send an in app message so I know it has registered with Intercom correctly.

My app is built from Hockey App, signed with prod cert and ad-hoc provisioning profile. I'm using the prod .pem file in Intercom settings.

Thanks.

**Comment by bboyle18** [comment]
Hi @mutablestudio 

Apologies for the delay in responding here.
Are you still having issues testing push notifications or has this been resolved?

Thanks

Brian

**Comment by bboyle18** [comment]
Closing this issue for now.
Feel free to reopen @mutablestudio if its still a problem you are experiencing.

Brian
