### ISSUE TITLE
Browse photo in camera roll page terminated due to memory issue

### ISSUE THREAD

**Issue by michaeltaiwan** [intercom/intercom-ios#358]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 4.1.18
  - iOS version: 11.2.2

## Expected behavior
Show photo in camera roll page

## Actual behavior
Xcode show: Message from debugger: Terminated due to memory issue

## Steps to reproduce
 1. In Camera Roll Page
 2. Scroll to bottom
 3. Scroll to top
 4. Repeat many times

**Comment by bboyle18** [comment]
Hi @michaeltaiwan 

Apologies for the delay in getting back to you on this.
Could you please tell me roughly how many photos are in your photo library? 
This will help us when trying to re-create the issue.

Thanks

Brian

**Comment by michaeltaiwan** [comment]
I think the number of photo is not the reason for crash, because i scroll slow will not crash.
App crashes when i scroll up or down very fast.

**Comment by bboyle18** [comment]
Hi Michael,

I've been unable to recreate this. I've been testing on an iPhone 7 with around 10k photos.
I've also done a memory analysis of this code to check for memory leaks and nothing shows up.
Its quite difficult to resolve memory issues like this as a lot of the time they are related to the device the app is running on and the number of other processes that are running on that app at the same time.

I'm going to close this issue as a result.
If anyone else is experiencing the same issue on a regular basis, please feel free to re-open.

Brian
