### ISSUE TITLE
Intercom message list and messenger does not show colors as configured

### ISSUE THREAD

**Issue by jorgefernandes** [intercom/intercom-ios#360]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 4.1.8
  - iOS version: 9.0

## Expected behavior
I expect intercom show the background color in messages list in white color and text color os messenger as configured

## Actual behavior
Intercom's message list appears without background, and the messenger with the text in color white, instead the color i set up in chat appearence configuration. Android seems fine.

![intercom-1](https://user-images.githubusercontent.com/415791/35224524-67a1bcbc-ff6c-11e7-9349-9f460ae11906.jpg)

![intercom-2](https://user-images.githubusercontent.com/415791/35224570-8f6d862c-ff6c-11e7-97a5-ee835113cb53.jpg)

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs

**Comment by skylerwshaw** [comment]
@jorgefernandes Can you share your dependencies here or via the Intercom in-app messenger in your Intercom dashboard? It appears that you or a dependency may be overriding/swizzling display APIs.

**Comment by jorgefernandes** [comment]
@skylerwshaw ok. here is my podfile.lock

PODS:
  - Amplitude-iOS (3.14.1)
  - Analytics (3.6.9)
  - AppAuth (0.92.0)
  - Bolts (1.9.0):
    - Bolts/AppLinks (= 1.9.0)
    - Bolts/Tasks (= 1.9.0)
  - Bolts/AppLinks (1.9.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.0)
  - Branch (0.14.12):
    - Branch/Core (= 0.14.12)
    - Branch/without-IDFA (= 0.14.12)
  - Branch/Core (0.14.12)
  - Branch/without-IDFA (0.14.12)
  - CocoaLumberjack (3.2.1):
    - CocoaLumberjack/Default (= 3.2.1)
    - CocoaLumberjack/Extensions (= 3.2.1)
  - CocoaLumberjack/Default (3.2.1)
  - CocoaLumberjack/Extensions (3.2.1):
    - CocoaLumberjack/Default
  - Crashlytics (3.9.3):
    - Fabric (~> 1.7.2)
  - ExpoKit/Core (2.2.1):
    - Amplitude-iOS (~> 3.8)
    - Analytics (~> 3.5)
    - AppAuth (~> 0.4)
    - Branch (~> 0.14.12)
    - CocoaLumberjack (~> 3.2.1)
    - Crashlytics (~> 3.8)
    - Fabric (~> 1.6)
    - FBAudienceNetwork (~> 4.24)
    - FBSDKCoreKit (~> 4.28)
    - FBSDKLoginKit (~> 4.28)
    - FBSDKShareKit (~> 4.28)
    - Google-Mobile-Ads-SDK (~> 7.22.0)
    - GoogleMaps (~> 2.2.0)
    - GoogleSignIn (~> 3.0)
    - GPUImage (~> 0.1.7)
    - lottie-ios (~> 2.1.3)
  - ExpoKit/CPP (2.2.1):
    - ExpoKit/Core
  - Fabric (1.7.2)
  - FBAudienceNetwork (4.27.2)
  - FBSDKCoreKit (4.29.0):
    - Bolts (~> 1.7)
  - FBSDKLoginKit (4.29.0):
    - FBSDKCoreKit
  - FBSDKShareKit (4.29.0):
    - FBSDKCoreKit
  - Firebase/Analytics (4.8.1):
    - Firebase/Core
  - Firebase/Core (4.8.1):
    - FirebaseAnalytics (= 4.0.7)
    - FirebaseCore (= 4.0.14)
  - Firebase/Crash (4.8.1):
    - Firebase/Core
    - FirebaseCrash (= 2.0.2)
  - Firebase/Messaging (4.8.1):
    - Firebase/Core
    - FirebaseMessaging (= 2.0.8)
  - FirebaseAnalytics (4.0.7):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseCore (4.0.14):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseCrash (2.0.2):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - Protobuf (~> 3.1)
  - FirebaseInstanceID (2.0.8):
    - FirebaseCore (~> 4.0)
  - FirebaseMessaging (2.0.8):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - Protobuf (~> 3.1)
  - Google-Mobile-Ads-SDK (7.22.0)
  - GoogleAppUtilities (1.1.2):
    - GoogleSymbolUtilities (~> 1.1)
  - GoogleAuthUtilities (2.0.2):
    - GoogleNetworkingUtilities (~> 1.2)
    - GoogleSymbolUtilities (~> 1.1)
  - GoogleMaps (2.2.0):
    - GoogleMaps/Maps (= 2.2.0)
  - GoogleMaps/Base (2.2.0)
  - GoogleMaps/Maps (2.2.0):
    - GoogleMaps/Base
  - GoogleNetworkingUtilities (1.2.2):
    - GoogleSymbolUtilities (~> 1.1)
  - GoogleSignIn (3.0.0):
    - GoogleAppUtilities (~> 1.0)
    - GoogleAuthUtilities (~> 2.0)
    - GoogleNetworkingUtilities (~> 1.0)
    - GoogleUtilities (~> 1.0)
  - GoogleSymbolUtilities (1.1.2)
  - GoogleToolboxForMac/Defines (2.1.3)
  - GoogleToolboxForMac/Logger (2.1.3):
    - GoogleToolboxForMac/Defines (= 2.1.3)
  - GoogleToolboxForMac/NSData+zlib (2.1.3):
    - GoogleToolboxForMac/Defines (= 2.1.3)
  - GoogleUtilities (1.3.2):
    - GoogleSymbolUtilities (~> 1.1)
  - GPUImage (0.1.7)
  - lottie-ios (2.1.5)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - Protobuf (3.5.0)
  - React (0.51.0):
    - React/Core (= 0.51.0)
  - React/ART (0.51.0):
    - React/Core
  - React/BatchedBridge (0.51.0):
    - React/Core
    - React/cxxreact_legacy
  - React/Core (0.51.0):
    - yoga (= 0.51.0.React)
  - React/cxxreact_legacy (0.51.0):
    - React/jschelpers_legacy
  - React/DevSupport (0.51.0):
    - React/Core
    - React/RCTWebSocket
  - React/fishhook (0.51.0)
  - React/jschelpers_legacy (0.51.0)
  - React/RCTActionSheet (0.51.0):
    - React/Core
  - React/RCTAnimation (0.51.0):
    - React/Core
  - React/RCTBlob (0.51.0):
    - React/Core
  - React/RCTCameraRoll (0.51.0):
    - React/Core
    - React/RCTImage
  - React/RCTGeolocation (0.51.0):
    - React/Core
  - React/RCTImage (0.51.0):
    - React/Core
    - React/RCTNetwork
  - React/RCTNetwork (0.51.0):
    - React/Core
  - React/RCTText (0.51.0):
    - React/Core
  - React/RCTVibration (0.51.0):
    - React/Core
  - React/RCTWebSocket (0.51.0):
    - React/Core
    - React/fishhook
    - React/RCTBlob
  - RNFirebase (3.0.4):
    - React
  - yoga (0.51.0.React)

DEPENDENCIES:
  - ExpoKit/Core (from `http://github.com/expo/expo.git`, tag `ios/2.2.1`)
  - ExpoKit/CPP (from `http://github.com/expo/expo.git`, tag `ios/2.2.1`)
  - Firebase/Analytics
  - Firebase/Core
  - Firebase/Crash
  - Firebase/Messaging
  - React/ART (from `../node_modules/react-native`)
  - React/BatchedBridge (from `../node_modules/react-native`)
  - React/Core (from `../node_modules/react-native`)
  - React/DevSupport (from `../node_modules/react-native`)
  - React/RCTActionSheet (from `../node_modules/react-native`)
  - React/RCTAnimation (from `../node_modules/react-native`)
  - React/RCTCameraRoll (from `../node_modules/react-native`)
  - React/RCTGeolocation (from `../node_modules/react-native`)
  - React/RCTImage (from `../node_modules/react-native`)
  - React/RCTNetwork (from `../node_modules/react-native`)
  - React/RCTText (from `../node_modules/react-native`)
  - React/RCTVibration (from `../node_modules/react-native`)
  - React/RCTWebSocket (from `../node_modules/react-native`)
  - RNFirebase (from `../node_modules/react-native-firebase`)
  - yoga (from `../node_modules/react-native/ReactCommon/yoga`)

EXTERNAL SOURCES:
  ExpoKit:
    :git: http://github.com/expo/expo.git
    :tag: ios/2.2.1
  React:
    :path: ../node_modules/react-native
  RNFirebase:
    :path: ../node_modules/react-native-firebase
  yoga:
    :path: ../node_modules/react-native/ReactCommon/yoga

CHECKOUT OPTIONS:
  ExpoKit:
    :git: http://github.com/expo/expo.git
    :tag: ios/2.2.1

SPEC CHECKSUMS:
  Amplitude-iOS: 4a3c8807b2ea5369dc11e87e23825bff01e5a922
  Analytics: 6541ce337e99d9f7a2240a8b3953940a7be5f998
  AppAuth: 3f4f1d6d85ad631d0bbf15ffcdc10c447face97a
  Bolts: ac6567323eac61e203f6a9763667d0f711be34c8
  Branch: f63d9cf82ac09747349a73184a0b739d28781c4d
  CocoaLumberjack: 2800c03334042fe80589423c8d80e582dcaec482
  Crashlytics: dbb07d01876c171c5ccbdf7826410380189e452c
  ExpoKit: fa14285686de9630d1662f2de284e48fee1e6678
  Fabric: 9cd6a848efcf1b8b07497e0b6a2e7d336353ba15
  FBAudienceNetwork: 84fc420e262ae16b30586861fa11dd9c779336a8
  FBSDKCoreKit: 6f139173dc63a1deaff4430a55f2fe5bb222d2af
  FBSDKLoginKit: 56a057ca6822535ea0faa25f57a7c41edb697fd4
  FBSDKShareKit: 18a2cd118aef11dd657fe7e8b64bae5c719088b2
  Firebase: 2721056b8885eef90233b03f37be64358d35d262
  FirebaseAnalytics: 617afa8c26b57a0c3f11361b248bc9e17bfd8dfd
  FirebaseCore: 2e0b98fb2d64ca8140136beff15772bdd14d2dd7
  FirebaseCrash: cded0fc566c03651aea606a101bc156085f333ca
  FirebaseInstanceID: 81df5805a08001e69138664bdd02c6719a9ac80f
  FirebaseMessaging: dfdcd307c2382290a1e297a81d0f18370f5b1bcd
  Google-Mobile-Ads-SDK: 1bdf1a4244d0553b1840239874c209c01aef055f
  GoogleAppUtilities: a8a552aa74f6597f805e45b5a3962766c3134973
  GoogleAuthUtilities: ccad2e0a9284699973ff57c0dd24c3893657fda4
  GoogleMaps: 104c418d61ab8a05dff06ed0784c25ea9d37da45
  GoogleNetworkingUtilities: 3edd3a8161347494f2da60ea0deddc8a472d94cb
  GoogleSignIn: 3d571172b8603be39dcb1705d8217146bb76fe62
  GoogleSymbolUtilities: 631ee17048aa5e9ab133470d768ea997a5ef9b96
  GoogleToolboxForMac: 2501e2ad72a52eb3dfe7bd9aee7dad11b858bd20
  GoogleUtilities: 8bbc733218aad26306f9d4a253823986110e3358
  GPUImage: 733a5f0fab92df9de1c37ba9df520a833ccb406d
  lottie-ios: 836cdbba92f62f3c6a00e37a4ce485321fe317cf
  nanopb: 5601e6bca2dbf1ed831b519092ec110f66982ca3
  Protobuf: 8a9838fba8dae3389230e1b7f8c104aa32389c03
  React: 541ba768b9855e10cdc76f55427a5cd0653ca806
  RNFirebase: 553eb775cc87de5c7f420128b949b83ab99f1536
  yoga: 17521bbb0dd54a47c0b3ac43253e78cdac7488e0

PODFILE CHECKSUM: 673ff1d3ffc6fc19bbb7cb4f3c263617fa55422b

COCOAPODS: 1.4.0

is this what you mean?

**Comment by skylerwshaw** [comment]
@jorgefernandes This does not appear to be a bug with the Intercom for iOS SDK. We don't specifically support Expo, which is a wrapper that wraps React Native, another wrapper of native iOS APIs. How have you integrated Expo into your app?

**Comment by jorgefernandes** [comment]
@skylerwshaw Im using a detached app. And i have ExpoKit 24.0.0 installed. I was using ios intercom before in this project; this problem seems to appeared now

**Comment by skylerwshaw** [comment]
@jorgefernandes Can you please define what you mean by now? What was the change that introduced this issue for you?

**Comment by jorgefernandes** [comment]
@skylerwshaw ok, sorry. Right after i've updated expo SDK 22.0.1 to 24.0.0 and intercom-ios from 3.2.8 to 4.1.8

**Comment by jorgefernandes** [comment]
@skylerwshaw i just tested again using expo SDK 22.0.1 and intercom-ios 3.2.8. And worked fine.

I update just expo sdk to 24.0.0 and bug happend again. I don't know how it can be related

![screen shot 2018-01-22 at 17 51 50](https://user-images.githubusercontent.com/415791/35244007-e3fa1d20-ffa5-11e7-89e9-f9d0b1e2f551.png)
![screen shot 2018-01-22 at 17 52 00](https://user-images.githubusercontent.com/415791/35244008-e421aa2a-ffa5-11e7-8c15-36f3a1faed7b.png)

**Comment by jorgefernandes** [comment]
@skylerwshaw i think a forget to mention that im using ExpoKit 24.0.0

**Comment by skylerwshaw** [comment]
@jorgefernandes Is ExpoKit Open Source? If so, can you share a link here? Unfortunately it's not possible for us to determine why a third party library is breaking these views. Intercom uses standard Apple APIs for displaying the messenger.

Feel free to continue the conversation here but I'm going to close the issue as not related to our SDK pending further information to the contrary.
