### ISSUE TITLE
Crash in -[PodIntercom_AFSecurityPolicy setPinnedCertificates:]

### ISSUE THREAD

**Issue by therichardnguyen** [intercom/intercom-ios#362]
## Version info
  - Intercom for iOS version: 3.0.10
  - iOS version: 11

## Logs
http://crashes.to/s/9bbdd50a196

**Comment by bboyle18** [comment]
Hi @therichardnguyen 

Version 3.0.10 is a very old version of Intercom.
If you update to [our latest version](https://github.com/intercom/intercom-ios/releases/tag/4.1.9), this should be fixed.

Thanks

Brian
