### ISSUE TITLE
Add support for the new build system in Xcode 9

### ISSUE THREAD

**Issue by fobin** [intercom/intercom-ios#363]
## Version info
  - Intercom for iOS version: 4.1.9
  - iOS version: 11.2.5

## Expected behavior
- Intercom bundle loads without issues

## Actual behavior
ERROR - 💥👎 Intercom.bundle hasn't been added to your app correctly. This will result in images not appearing in the SDK's messaging UI. More information on how to correctly integrate Intercom is available here: https://developers.intercom.com/docs/ios-installation.

## Steps to reproduce
 1. Create new project 
 2. Add Intercom via Cocoapods
 3. Switch the build system to be the New build system (File -> Workspace Settings -> Build system)

## Logs
Check actual behavior

**Comment by bboyle18** [comment]
Hi @fobin 👋 
Thanks for getting in touch.

We will support this new build system once its out of its experimental phase. We're also reliant on Cocoapods to officially support this as well.

Cheers

Brian
