### ISSUE TITLE
Can't see tying text in messenger composer

### ISSUE THREAD

**Issue by al-zonke** [intercom/intercom-ios#365]
## Version info
  - Intercom for iOS version: 4.1.9
  - iOS version: 9.3 simualtor, 10.3 simualtor, 11.3 device and simulator

## Expected behavior
User can see message he is typing

## Actual behavior
Message is hidden below screen when user starts typing

## Steps to reproduce
 1.  Setup Intercom on app launch
```
[Intercom registerUserWithUserId:userId email:email];
[Intercom setLauncherVisible:YES];
```
 2. tap intercom button (default one)
 3. tap into message input text field
 4. observe text field is shifted down below screen
 5. if deice has no external keyboard attached it's impossible to perform 

![img_0011](https://user-images.githubusercontent.com/4379567/36358797-e5d08f26-151c-11e8-88fa-f6f127a6cbee.PNG)

<img width="660" alt="screen shot 2018-02-19 at 02 28 59" src="https://user-images.githubusercontent.com/4379567/36358784-b1e06042-151c-11e8-8a2f-0be9021d2c82.png">
<img width="660" alt="screen shot 2018-02-19 at 02 19 53" src="https://user-images.githubusercontent.com/4379567/36358785-b1fa5222-151c-11e8-977f-3062891a6c65.png">

**Comment by bboyle18** [comment]
Hi @al-zonke 

This is probably as a result of a 3rd party library interferring with the Intercom composer.
If you can provide me with a list of your other 3rd party libs, I can help you identify which one is causing the problem.

Cheers

Brian

**Comment by bboyle18** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.
