### ISSUE TITLE
Carthage install doesn't provide the LICENSE file

### ISSUE THREAD

**Issue by potecuta** [intercom/intercom-ios#366]
Like the title says when installing through Carthage, the LICENSE file isn't provided anywhere. I'm pretty sure this is because you are only providing a binary, but I'm still at a loss regarding what I should do. Is there any alternative other than manually putting the LICENSE file in the app and making sure it gets updated when you update it?

**Comment by bboyle18** [comment]
Hi @potecuta 

Does Carthage require a licence file for 3rd party libs? Or is this just something you feel should be included?

Thanks

Brian

**Comment by potecuta** [comment]
Well, the Licenses from third party apps should be shown (or at least included) inside the applications that are using them. On Cocoapods this is done by Cocoapods, on Carthage this is usually done with a script extracting the Licenses from the Checkout folders. But when using Carthage with binaries there is no Checkout folder for the respective dependency so there is no way of extracting the License.

**Comment by bboyle18** [comment]
Thanks for highlighting this. 👍 
Our up to date licence is always [available here](https://github.com/intercom/intercom-ios/blob/master/LICENSE) but I'll track this issue internally and update our build scripts so that its included in Carthage in the future.

Thanks

Brian
