### ISSUE TITLE
OSX?

### ISSUE THREAD

**Issue by reddavis** [intercom/intercom-ios#51]
Hey! Sorry, not really an issue, just a question: Any plans on making the SDK work on OS X?

Cheers, Red

**Comment by idcuesta** [comment]
Hi @reddavis,

Currently we have no plans for OS X. Maybe it is something we could consider if the demand grows, but I don't think it will happen in the near future :(

Regards
Ignacio

**Comment by fjaeger** [comment]
I would also love to see this happen!

**Comment by sjalgeo** [comment]
+1 @idcuesta

**Comment by careybaird** [comment]
+1 on this one @idcuesta

**Comment by jtreanor** [comment]
Hi @careybaird and @sjalgeo,

This is still not something we we be supporting in the foreseeable future. However, depending on your requirements, you may be able to use our JS integration in a desktop app. Our REST API may also do what you need.

**Comment by grasmeyer** [comment]
+1 @idcuesta @jtreanor We don't necessarily need a Mac-based UI for Intercom conversations, but just porting the core Intercom SDK to allow logging Intercom events would be useful. That code within the Intercom SDK probably isn't platform-specific anyway, so it should run fine on macOS without much modification.

**Comment by jtreanor** [comment]
Hi @grasmeyer,
We have a HTTP API that should fit your needs. You can read about it here: https://developers.intercom.com/docs/overview-and-setup
There are also a number of simple SDK wrappers for the API [here](https://developers.intercom.com/docs/intercom-sdks).
