### ISSUE TITLE
Dodgy swizzling causing crashes in our production app

### ISSUE THREAD

**Issue by sammcewan** [intercom/intercom-ios#52]
The method swizzleBecomeFirstResponder on the category UIView+ITBAllowFirstResponder.h causes frequent crashes for our app. It's getting really painful.

Swizzling is generally a last resort so I imagine this is there for a good reason. However this is a huge pain especially in a static library.

Urge a different approach here if at all possible.

**Comment by idcuesta** [comment]
Hi @sammcewan,

Sorry to hear about this :(

Could you provide more info about the issue? Any crash report or sample project where we can reproduce it would be great.

If you want we can follow up this privately, via Intercom app.

Regards
Ignacio

**Comment by vintagexav** [comment]
@idcuesta it looks like Intercom's SDK got a problem here:

```
UIView+ITBAllowFirstResponder.m line 32
__61+[UIView(ITBAllowFirstResponder) swizzleBecomeFirstResponder]_block_invoke_2
```

**Comment by adamkmccarthy** [comment]
Thanks @vintagexav. We are about to release a version of this that decouples a lot of the 'safe' swizzle we did here in an attempt to make implementing push a little easier. We'll be releasing 2.1 very early next week which should fix this.

**Comment by tankista** [comment]
@adamkmccarthy in 2.1.1 this but shill happens. I can provide a crash log if you wish. We will now update to version 2.2 and will keep you updated if it happens again.

**Comment by adamkmccarthy** [comment]
@tankista a crash log would be great as we changed how push works in 2.1+ so we could move away from the swizzle. You can mail it to me if it's easier, adam at intercom dot io. Given our implementation has changed ill create a new bug if I can reproduce this crash.

**Comment by jameshartt** [comment]
+1 on this, curiously, only on the Simulator, on a UITextView. Will disable for Simulator for now as there is no need. But it's good to here you are moving away from swizzling all the things.

**Comment by adamkmccarthy** [comment]
For sure. We're actually going to try and close this out this week :+1:

**Comment by vintagexav** [comment]
@adamkmccarthy is this fixed?

**Comment by adamkmccarthy** [comment]
@vintagexav Yep: https://github.com/intercom/intercom-ios/commit/9118b846362b7365b7ee0e3ac28c6ae8cc20287f
