### ISSUE TITLE
UDID usage is non-public, cant submit to appstore

### ISSUE THREAD

**Issue by frobichaud** [intercom/intercom-ios#55]
find . | grep -v .svn | grep "\.a" | grep -v "\.app" | xargs grep uniqueIdentifier
Binary file ./Pods/Intercom/Intercom/libIntercom.a matches

![screen shot 2015-02-24 at 9 30 37 pm](https://cloud.githubusercontent.com/assets/3533748/6363943/a5d0ebb0-bc6d-11e4-86f6-0836044ecd0b.png)

This is with both version 2.0.6 and 2.0.7

**Comment by adamkmccarthy** [comment]
Hi @frobichaud. Thanks for letting us know. For what it's worth, we don't actually use any private APIs in the SDK. The references you're finding there are returning public properties on our own user class that reference a unique identifier. We've had a few hundred App Store submissions (including our own app) and we haven't had any big problems before. We submitted our own app to the store twice in the last few weeks most recently without incident. Is it possible there's something else going on here? Thanks for your help.

**Comment by frobichaud** [comment]
Thanks for your quick reply, it was actually a different library that caused the issue.
