### ISSUE TITLE
No public headers exposed when added as pod

### ISSUE THREAD

**Issue by nickbit** [intercom/intercom-ios#57]
I have Intercom added as a pod. 
It gives me file not found errors for "Intercom.h". 
It seems that the headers are not exposed as public anymore.
Please check...

**Comment by jtreanor** [comment]
Hi @nickbit, did you get it working ok?

Let me know if you are having any issues.

**Comment by nickbit** [comment]
It seems to be OK after I updated to 2.1.1.

Thank you!

**Comment by dstudeba** [comment]
Just for future reference I had a similar problem and noticed that there was an extra "Intercom" folder in the Pods/Headers/Public area.  I copied the Intercom.h file from the Public/Intercom/Intercom folder to the Public/Intercom folder and it worked.
