### ISSUE TITLE
Navigation bar scrolls up and never comes down after replying into any conversation.

### ISSUE THREAD

**Issue by Prarik** [intercom/intercom-ios#59]
When I present message composer using [Intercom presentMessageComposer]; it opens the composer fine. But when I type in any the keyboard appears and navigation bar goes up, which should come down again when the keyboard hides but it doesn't come down. 

Can you tell me how can I solve this issue? As I can see no implementation files for the sdk.

![ios simulator screen shot 26-mar-2015 10 52 08 pm](https://cloud.githubusercontent.com/assets/3737919/6852461/ca90ee5a-d40a-11e4-8847-e6ff37fb24c8.png)

**Comment by adamkmccarthy** [comment]
Thanks @Prarik. This is quite odd. There is no animations implemented on the SDK's navigation bars, we don't hide them at all. Is there anything in your app that might be attempting to set an effect or proxy UINavigationBar at all?

**Comment by Prarik** [comment]
No we are also not hiding the navigation bars, we only used translucent navigation bars, does that cause any issue?

**Comment by adamkmccarthy** [comment]
It would be unusual but that could be it, the bars in the SDK are entirely stock. Would you be able to share (perhaps via Intercom) some of the appearance proxying you're doing and ill be able to test it out and see if that has anything to do with it?

**Comment by Prarik** [comment]
Thanks @adamkmccarthy  for looking into this but I found the issue it was because of IQKeyboardManager. Removing that library solved the issue.

**Comment by Coooi** [comment]
@adamkmccarthy I'm facing the same issue after closing the messenger.
Steps to reproduce:
1. Intercom.presentMessenger()
2. Open any conversation.
3. Close the messenger.
4. All navigation controllers disappear.

Do you know if Intercom SDK is modifying UINavigationBar.appearance() ?

**Comment by jtreanor** [comment]
Hi @Coooi,

Since this issues to quite an old version of Intercom, could you please open a new issue for this so that we can help diagnose it?

James

**Comment by Coooi** [comment]
@jtreanor For sure, thanks.
