### ISSUE TITLE
Support for users persisting across multiple environments

### ISSUE THREAD

**Issue by ajwhite** [intercom/intercom-ios#61]
Our application has multiple environments between production and testing. In our testing environment, we use a specific App ID and API Key for Intercom, and similarly we use a separate pair for our production environment.

When building the application on the same device in one environment and then later building in another environment, the second does not successfully report to Intercom. Instead, it fails with a `404`:

> ERROR - Tried to update user attributes but there was a network error - Request failed: not found (404)

### Steps to reproduce:

- Choose a persistent "user id". In our application, the device is the actor in the system, so this device carries the same user ID across multiple environments (its UUID). 
- Initialize intercom with your testing credentials
- Register/update a user with an ID (or email for that matter -- that will have problems across environments if the same email is used to identify a user)
- Optionally track an event, this will produce a `404` as well

Reproduce the steps above with the production credentials, and after the last step of updating the user on Intercom, you should receive a `404`

---

I discussed this issue with @adamkmccarthy over the Intercom support channel, who suggested calling `[Intercom reset]` for the new environment, but cautioned about doing this too frequently, such as when the application loads. Instead, it would be better to invoke this ~~after logging in, before updating the user~~ upon logging out.

**Comment by adamkmccarthy** [comment]
Thanks @ajwhite. The crux of the problem here is that Intercom users are scoped on a per-app basis, so don't flow freely between "hot" SDK deployments like scheme switching in Xcode between environments. We're going to attempt a small fix to the SDK in a future update.

To be clear, *never* call `reset` after logging in. *Only* call `reset` when logging out.

**Comment by ajwhite** [comment]
Thanks & updated

**Comment by jtreanor** [comment]
This has been fixed in 2.2.2. Users can now be tracked seamlessly across environments.

James

**Comment by ajwhite** [comment]
Thanks for the update!

To double check -- no more need to call reset as the previous workaround for environment changes?

**Comment by jtreanor** [comment]
Yes, exactly. Calling reset to change environments is no longer necessary. The SDK now detects when this happens and handles it internally.

**Comment by ajwhite** [comment]
:+1: thanks guys!
