### ISSUE TITLE
pre populate message composer with text

### ISSUE THREAD

**Issue by mderazon** [intercom/intercom-ios#62]
Is it possible to open the message composer with pre populated text ?

This could be handly in cases we want the customer to contact us with something specific  that happens in the app.

For example, "report a problem with this restaurant listing" could open the message composer with the restaurant details already pre-entered...

**Comment by adamkmccarthy** [comment]
@mderazon unfortunately the kind of use case you outline isn't possible at the moment although ill bring it to the product team as it sounds like a useful customisation to have. Thanks!

**Comment by kapluni** [comment]
this would  be great. a very useful feature in the web version, it would also help a great deal on mobile

**Comment by audvin** [comment]
Would love this on the web version indeed. 

Great for when the User receives an error. This way the Help Team can be promoted immediately via Intercom and the User sees that action is taken.

**Comment by mderazon** [comment]
So, what did the product team say ? 😁

**Comment by adamkmccarthy** [comment]
@mderazon They said yes :) We shipped it a few versions ago: https://github.com/intercom/intercom-ios/blob/master/CHANGELOG.md#3013-2016-10-7

**Comment by mderazon** [comment]
😱
