### ISSUE TITLE
Session is always  = 0

### ISSUE THREAD

**Issue by invoodoo** [intercom/intercom-ios#63]
I'm using [Intercom registerUserWithEmail:userID]; method all time user start the app, but it doesn't count the number of sessions. What I'm doing wrong? I saw deprecated methods for beginSession/endSession and there is a note about usage of register method to count sessions, but it doesn't work.

Thanks.

**Comment by jtreanor** [comment]
Thanks @invoodoo,

It sounds like you are doing everything correctly. I will investigate this on our backend and let you know when I know more.

James

**Comment by adamkmccarthy** [comment]
Hi @invoodoo, the session column you're seeing in Intercom is for Web sessions only and not iOS sessions. If you go to the column chooser at the top right of your user list and select `iOS Sessions` from the list, you'll see the correct values there. Sorry for the confusion, we're working on ways to make this clearer. Thanks!

![screen shot 2015-05-06 at 08 58 24](https://cloud.githubusercontent.com/assets/1059521/7489399/2e680d7c-f3ce-11e4-9ebb-69ac42c79ff3.png)

**Comment by invoodoo** [comment]
Thanks, I found. Yep, little bit hidden.
