### ISSUE TITLE
[PodIntercom_ITBNetworkMessage setConversation:] - unrecognized selector

### ISSUE THREAD

**Issue by zdavison** [intercom/intercom-ios#64]
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PodIntercom_ITBNetworkMessage setConversation:]: unrecognized selector sent to instance 0x16752ca0'
```

The user that is logged in at the time (my user) has 3 old messages from Intercom, this does not repro on an account that has no pending messages (which makes sense given the exception).

**Comment by jtreanor** [comment]
Hi @zdavison 

This error happens when you are missing the `-ObjC` linker flag so categories in Intercom can't be loaded. Luckily, 2.2.2 removed this requirement so if you update your SDK version it will work fine :smile:

James

**Comment by zdavison** [comment]
Updating to 2.2.2 does indeed work, we switched to a different dependency management tool (not Cocoapods), so forgot to bring the -Objc flag with us. 
Cheers!

**Comment by jtreanor** [comment]
No problem at all.
