### ISSUE TITLE
Code signing error.

### ISSUE THREAD

**Issue by zdavison** [intercom/intercom-ios#65]
```
Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
<PATH>/Build/Products/Debug-iphoneos/iPad.app/Frameworks/Intercom.framework: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1
```

This started happening very recently and I can't pin a finger on why, any ideas? We're on 6.4 beta 3.

This also happens if I try and codesign the framework (or the `/A` version) by hand, freshly downloaded from Github releases.

**Comment by jtreanor** [comment]
Hi @zdavison,

Do you get this same error when using CocoaPods? Does it only happen in the Xcode beta?
