### ISSUE TITLE
Intercom window not honoring -prefersStatusBarHidden

### ISSUE THREAD

**Issue by hwaxxer** [intercom/intercom-ios#66]
The status bar appears in view controllers where `-prefersStatusBarHidden` is `YES`.

**Comment by adamkmccarthy** [comment]
Thanks. The UI we have opens in a new UIWindow and doesn't transfer those values to it's own Intercom view controllers. We'll look into being able to support this.

**Comment by hwaxxer** [comment]
Thanks for looking into it. I could probably have been more clear. As you probably figured out, the status bar becomes visible when the "chat face" appears in the UI. 
Let me know if you have trouble reproducing. If it helps, our navigation hierarchy consists of a view controller that, depending on context, switches between child tab bar controllers that in turn contain navigation controllers that each may or may not prefer status bar to be hidden.

**Comment by adamkmccarthy** [comment]
:+1: Thanks Martin. Our conversation in Intercom made it super clear, we're looking into it today as it isn't at all desirable.

**Comment by jtreanor** [comment]
2.3.0 now respects `-prefersStatusBarHidden`
