### ISSUE TITLE
+reset doesn't work

### ISSUE THREAD

**Issue by hwaxxer** [intercom/intercom-ios#68]
Calling `+reset` doesn't actually reset or clear the registered user. Events that are logged after calling `+reset` (and subsequently `+registerUnidentifiedUser`) are assigned to the previously registered user. 

It looks like if an event is logged shortly prior to calling `+reset`, the previous request somehow logs in the user again.

**Comment by adamkmccarthy** [comment]
Thanks @hwaxxer. Are you using the very latest version of the library? We had a bug like this before that I was sure we had fixed :(

**Comment by hwaxxer** [comment]
Yes, version `2.2.4`. We log a sign out event just before calling `+reset`. It's very easy to reproduce. If I delay the `+reset` by a second or two, the issue doesn't occur (given that no other event is triggered during that delay).

**Comment by adamkmccarthy** [comment]
That makes sense (the steps you outline). Whats happening here is the event's response is returning the user's ID _after_ the reset and thus re-applying that user's identity. This feels like a regression, as we had fixed this specific issue before. We'll look into it straight away.

**Comment by hwaxxer** [comment]
Are you by any chance using a serial queue for your requests? Because if so I could fix this by dispatching the intercom methods on a serial thread.

**Comment by adamkmccarthy** [comment]
We're not using a serial queue (rest doesn't make a network request) but if you are calling them asynchronously it may well be that the event is coming back after reset has happened.

**Comment by hwaxxer** [comment]
All communication with Intercom is currently on the main thread. Fortunately our users don't log out very often. Anyway, thanks for the fast reply.

**Comment by jtreanor** [comment]
This has been fixed in 2.3.0.
