### ISSUE TITLE
Can't see welcome message or autoreply in composer

### ISSUE THREAD

**Issue by jparkrr** [intercom/intercom-ios#69]
I set a welcome message in Settings > Messaging, but it doesn't show up.

![image](https://cloud.githubusercontent.com/assets/872456/7988057/a91e7b12-0ae1-11e5-897e-3c7457993148.png)

I've also changed the color in Settings > Appearance, and it is working, so I know I have the right app.

Thanks.

**Comment by adamkmccarthy** [comment]
Thanks @jparkrr. There was a bug for a while on our side we've we've since fixed - are you still having problems with that welcome message appearing?

**Comment by jparkrr** [comment]
I'm working with @hwaxxer. We're on the latest version.

**Comment by adamkmccarthy** [comment]
:+1: is it still happening for you?

**Comment by jparkrr** [comment]
No, it still doesn't work.

What are you thinking the problem.

**Comment by adamkmccarthy** [comment]
Just looking into it now, it's a problem with our API for sure.

**Comment by adamkmccarthy** [comment]
@jparkrr can you ping me inside Intercom? (handier to discuss app_ids etc in a private forum)

**Comment by adamkmccarthy** [comment]
We're rolling out a fix for this now, sorry for the trouble.

**Comment by jparkrr** [comment]
Awesome! Confirmed. Do you have any idea why the auto reply isn't working
also

**Comment by adamkmccarthy** [comment]
I do! We removed that feature in version 2.2.2 about a month ago: https://github.com/intercom/intercom-ios/blob/master/CHANGES#L20

**Comment by hwaxxer** [comment]
Why did you remove it? And why does it still show in the app's settings?
