### ISSUE TITLE
When the log is off, I shouldn't see console messages

### ISSUE THREAD

**Issue by hsoi** [intercom/intercom-ios#70]
If I have never invoked:

```swift
Intercom.enableLogging()
```

then I expect nothing logged to the console. However, I noticed errors are being logged. 

In my case we log some event analytics on things like the application becoming active, which happens upon app launch before the user is able to log in -- legit, fine, technically an error but not really a problem for us, but yet it reports that in the console despite the fact I haven't enabled logging.

Maybe that's how it should work, but it seems like, given the public API, that I should only get log messages (period, any flavor) if logging was enabled.

**Comment by adamkmccarthy** [comment]
thanks @hsoi. The current implementation does, as you point, log potentially critical errors to the console. We'll evaluate this in a future release for sure. Thanks.
