### ISSUE TITLE
Variable log levels

### ISSUE THREAD

**Issue by hsoi** [intercom/intercom-ios#71]
Building upon issue #70 it may be more useful to have levels of logging instead of a simple on/off setting.

Maybe something like:

```
enum {
case Error
case Warn
case Info
case Debug
case Verbose
case Off
}
```

as it seems you may internally already have such levels (given how I've seen log output).

**Comment by adamkmccarthy** [comment]
Thanks John. We have something very similar indeed, we just don't hide the `ERROR` cases at the moment. A number of folks have expressed their distaste with how we're currently doing it, we'll definitely be taking another look. Thanks!
