### ISSUE TITLE
[Intercom presentMessageComposer] doesn't work

### ISSUE THREAD

**Issue by limenutt** [intercom/intercom-ios#73]
[Intercom presentMessageComposer] currently opens conversations list instead of showing a message composer.

**Comment by adamkmccarthy** [comment]
Thanks @limenutt, I can see in Intercom that you're on the Learn Pro package which doesn't support inbound messaging. If you enable logging in the SDK, you will see an error letting you know why it didn't show the new message composer. Feel free to contact us in Intercom if you'd like to change that. Thanks.
