### ISSUE TITLE
Keyboard padding bug in message composer

### ISSUE THREAD

**Issue by macbaszii** [intercom/intercom-ios#75]
![ios simulator screen shot jun 29 2015 11 48 29 am-2](https://cloud.githubusercontent.com/assets/809559/8401312/fae11fe4-1e56-11e5-85a7-a072c7dae140.png)

**Comment by jtreanor** [comment]
Hi @macbaszii

Can you explain what the issue is here?

**Comment by jtreanor** [comment]
Sorry @macbaszii, I see it now. Its Monday morning here :smile: 

The offset seems to be exactly the height of a UIToolbar. Are you using any third party components that modify keyboard behaviour? e.g IQKeyboardManager, DAKeyboardControl etc.

**Comment by macbaszii** [comment]
@jtreanor Yes, I used IQKeyboardManager and How can we use it ?

Sorry for late reply.

**Comment by jtreanor** [comment]
No problem @macbaszii. The issue is that IQKeyboardManager swizzles keyboard behaviour so directly messes with our ability to present a keyboard.

To fix it you can disable IQKeyboardManager while the Intercom window is open. Something like this would work:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
   ...
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(intercomWillShow) name:IntercomWindowWillShowNotification object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(intercomWillHide) name:IntercomWindowWillHideNotification object:nil];
    ...
}

- (void)intercomWillShow {
    [IQKeyboardManager sharedManager].enable = NO; 
}

- (void)intercomWillHide {
    [IQKeyboardManager sharedManager].enable = YES;
}
```
