### ISSUE TITLE
Atomic user creation

### ISSUE THREAD

**Issue by mchicote** [intercom/intercom-ios#76]
Hi
I would like to propose a way to create a user atomically. Current version of the SDK only allows to register a user using ID or ID and Email. I would like a way to create and update user properties all at once.

The reason behind this is that I user Zapier to listen for users created on Intercom and create them on Promoter. If I don't have atomic user creation, users don't have important properties (i.e. Name) when they are created on Promoter.

Thanks!

**Comment by sheppyc** [comment]
Yes this would be useful. I have a similar requirement but for slack integration. Currently we're using ID + email, and it's nice but would prefer to add the full name as we collect during signup to make things a little nicer.

**Comment by adamkmccarthy** [comment]
thanks @mchicote & @sheppyc. We did have this in a previous version and removed it for simplicity (at a time when re required synchronous communication with Intercom's API for such requests) but we have a much better API these days. We'll revisit it for sure and see what it would look like.
