### ISSUE TITLE
Linker error when compiling for device on Xcode 7 Beta 3

### ISSUE THREAD

**Issue by roland9** [intercom/intercom-ios#77]
Hey guys,
I know it's an Xcode beta version, but would be great if I could compile my app with Xcode 7. I'm using intercom-ios 2.3.0 and I get this error:

```
ld: ' [...] /Pods/Intercom/Intercom.framework/Intercom(AFHTTPRequestOperation.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
```
In my project and the Pods project I have the `Enable Bitcode` setting set to Yes.

**Comment by adamkmccarthy** [comment]
Thanks for this @roland9. We'll need to get further through the beta cycle (or until Apple start accepting Xcode 7 built binaries in the App Store) before we can start building with bitcode, in the meantime i'd suggest turning bitcode off in your Xcode 7 project for now as it's not giving you anything specific just yet. If you're using cocoapods you can probably toggle it per pod target too (I think, ill find out for sure)

**Comment by roland9** [comment]
@adamkmccarthy yep that's what I ended up doing - because also other libraries have the same 'problem'. Again, I'm aware it's a beta release, so good to hear it's in you radar. Closing

**Comment by moflo** [comment]
Hi, any update on providing a bitcode enabled Intercom framework? Thanks!

**Comment by jtreanor** [comment]
Hi @moflo,

Yes, we will have a new version soon. You can find updates here: https://github.com/intercom/intercom-ios/issues/90
