### ISSUE TITLE
New message is not displayed in the conversation on push notification

### ISSUE THREAD

**Issue by egrankovskiy** [intercom/intercom-ios#79]
If open the app with Intercom integration via push notification tap, the new message is not displayed in the conversation.

STR:
1. Go to the Conversation screen.
2. Put the app in to background.
3. Send a new message to this user via Intercom.
4. Wait for the push notification.
5. Tap on the push notification.

Expected result: The app is opened and the new message is displayed.
Actual result: The app is opened, but there is no new message on the conversation screen. You should go to the conversation list screen and return back to the current conversation to see new messages.

I suppose you should add something like [self updateMessages] to your -viewDidAppear method of the Conversation view controller.

**Comment by jtreanor** [comment]
Hi @egrankovskiy,

The new message should appear when you open via a push notification. Can you tell me what version of Intercom for iOS you are using? There was a bug prior to 2.2.4 where it did not always work.

By any chance are you calling `[Intercom setMessagesHidden:YES]` when your app launches?

**Comment by egrankovskiy** [comment]
Hi, @jtreanor 

The latest ones (iOS 8.4, intercom 2.3.1). No, I don't use that method. 100% reproducible. Test app, if it matters.

**Comment by jtreanor** [comment]
Thanks @egrankovskiy,

I'll investigate and update here when I know more.

**Comment by jtreanor** [comment]
Would you mind sending a message through Intercom so that we can dig deeper, without having to discuss your app's details in this public issue?

James

**Comment by egrankovskiy** [comment]
Sure, let's talk. Wrote to Intercom.

**Comment by jtreanor** [comment]
Hi @egrankovskiy,

Are you still seeing this issue? After discussion in Intercom, I strongly suspect this is caused by switching an app between TEST and regular Intercom environments. i.e. if you open a push from a test app while registered on your main app, Intercom can't open it because the message won't be found.

Thankfully, if this is the issue, it will not be present for any end users.

**Comment by egrankovskiy** [comment]
@jtreanor, message is not missed, I can see it after going to the conversation list screen and return back to the current conversation. Also, I work ONLY with a test app to reproduce this issue.

Let me describe in other words.

I open the app and go to the current conversation screen and see N messages. Then I put the app to the background (with home button). Then I send a new message from the Intercom (after that we have N + 1 message). I receive the push notification on my iPhone, tap on it and switch back to my app (which still displays conversation screen) and see the same N messages. New message is not displayed. If I navigate to another screen and open again the conversation screen — all messages will be loaded (N+1). So, I suspect that you just don't refresh the message list when the app is going back from background.

**Comment by egrankovskiy** [comment]
@jtreanor, message is not missed, I can see it after going to the conversation list screen and return back to the current conversation. Also, I work ONLY with a test app to reproduce this issue.

Let me describe in other words.

I open the app and go to the current conversation screen and see N messages. Then I put the app to the background (with home button). Then I send a new message from the Intercom (after that we have N + 1 message). I receive the push notification on my iPhone, tap on it and switch back to my app (which still displays conversation screen) and see the same N messages. New message is not displayed. If I navigate to another screen and open again the conversation screen — all messages will be loaded (N+1). So, I suspect that you just don't refresh the message list when the app is going back from background.

**Comment by egrankovskiy** [comment]
@jtreanor, message is not missed, I can see it after going to the conversation list screen and return back to the current conversation. Also, I work ONLY with a test app to reproduce this issue.

Let me describe in other words.

I open the app and go to the current conversation screen and see N messages. Then I put the app to the background (with home button). Then I send a new message from the Intercom (after that we have N + 1 message). I receive the push notification on my iPhone, tap on it and switch back to my app (which still displays conversation screen) and see the same N messages. New message is not displayed. If I navigate to another screen and open again the conversation screen — all messages will be loaded (N+1). So, I suspect that you just don't refresh the message list when the app is going back from background.

**Comment by egrankovskiy** [comment]
@jtreanor, message is not missed, I can see it after going to the conversation list screen and return back to the current conversation. Also, I work ONLY with a test app to reproduce this issue.

Let me describe in other words.

I open the app and go to the current conversation screen and see N messages. Then I put the app to the background (with home button). Then I send a new message from the Intercom (after that we have N + 1 message). I receive the push notification on my iPhone, tap on it and switch back to my app (which still displays conversation screen) and see the same N messages. New message is not displayed. If I navigate to another screen and open again the conversation screen — all messages will be loaded (N+1). So, I suspect that you just don't refresh the message list when the app is going back from background.

**Comment by egrankovskiy** [comment]
@jtreanor, message is not missed, I can see it after going to the conversation list screen and return back to the current conversation. Also, I work ONLY with a test app to reproduce this issue.

Let me describe in other words.

I open the app and go to the current conversation screen and see N messages. Then I put the app to the background (with home button). Then I send a new message from the Intercom (after that we have N + 1 message). I receive the push notification on my iPhone, tap on it and switch back to my app (which still displays conversation screen) and see the same N messages. New message is not displayed. If I navigate to another screen and open again the conversation screen — all messages will be loaded (N+1). So, I suspect that you just don't refresh the message list when the app is going back from background.

**Comment by egrankovskiy** [comment]
@jtreanor, message is not missed, I can see it after going to the conversation list screen and return back to the current conversation. Also, I work ONLY with a test app to reproduce this issue.

Let me describe in other words.

I open the app and go to the current conversation screen and see N messages. Then I put the app to the background (with home button). Then I send a new message from the Intercom (after that we have N + 1 message). I receive the push notification on my iPhone, tap on it and switch back to my app (which still displays conversation screen) and see the same N messages. New message is not displayed. If I navigate to another screen and open again the conversation screen — all messages will be loaded (N+1). So, I suspect that you just don't refresh the message list when the app is going back from background.

**Comment by jtreanor** [comment]
Sorry @egrankovskiy, I got misunderstood the issue. My mistake.

The good news is we are releasing a new version this morning that fixes this issue :smile: I'll keep you updated.

**Comment by jtreanor** [comment]
Version 2.3.2, which fixes this issue has now been released.
