### ISSUE TITLE
Intercom presentConversationList or do not preserve status bar  style

### ISSUE THREAD

**Issue by innovative1** [intercom/intercom-ios#82]
My app has the status bar style set to UIStatusBarStyleLightContent and View controller based status bar style set off. After the Intercom message compose is displayed using +[Intercom presentConversationList] or +[Intercom presentConversationList] status bar style is set to default. 

The status bar style should not be changed or should be reset to its previous state after the message composer is dismissed.

**Comment by jtreanor** [comment]
This has been fixed in 2.3.3.

**Comment by Natelegreat1** [comment]
I have been seeing this issue with 4.0+ ...
