### ISSUE TITLE
Need to present Conversation List inside TabBarController with visible TabBar.

### ISSUE THREAD

**Issue by amitbobade2007** [intercom/intercom-ios#83]
Currently, TabBar is hiding behind presented Conversation List.

**Comment by adamkmccarthy** [comment]
Hi @amitbobade2007, thanks for reaching out. Currently the Intercom SDK lives inside it's own UIWindow so presents as a later above the host app. As a result we don't have the capability to vend a view controller that would work inside elements like your UITabBarController unfortunately.

**Comment by amitbobade2007** [comment]
Thanks @adamkmccarthy. I want to display it inside tabbar. As it is not possible. Now i need to call custom webAPI for conversation history and bind it with viewcontroller. Do you any workaround to access conversation list?

**Comment by adamkmccarthy** [comment]
Unfortunately not. Ping us at team@intercom.io if you'd like to share your reasons for wanted a different type of customisation, hearing about your constraints would be helpful if you had the time. Thanks @amitbobade2007

**Comment by b-raines** [comment]
Same issue here. We are trying to move to tab bar navigation, but intercom window doesn't allow for that. Any updates on this?

**Comment by pkbhadkoliya** [comment]
Hi any update on presenting chat inside UITabBarController.

**Comment by b-raines** [comment]
I just ended up implementing an empty view controller for my tab bar controller, and then subclassed UITabBarController to implement the delegate method for `tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController)`. Not pretty, but works fairly well.

```
  func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool {
    if viewController.isKind(of: IntercomShellViewController.self) {
      if Intercom.unreadConversationCount() > 0 {
        Intercom.presentMessenger()
      } else {
        Intercom.presentMessageComposer()
      }
      return false
    }
    
    return true
  }
```

**Comment by jtreanor** [comment]
@pkbhadkoliya No changes on this.

@b-raines Quick not on your code snippet; `Intercom.presentMessenger()` opens the composer if there is no conversations so the if is not needed 😄
