### ISSUE TITLE
openURL not being called

### ISSUE THREAD

**Issue by scotbond** [intercom/intercom-ios#85]
After integrating IntercomSDK into our project we noticed that deep links has stopped working on iPhone6(+) devices running iOS 8.3 or above (and only when the app is not running in BG, suspended or killed).
The `application:openURL:sourceApplication:annotation:` is not being called after `application:didFinishLaunchingWithOptions:` has finished. According to Apple, openURL will not be called if `didFinishLaunchingWithOptions` returns NO. It seems to me that your swizzling method `swizzleDidFinishLaunchingWithOptions` is causing this problem. 
I wonder if there is some device specific logic you implemented there which may return false in certain circumstances. I'm forced to remove Intercom from the project till this is resolved. Will be happy provide more info as required.
Thanks!

**Comment by harkin** [comment]
Thanks for letting us know about this, it does look like there's a bug in the swizzling. We'll keep you updated as we look into this

**Comment by jtreanor** [comment]
Thanks for reporting this. We have found this issue and are working on a fix.

**Comment by jtreanor** [comment]
This has been fixed in 2.3.4. Let me know if you still see this issue.

**Comment by edelibasi** [comment]
Hello @jtreanor, I am having this issue running the latest version. Would appreciate any help. Thanks!

**Comment by jtreanor** [comment]
Hi @edelibasi,

Could you send us a message through the Messenger on [https://www.intercom.com](https://www.intercom.com) so that we can help you with this.
The issue described here has definitely resolved so it would be great to determine if there is an install problem or if a new issue has surfaced.

James

**Comment by edelibasi** [comment]
I already did James, talking with a colleague of yours. A slight difference of the issue I have is that application:openURL:sourceApplication:annotation: is not called if I add a URI at the manual notification creator but _gets called_ if I launch the app with a URL scheme via Safari. So it does not break anything, only the passed URI from Intercom doesn't work.

**Comment by zachrnolan** [comment]
I'm having the same issue as @edelibasi, any updates on this?

**Comment by jtreanor** [comment]
Hi @zachrnolan,

Can you give a little more detail on the issue you are seeing?

**Comment by zachrnolan** [comment]
@jtreanor Sure.

I'm creating a manual push message in Intercom. I'm putting my deep link URL in the iOS URI and Android URI fields. Android is working fine and will open the app to the correct screen. However, iOS doesn't seem to register the deep link and only opens the app to the home screen. I'm not receiving any errors. 

I'm using Branch to handle the deep link and it's never kicked off when opening iOS from an Intercom push message. It works in all other scenarios (push notifications from other services, mail app, etc).

**Comment by jtreanor** [comment]
Thanks @zachrnolan,

Could you send a message in through the Messenger on [intercom.com](https://intercom.com) about this?
Using Branch here may be the issue.

James

**Comment by zachrnolan** [comment]
@jtreanor I've had a conversation open with a support engineer named Sean, but he hasn't been very responsive. Can you tell me what methods in appdelegate.m should be called when tapping on a push notification?

I removed branch and it's still not working. It seems like intercom isn't triggering any of the appdelegate methods.
