### ISSUE TITLE
Include dependancies in module.modulemap

### ISSUE THREAD

**Issue by kylejm** [intercom/intercom-ios#86]
I noticed that Crashlytics does this. It means that users don't have to manually include each framework that Intercom depends on. You can just link each one in the `module.map`:

```
framework module Crashlytics {
    header "Crashlytics.h"
    header "Answers.h"
    header "CLSLogging.h"
    header "CLSReport.h"
    header "CLSStackFrame.h"

    export *

    link "z"
    link "c++"
}
```

**Comment by harkin** [comment]
That's very neat, we'll look into this. Thanks for bringing it to our attention :+1:

**Comment by jtreanor** [comment]
Thanks @kylejm for the suggestion. Version 2.3.5 now has a better modulemap and a [much improved](https://github.com/intercom/intercom-ios#manual-installation) manual install process :smile:

**Comment by kylejm** [comment]
Hey James, that's awesome! Thanks so much for this, it's really cool!

I've now run in to issue #97, but I can see you're well on to that one :smile:. I've subscribed to it and listen out for more info.

**Comment by jtreanor** [comment]
No problem @kylejm :smile: Glad you like it!

Yeah, we're still getting to the bottom of #97.
