### ISSUE TITLE
Deep Linking from push notifications?

### ISSUE THREAD

**Issue by kotay** [intercom/intercom-ios#87]
According to your `README` you support "Deep Linking in messages" - how do I set this up? I'm looking to deep link from push notifications but can't find any code or documentation on this subject?

**Comment by DaleCantwell** [comment]
@kotay we have been meaning to create docs for deep linking. You can create a custom url scheme for your app as normal (https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html). Then if you create an in app message in intercom with a button or link url that contains your scheme and send that message to users. When a user open the push notification or the in app message they will be brought to the conversation where they can tap on the deep link url.
What you can't currently do is provide a push notification that bring you directly to a part of your app.
