### ISSUE TITLE
App flagged for not declaring push notification support

### ISSUE THREAD

**Issue by sammcewan** [intercom/intercom-ios#88]
We do not want to utilise Intercom's push notification service at this point. 

Apple have recently flagged our app because we don't declare APNS support and we no longer can get through review in a timely manner as a result.

Strongly suggest providing an option for a build with no push notification references.

**Comment by jtreanor** [comment]
Hi @sammcewan

There are many apps in the AppStore with Intercom that do not use push notifications.

Can you give more details of the response they gave you?

**Comment by sammcewan** [comment]
Dear developer,

We have discovered one or more issues with your recent delivery for "xx". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

Regards,

The App Store team

**Comment by sammcewan** [comment]
We believe this was the cause for hold up. 8 days to get through the external review process.

**Comment by jtreanor** [comment]
Thanks for sending on the details. I am very surprised that Apple have started rejecting apps for this reason. Many of apps using Intercom don't use push but this has never been an issue.

A short term fix for your case would be to add the push notifications entitlement, even if you don't intend to use it.

In the meantime we are investigating this and working on a solution.

**Comment by jtreanor** [comment]
I re-read your comment and I see this is a warning, not a rejection. Still important to fix but not quite as major.

Did they give any more detail about which APIs were being flagged?

**Comment by jtreanor** [comment]
This was closed by mistake. Reopening.

We are preparing a potential solution for the next release. I believe the deprecated [`registerForRemoteNotifications`](https://github.com/intercom/intercom-ios/blob/master/Intercom.framework/Versions/A/Headers/Intercom.h#L470) may be the culprit.

**Comment by urkle** [comment]
@jtreanor Thanks.. Hopefully the next update will appease Apple's API usage monitor.   They only started doing this check less than 2 weeks ago.  Which means at some point in the near future they will be rejecting apps due to this.

**Comment by stephencelis** [comment]
We're seeing the same issue. The stricter check came alongside the latest GM.

**Comment by jtreanor** [comment]
Thanks everyone for reporting this.

We are working on this as a matter of priority and I'm quite confident of the upcoming fix. Unfortunately I cannot be 100% sure it will be fixed because Apple did not say specifically which API caused the flag.

**Comment by jtreanor** [comment]
Version 2.3.5 has been released. I am hopeful that this issue should now be fixed but unfortunately we can't be sure until we see how Apple treats this new version.

**Comment by urkle** [comment]
Thanks!, I'll test the new build and see what they do

**Comment by jtreanor** [comment]
This seems not to be an issue anymore. Let me know if you see this again.

**Comment by douglasd3** [comment]
Hi, i having the same issue when upload the app to TestFlight. I've double checked the AppID and the certificates. Any ideia of what could be causing the problem?
PS.: The Push works fine despise the message.

**Comment by jtreanor** [comment]
Hi @douglasd3,

Would you mind opening a new issue for your case so that we can help investigate it?

**Comment by douglasd3** [comment]
Done. Thank you.

**Comment by sravanzeal** [comment]
Hi Intercom Team i implemented Intercom in my application in-app messages are working fine but dam not getting push notification Could you please tell me

**Comment by jtreanor** [comment]
@sravanzeal Could you send a mail to team@intercom.io so we can help with your specific case?
