### ISSUE TITLE
Register user without email

### ISSUE THREAD

**Issue by mchicote** [intercom/intercom-ios#89]
Hi
If I use the method ````(void)registerUserWithUserId:(NSString *)userId email:(NSString *)email;```` to register a user and the email is empty, the user does not get created. Is this expected behavior? Could the user just be created without the email? 

The work around is of course to user ````(void)registerUserWithUserId:(NSString *)userId;````. The strange thing is that if I do this, attributes updated immediately after the user is created don't get updated.  For example, the name attribute does not get updated. 

Summing up, this does not work:

`````
    [Intercom registerUserWithUserId:user.userId.stringValue];
    [Intercom updateUserWithAttributes:@{ @"name" : (user.fullName) ? user.fullName : @""}];
`````

It takes a while but the user gets created but the name is never updated.

Any help with this would be appreciated. 

Thanks!

**Comment by alexblack** [comment]
Having a similar issue, did you figure this out?

**Comment by jtreanor** [comment]
Hi @alexblack,

Can you explain your issue in a little more detail? All parameters on must be non null when registering but updating the user after should work fine.

**Comment by alexblack** [comment]
We're getting

```
"[Intercom] ERROR - 'name' must be an NSString and can't be nil or empty" and ""[Intercom] ERROR - 'email' must be an NSString and can't be nil or empty"
```

**Comment by alexblack** [comment]
We're registering user's with user id, but not email, then later trying to update user attributes, again without name or email in some cases.

**Comment by jtreanor** [comment]
@alexblack The best thing to do here is to check if email and name are present before updating. Something like this will work:

```
[Intercom registerUserWithUserId:user.userId];
ICMUserAttributes *userAttributes = [ICMUserAttributes new];
if (user.name.length > 0) {
    userAttributes.name = user.name;
}
if (user.email.length > 0) {
    userAttributes.email = user.email;
}
[Intercom updateUser:userAttributes];
```

**Comment by alexblack** [comment]
Thanks, ah it was our mistake, we'd accidentally specified empty values for name and email on the company object, and that error tripped us up.
