### ISSUE TITLE
Unauthorized Token error

### ISSUE THREAD

**Issue by croyneaus4u** [intercom/intercom-ios#91]
I integrated the Intercom iOS sdks with the default API key that was provided to me on startup and everything was working fine. But when I generated a full access API Key and tried to register  using the new API key, I am getting `unauthorised token` Error. The sdks version is v2.3.4

**Comment by jtreanor** [comment]
Hi @croyneaus4u,

You can only use an iOS API key with the iOS SDK. The key you generated is intended to be used only with the REST API.
