### ISSUE TITLE
Support CocoaPods frameworks

### ISSUE THREAD

**Issue by orta** [intercom/intercom-ios#94]
Since migrating our app to [use frameworks](https://github.com/artsy/energy/pull/50) - we're now seeing:

```
2015-09-16 16:31:33.837 FolioDev[82249:24127656] [Intercom] ERROR - 💥👎 The Intercom.bundle hasn't been added to your app correctly. This will result in images not appearing in the SDK's messaging UI. More information on how to correctly integrate the Intercom SDK and it's bundle is available here: https://github.com/intercom/intercom-ios#manual-installation.
```

I'm guessing you're currently vending a static library that fakes being a framework? One solution is to start going full out framework style, you can use Marius Rackwitz' [xcconfigs](https://github.com/mrackwitz/xcconfigs/) to make that easier on your devs. Or you can ship an open source SDK - which is a better option IMO. 

Now that iOS9 is out, I'd expect a lot more people to start using frameworks :+1:

**Comment by jtreanor** [comment]
Thanks for reporting this @orta.

The supplied framework is built using [CocoaPods Packager](https://github.com/cocoapods/cocoapods-packager). Unless I'm mistaken, I don't think it is possible for us to use actual (dynamic) Frameworks due to that fact that we still support iOS 7.

We currently check both `[NSBundle bundleForClass:]` and `[NSBundle mainBundle]` for the Intercom bundle before printing the error you are seeing. I'm not overly familiar with CocoaPods frameworks. Is there another way I could be loading the bundle?

**Comment by orta** [comment]
Yeah, iOS7 is a shame, but very understandable. I'd expect them to be in the main bundle, given that you're using `resources` which should be putting them inside the application itself. I won't be touching this app again till next week though, so I can get back with a confirmation or you can make a demo project and add this Podfile:

```
use_frameworks!
pod 'Intercom'
```

**Comment by jtreanor** [comment]
Thanks @orta.

I will test it out in a sample app and track it down.

**Comment by jtreanor** [comment]
I have put together a simple sample app with the Podfile you posted above and the bundle was loaded fine. I've uploaded it [here](http://d.pr/f/1a5LD).

Is there anything unusual about your setup that may cause it to behave differently?

**Comment by orta** [comment]
Ouh! Must be, alright, I'll let you know :+1:

**Comment by jtreanor** [comment]
Let me know if I can help with tracking it down :smile:

**Comment by orta** [comment]
I own a copy of Hopper, nothing is out of my reach :dancers:

**Comment by jtreanor** [comment]
:smile:

**Comment by ded** [comment]
I was able to get Intercom working with Pods for iOS 9 with no problem (with the exception of setting `ENABLE_BITCODE='NO'`).

**Comment by jtreanor** [comment]
@orta Did you have any luck getting this to work with CocoaPods Frameworks? Let me know if I can help out :smile:

**Comment by orta** [comment]
Ah yeah, we reverted from frameworks due to their impact on lunch times - https://github.com/artsy/energy/pull/77

So never got around to debugging my issue.

**Comment by jtreanor** [comment]
@orta :+1: 

Feel free to reopen if you encounter this again.
