### ISSUE TITLE
Programmatic customization of user interface appearance

### ISSUE THREAD

**Issue by mjbeauregard** [intercom/intercom-ios#95]
I'd like to integrate this with an app that has it's own themes that are changed at runtime. I need a way to adjust the theme of the Intercom user interfaces programmatically.

**Comment by adamkmccarthy** [comment]
Thanks @mjbeauregard - we're doing some research into these kinds of options at the moment. Although it isn't flexible right now, we're looking at options here for future releases for sure. Thanks!
