### ISSUE TITLE
restoring Intercom.presentConversationList() key window

### ISSUE THREAD

**Issue by ded** [intercom/intercom-ios#96]
Hi there!

I've successfully integrated everything smoothly, and all works fine for a general purpose flow. I can call `Intercom.presentConversationList()` within a tap gesture, and it works perfectly.

I've since added a deep linking feature into our application, eg: (`our-app-protocol://product/123`), which opens up our app directly to our product view. Thus, when our team responds to a user in the chat view, we can add a link such as `http://redirector.ourapp.com/product/123` which does a straight redirect to `our-app-protocol://product/123` so the user can click on the link in the chat view and see the product view seamlessly in our app :grinning: 

see our `AppDelegate.swift` section where we implement the `openURL`

``` swift
func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
    if (url.scheme == "ltl" && url.host == "product" && (url.path! =~ "^\\/\\d+").boolValue) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)

        let main = storyboard.instantiateViewControllerWithIdentifier("MainEntry") as! MainEntryViewController
        self.window?.rootViewController = main

        let vc = storyboard.instantiateViewControllerWithIdentifier("CartItemDetail") as! CartItemDetailViewController
        self.window?.makeKeyAndVisible()
        self.window?.rootViewController?.presentViewController(vc, animated: true, completion: nil)
        return true
    }
    return false
}
```

Within this `CartItemDetailViewController`, a user can add a product to their shopping cart, and/or dismiss this view. It is essentially at this point that I'd like to restore the chat view that the user was last on.

Typically, if a user re-enters an app (just after closing it), they land where they last left off.

Any advice on how I can make this work?

**Comment by ded** [comment]
Hi there,
I've been noticing activity on the repo given attention to other issues. This seems alright given the severity of them, and I understand priority needs to go to the most important issues.

When you get a chance would someone mind having a look at this issue and let me know if this is an Intercom issue, or if there is another known workaround to restoring the Intercom window as the keyWindow.

**Comment by jtreanor** [comment]
Hi @ded

It is not possible to directly restore the window after closing because it is destroyed immediately tom ensure it doesn't use unnecessary resources.

At the moment the closest you can do is call `[Intercom presentConversationList]` and let them re-enter the conversation they were in.

**Comment by ded** [comment]
Alrighty. I've called `Intercom presentConversationList()` upon returning to the app, but no window is shown... (I can verify that the tap gesture is being received).

**Comment by jtreanor** [comment]
That is very surprising @ded. Can you double check that you are calling it from the main thread?

**Comment by ded** [comment]
@jtreanor Here's what I have. Not sure if it's an issue with Intercom, or I've just implemented my flow incorrectly.

Have a look. http://cl.ly/1z3O08122b01

**Comment by jtreanor** [comment]
Thanks @ded. I will investigate this exact case tomorrow. 

However, I believe this should work for you if you send the deep link to you app directly in the Intercom message (instead of redirecting through Safari)

**Comment by ded** [comment]
That was my initial preference, but the protocol does not linkify in the chat conversation. Only `http(s)://` would work. If I can type in `ltl://product/123` and make it be linkable in the chat message, that would be awesome

**Comment by jtreanor** [comment]
Your `ltl://` aren't linkified automatically but you can link to it in the Intercom composer. For example if your message is: `Tap here to see more`, you can highlight `here` and add a link to it.

**Comment by ded** [comment]
perfect. that works just right!
