### ISSUE TITLE
v2.3.5 introduced 200+ compiler warnings

### ISSUE THREAD

**Issue by hanssl** [intercom/intercom-ios#99]
After I upgraded from 2.3.4 to 2.3.5+ Xcode now reports 200+ compiler warnings from the Intercom pod.
![screen shot 2015-09-23 at 10 10 39 am](https://cloud.githubusercontent.com/assets/649957/10050839/8af58ee0-61db-11e5-8f2d-89e28d6ca7e6.png)

**Comment by jtreanor** [comment]
Thanks @hanssl.

This is being tracked in #97. we are working on resolving it at the moment. There seems to be a bug in Xcode so we are working around it.
